### ISSUE TITLE
Cannot mount nginx config to volume in nginx container using docker-compose or docker

### ISSUE THREAD

**Issue by gegana** [docker/for-win#100]
Using docker command to run official nginx image with custom mounted nginx configuration should result in a running nginx container with the configuration file mounted in the specified volume where nginx can read of.

Or
Using docker-compose with the following yaml file:
```
version: '2'
services:
    helloworld-service:
        container_name: helloworldapp
        build: .

    reverse-proxy:
        container_name: reverse-proxy
        image: nginx
        ports:
         - "9090:8080"
        volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
```

### Expected behavior
A nginx container reading configuration from /etc/nginx/nginx.conf.

### Actual behavior
```
docker-compose up -d
Creating helloworldapp
Creating reverse-proxy

ERROR: for reverse-proxy  Cannot start service reverse-proxy: oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/4937f1cafcc6313acaeb329840e49abcfa10ec33516ea56fd92ded47bc16addc/etc/nginx/nginx.conf" to rootfs "/var/lib/docker/aufs/mnt/4937f1cafcc6313acaeb329840e49abcfa10ec33516ea56fd92ded47bc16addc" caused "not a directory"
[31mERROR[0m: Encountered errors while bringing up the project.
```

### Information
Was run on Windows 10 professional (I actually just bought after reading up about the Docker for windows native support)... Obviously not using DockerToolbox.

All drives are shared under docker settings.

**EDIT**
I tried the following yaml so to map the folder first then the file. It seems like the file is being mapped as a directory... Why is that?
```
version: '2'
services:
    helloworld-service:
        container_name: helloworldapp
        build: .

    reverse-proxy:
        container_name: reverse-proxy
        image: nginx
        ports:
         - "9090:8080"
        volumes:
         - .:/etc/nginx/
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
```
