### ISSUE TITLE
Volume with local driver bind mount volumes are not reliable with WSL2

### ISSUE THREAD

**Issue by Nimamoh** [docker/for-win#10060]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

Container not able to start after reboot.

### Expected behavior

Container able to start after reboot.

### Information

In using a volume bind mount I noticed the volume had to be redefined after each reboot.

  - Windows Version: W10 2004
  - Docker Desktop Version: 3.0.4
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Here are the step to reproduce:
```
mkdir bound-folder
```
`docker-compose.yml`:
```
version: "3"
services:
  web:
    image: nginx
    restart: always
    volumes:
      - bound-vol:/tmp/bound

volumes:
  bound-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./bound-folder
```

Then: `docker-compose up -d`. The container is OK, with the volume correctly mounted

Reboot.

The container failed to start, when trying to `docker-compose up -d` again:

```
ERROR: for local-volume-bind-mount_web_1  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/local-volume-bind-mount_bound-vol/_data': failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/3630eb0615a80795eadd39aeb03f70db9dc9d0b8dc06b64e3a6d884619da3b7f:/var/lib/docker/volumes/local-volume-bind-mount_bound-vol/_data, flags: 0x1000: no such file or directory
```
