### ISSUE TITLE
Docker Desktop 3.0.4 Upgrade Breaks GELF Logging Driver

### ISSUE THREAD

**Issue by lofbacke** [docker/for-win#10081]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D546E9F4-8C1F-48CE-A431-189457BE23FB/20210112223535
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker container does not forward logs to designated UDP port using GELF logging driver.

### Expected behavior
Docker container should forward logs from .NET Core container to the UDP port designated in the docker-compose file.

### Information
This is a reproducible issue that appeared after I upgraded from Docker Desktop 3.0.0 to 3.0.4. To be 110% sure, I uninstalled 3.0.4, reinstalled 3.0.0, and tried it again. The logs were successfully forwarded again in 3.0.0. When I re-upgraded to 3.0.4, it stopped working again.

  - Windows Version: Windows 10 Home Edition, 10.0.19042
  - Docker Desktop Version: 3.0.4 (51218)
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Create a .NET Core 3.1 application that produces logs (I use Serilog and log to the console) using the following Dockerfile:
  ```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["ProjectDirectory/ProjectName.csproj", "ProjectDirectory/"]
RUN dotnet restore "ProjectDirectory/ProjectName.csproj"
COPY . .
WORKDIR "/src/ProjectDirectory"
RUN dotnet build "ProjectName.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ProjectName.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProjectName.dll"]
  ```
  2. Set up the container to use the GELF logging driver and log to the UDP port of your choice. I am using Seq, so my docker-compose file is as follows:
  ```
version: '3.5'

services:
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ../seq-data:/data

  api:
    image: myimagename:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "49524:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - seq-input-gelf
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  ```
  3. Execute the docker-compose file. Logs are not forwarded to Seq.

Please let me know if more information is required. Thanks in advance!
