### ISSUE TITLE
Linux Client, Windows (WSL2) Host:  trying to mount a directory onto a file (or vice-versa) issue

### ISSUE THREAD

**Issue by cribmove** [docker/for-win#10309]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have tried downgrading
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend
  - [x] Tested with 20.10.2
  - [x] Tested with 19.03.13
  - [x] Increased ssh MaxSessions on windows to 500
  - [x] Uninstalled & downgraded both docker client and the docker host.
  - [x] Ubuntu Client and Windows 10 Host

### Scenario
I'm trying to docker compose up on a linux client with a windows remote host running WSL2.

Example service:

```
phpfpm:
    container_name: example_php
    tty: true # Enables debugging capabilities when attached to this container.
    restart: always
    build:
      dockerfile: php.dockerfile
      context: .
    environment:
      - PHP_IDE_CONFIG=serverName=example.localhost
    hostname: example_php
    networks:
      - devenv_devenv
    labels:
      kompose.service.type: nodeport
    ports:
      - '9004'
    volumes:
      - ./src:/var/www/example
      - ./php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
```

### Actual behavior

'\u001b[1A\u001b[2K\rStarting example_php ... \u001b[31merror\u001b[0m\r\u001b[1B\n' +
    'ERROR: for example_php  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/1b45634ef83bac541b99de62b3828f964d7dbfc23eb265270000aa0e5a7fbcb9\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/ba98060dbf3d0d2de1dcd65fe6721ec96d5b3de47a08472059d214420d6d91bb/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/ba98060dbf3d0d2de1dcd65fe6721ec96d5b3de47a08472059d214420d6d91bb/merged/opt/bitnami/php/etc/php-fpm.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\n' +
    '\n' +
    'ERROR: for phpfpm  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/1b45634ef83bac541b99de62b3828f964d7dbfc23eb265270000aa0e5a7fbcb9\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/ba98060dbf3d0d2de1dcd65fe6721ec96d5b3de47a08472059d214420d6d91bb/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/ba98060dbf3d0d2de1dcd65fe6721ec96d5b3de47a08472059d214420d6d91bb/merged/opt/bitnami/php/etc/php-fpm.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\n' +
    'Encountered errors while bringing up the project.

### Expected behavior

Just mounting the file would be nice.

### Information

I believe this may be an edge case and none-urgent. If someone else could replicate this issue that would be great. The reason for having a windows remote host (my desktop) is due to resource intensive containers crippling my laptop.

### Steps to reproduce the behavior

  1. Have a linux docker client
  2. Have a windows remote host through ssh
  3. Mount a file to a service directory in docker compose

I hope this ticket is detailed and sufficient for the community.
