### ISSUE TITLE
Volumes don't work after docker restart

### ISSUE THREAD

**Issue by Morgy93** [docker/for-win#1041]
### Expected behavior
I have my docker container up and running fine and after restarting docker itself it should restart and work again fine with all volumes.

### Actual behavior
I have my docker container up and running fine and after restarting docker itself my defined volumes are missing. We'll they're there but the content is missing.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: EF5CEE54-6553-4655-A810-98A1549E5A7D/2017-08-25_11-02-49
  - a reproducible case if this is a bug, Dockerfiles FTW:

```
version: "3"
services:

  web:
    image: mgtcommerce/mgt-development-environment-5.6
    container_name: mgt
    hostname: mgt
    network_mode: bridge
    privileged: true
    ports: 
      - "80:80"
      - "443:443"
      - "22:22"
      - "3306:3306"
      - "3333:3333"
    volumes: 
      - ./htdocs/:/home/cloudpanel/htdocs_local/
      - ./sync/:/home/cloudpanel/sync/
      - ./mysql/:/var/lib/mysql_local/
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
    restart: on-failure
```
  - host distribution and version (Windows version, build number, etc): Windows 10 Pro v1703 build 15063.540

### Steps to reproduce the behavior

  1. Start container: `docker-compose up`
  2. Go inside container: `docker exec -it mgt bash`
  3. Look for files `ls /home/cloudpanel/sync`
  4. See that your lokal foles from the sync folder should be there
  5. Exit docker completely and restart the program
  6. Go inside container: `docker exec -it mgt bash`
  7. Look for files `ls /home/cloudpanel/sync`
  8. See that your local files are missing now. **<- this is the actual issue**
__OPTIONAL:__
  9. Stop the container: `docker-compose stop`
  10. Start the container again: `docker-compose start`
  11. See that it's working fine again. =)
