### ISSUE TITLE
docker-compose fails to mount mounted folders correctly

### ISSUE THREAD

**Issue by ad-on-is** [docker/for-win#10541]
I have the following scenario

- I mount a VHDX into WSL2 under `/mnt/wsl/PhysicalDrive5p5`
- then I `mount --bind /mnt/wsl/PhysicalDrive5p5 /home/username` to my users home folder
- In a docker-compose.yml I have 
``` ...
    volumes:
       - ~:${HOME}
```

For some reason the folder `/home/username` in a Docker container does not have the contents of the WSL2 /home/username folder, but has the old folders/files instead, which are present before executing `mount --bind`

Am I missing something here?

**Comment by mattford** [comment]
I'm seeing a similar problem with `docker-compose up -d`

```
version: "3"
networks:
    net:
        driver: bridge
services:
    web:
        image: php:7.4-apache
        restart: always
        networks:
            - net
        ports:
            - "8080:80"
            - "6006:6006"
        volumes:
            - ~/myapp:/var/www/app
```

When I use `docker exec -it web_1 /bin/bash` the `/var/www/app` folder is empty.

However if I run: `docker run -v ~/myapp:/var/www/app php:7.4-apache` from WSL, the folder is mounted correctly
