### ISSUE TITLE
docker-compose by Docker desktop 3.2.1 failed to render environment variables in .env file

### ISSUE THREAD

**Issue by Void9711** [docker/for-win#10617]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

After upgrading to **3.2.1**, my docker-compose in cmd failed to render environment variables in .env file, with following command:

`docker-compose -f docker-compose.yml --env-file .env up`

```
ERROR: Missing mandatory value for "image" option interpolating amazon/dynamodb-local:${DYNAMODB_LOCAL_VERSION:?Cannot find env DYNAMODB_LOCAL_VERSION} in service "dynamodb-local": Cannot find env DYNAMODB_LOCAL_VERSION
```

`DYNAMODB_LOCAL_VERSION` is interpolated as an environment variable in `image` option of docker-compose.yml.

.env file:

```
DYNAMODB_LOCAL_VERSION=1.12.0
```

### Expected behavior

Acts as before (like **3.1.0**), `docker-compose up` succeeded.

<https://docs.docker.com/compose/environment-variables/>

### Information

  - Windows Version: 2004 (OS Build 19041.804)
  - Docker Desktop Version: **3.2.1**
  - WSL2 or Hyper-V backend? Both have this issue 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

1. `docker-compose.yml` failed to up in **3.2.1**:

```yaml
version: '3'

services:
  dynamodb-local:
    image: "amazon/dynamodb-local:${DYNAMODB_LOCAL_VERSION:?Cannot find env DYNAMODB_LOCAL_VERSION}"
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "db", "-sharedDb"]
    # Specify "env_file" here solved this failure
    # env_file:
    #   - .env
    networks:
      server-net:
    volumes:
      - ./dynamodb-local/db:/home/dynamodblocal/db
    ports:
      - "8000:8000"
networks:
  server-net:
    external: true
```
