### ISSUE TITLE
Docker freezed randomly at starting a container

### ISSUE THREAD

**Issue by StarpTech** [docker/for-win#1097]
### Expected behavior
Container should start immediately

### Actual behavior
Docker is freezed and nothing happens.

### Information

- A diagnostic was uploaded with id: 67236A24-F2DD-4251-B5C0-3AB8EA21BF58/2017-09-14_20-50-53
- Windows 10 Pro N (64bit), Version: 1703

### Steps to reproduce the behavior
1. Start docker for windows
2. Start a container
```
Creating network "project_default" with the default driver
Creating project_db_1 ...
Creating project_db_1
// here freezed
```

My docker-compose file
```
version: "3"
services:
  db:
    image: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
      - 11211:11211
```

### Workaround
Restart docker and it works fine again but after some time I run into the same issue

Complete log after success
```
Attaching to project_dbb_1
db_1  | Starting Couchbase Server -- Web UI available at http://<ip>:8091 and logs available in /opt/couchbase/var/lib/couchbase/logs
```
