### ISSUE TITLE
Docker Image Always Using Stale File/Data

### ISSUE THREAD

**Issue by riez** [docker/for-win#11349]
#### Windows
![image](https://user-images.githubusercontent.com/37952353/120221626-ef2ca580-c268-11eb-8cf4-e091eccf84dd.png)
#### App Version
![image](https://user-images.githubusercontent.com/37952353/120221715-14211880-c269-11eb-9652-e189a699640c.png)

### Actual behavior
I'm using docker volumes bind. But the files inside the container is always stale and never following update from the host.
Eg.
Container file:
- index.js
Host file:
- index.js

When I add new file or update index.js the container is not following.
Container file:
- index.js
(the newfile.js should be here, but it doesn't)
Host file:
- index.js
- newfile.js

### Expected behavior
- The file should always updated .

### Dockerfile
`path: /test/Dockerfile`
```
FROM node:14-alpine3.12 as builder
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN pnpm install

FROM node:14-alpine3.12
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 4000
```
### docker-compose.yml
```
version: '3.6'
services:
  test:
    build: ./test
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./test
        target: /app
```
### Note
- I use the same file configuration on MacOS, it doesn't happen. All good. Also been testing it on Linux server.
- Been trying these command:
```
docker-compose down --rmi all && docker-compose up -d --build
```
```
docker-compose up -d --force-recreate --renew-anon-volumes
```

Still no luck
