### ISSUE TITLE
Can't stop/remove docker-compose containers group when override file is in the same directory

### ISSUE THREAD

**Issue by wiktor-golonka** [docker/for-win#11445]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features 
  
  (none of experimental features is enabled)
  
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

## Steps to reproduce
1. Run `docker-compose up` in a directory with`docker-compose.yml` and `docker-compose.override.yml`.
2. Containers starts properly
3. Click stop (or remove) button on whole group in docker-desktop.

### Actual behavior
None of the containers being stopped. 
Docker desktop shows error message:

Error message: 
```
Cannot stop Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: docker-compose --file "docker-compose.yml,docker-compose.override.yml" --project-name "docker-compose" --project-directory "DIRECTORY\docker-compose" stop .FileNotFoundError: [Errno 2] No such file or directory: '.\\docker-compose.yml,docker-compose.override.yml'
```

### Expected behavior
Containers stops without any error

### Information
 - Is it reproducible?
Yes. Error appeared on:
a) a clean installation of docker desktop v3.4.0 on machine 1
b) after updating from docker v3.3.x to v3.4.0 on machine 2

 - Is the problem new?
Yes. 

 - Did the problem appear with an update?
Yes, after updating from version v3.3.x to v.3.4.0 and also on clean installation of v3.4.0 on a different machine.
It was working properly on v3.3.x.

 - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

docker-compose.yml
```
version: '3.4'

services:

    redis:
        image: redis:5.0.7

    postgres:
        image: postgres:10
```

docker-compose.override.yml 
```
version: '3.4'

services:
    redis:
        command: redis-server
        ports:
            - 5666:6379

    postgres:
        environment:
            - POSTGRES_PASSWORD=qwerty1234
        ports:
            - 5667:5432
```

  - Windows Version:
  1. Windows 10 21390.1000
  2. Windows 10 21H1
  
  - Docker Desktop Version:
  a) 3.4.0
  b) 3.4.0
  
  - WSL2 or Hyper-V backend?  
  WSL2
  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  a) No
  b) No
