### ISSUE TITLE
In WSL2, Kubernetes local volumes end up in strange location

### ISSUE THREAD

**Issue by vincent-163** [docker/for-win#11811]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 65E4490D-A5B0-451B-AD29-EAB0B14D5EAC/20210802084824

### Actual behavior

The mounted volume ends up in `/mnt/version-pack/containers/services/docker/rootfs/mnt/wsl/data` in the `docker-desktop` distro.

### Expected behavior

The mounted volume ends up in `/mnt/wsl/data` which is shared across all distros.

### Information

  - Windows Version: Windows 11 21H2, 22000.100
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, it's on a laptop

### Steps to reproduce the behavior

Use the following Kubernetes configuration:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  terminationGracePeriodSeconds: 30
  containers:
  - name: bash
    image: alpine
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /mnt/wsl/data
      type: DirectoryOrCreate
```
Create the above pod using `kubectl create -f <file>.yaml`. No directory is created under `/mnt/wsl`. Instead, the path `/mnt/wsl/data` is created at `/mnt/version-pack/containers/services/docker/rootfs/mnt/wsl/data`, leaving no way to mount a folder from a WSL2 distro into Kubernetes.
