### ISSUE TITLE
Docker compose fails to start container with mapped volumes : Fails error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

### ISSUE THREAD

**Issue by markddrake** [docker/for-win#12227]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:ECFBB5DA-D5F0-468D-82B7-B62EA973BCCF/20211001065102

### Actual behavior
Docker Compose fails to start container
```
C:\yadamu>docker-compose --file=docker\dockerfiles\docker-compose-windows.yml up -d
Creating network "YADAMU-NET" with the default driver
Creating volume "YADAMU_01-SHARED" with default driver
Creating volume "dockerfiles_MSSQL14-01-DATA" with default driver
Creating volume "dockerfiles_MSSQL14-01-LOG" with default driver
Creating MSSQL14-01 ... error

ERROR: for MSSQL14-01  Cannot start service MSSQL14-01: container a2e579e8e5e8aea455cff46f85793f6bd87601b5d444f51fe1ebe50f65ac919f encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

ERROR: for MSSQL14-01  Cannot start service MSSQL14-01: container a2e579e8e5e8aea455cff46f85793f6bd87601b5d444f51fe1ebe50f65ac919f encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)
ERROR: Encountered errors while bringing up the project.

```
### Expected behavior
Container should start
### Information

```
version: "2.4"
services:

  MSSQL14-01: 
      container_name: MSSQL14-01
      image:  yadamu/mssql:2014
      mem_limit: '16gb'
      shm_size: '4gb'
      networks:
        - YADAMU-NET
      ports: 
        - "1435:1433"
      environment:
        ACCEPT_EULA: Y
        MSSQL_MEMORY_LIMIT_MB: 16384
        SA_PASSWORD: oracle#1
      volumes:
        - YADAMU_01-SHARED:c:\docker\shared
        - MSSQL14-01-DATA:C:\MSSQL12.MSSQLSERVER\MSSQL\DATA
        #- MSSQL14-01-LOG:C:\MSSQL12.MSSQLSERVER\MSSQL\LOG
      restart: always
  
networks: 
  YADAMU-NET:
     name: YADAMU-NET
  
volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#     device: c:\docker\shared
  MSSQL14-01-DATA:
  MSSQL14-01-LOG:
```
Note if I comment out the line   - MSSQL14-01-DATA:C:\MSSQL12.MSSQLSERVER\MSSQL\DATA the container will start

  - Windows Version: 10 21H1
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?   Hyper V - Windows Container
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
See Above.

In my Image the folders C:\MSSQL12.MSSQLSERVER\MSSQL\DATA exist and contain data. 

I am not sure how I can provide the 18G Image that is :  yadamu/mssql:2014

**Comment by lorenrh** [comment]
Can you please share the output of `docker-compose -v`?

**Comment by markddrake** [comment]
It's Identical
```
C:\yadamu>docker-compose --file=docker\dockerfiles\docker-compose-windows.yml up -d -V
Recreating MSSQL14-01 ... error

ERROR: for MSSQL14-01  Cannot start service MSSQL14-01: container 86522773cd0bf4c153c293342c32069f7c9da2a58f9f0ce82f1fbe10c3b60fb6 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

ERROR: for MSSQL14-01  Cannot start service MSSQL14-01: container 86522773cd0bf4c153c293342c32069f7c9da2a58f9f0ce82f1fbe10c3b60fb6 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)
ERROR: Encountered errors while bringing up the project.

C:\yadamu>
```

**Comment by markddrake** [comment]
Issue you mean upper case 'V'

**Comment by markddrake** [comment]
FYI 

```
C:\yadamu>docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 20.10.7
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19043.1237)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.89GiB
 Name: YADAMU-DB3
 ID: YUMN:T4JT:IBBW:XTIK:EEGC:KQLR:AHI5:O2T7:NIW6:4HQ5:P2OY:MZLN
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine


C:\yadamu>
``

**Comment by markddrake** [comment]
```
C:\yadamu>docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

C:\yadamu>
```

**Comment by markddrake** [comment]
Also, problem will reproduce with this docker compose file which uses an image from the docker repository

```
version: "2.4"
services:

  SS2014-01: 
      container_name: SS2014-01
      image:  dbafromthecold/sqlserver2014dev:sp2
      mem_limit: '16gb'
      shm_size: '4gb'
      networks:
        - YADAMU-NET
      ports: 
        - "1435:1433"
      environment:
        ACCEPT_EULA: Y
        MSSQL_MEMORY_LIMIT_MB: 16384
        SA_PASSWORD: oracle#1
      volumes:
        - YADAMU_01-SHARED:c:\docker\shared
        - SS2014-01-DATA:c:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA
        - SS2014-01-LOG:c:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Log
      restart: always
  
networks: 
  YADAMU-NET:
     name: YADAMU-NET
  
volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#     device: c:\docker\shared
  SS2014-01-DATA:
  SS2014-01-LOG:
  
```

My original example was derived from this one, but attempted to remove the spaces from the target path names in case they were the cause of the error.

```
C:\yadamu>docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

C:\yadamu>docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

C:\yadamu>docker images
REPOSITORY                        TAG       IMAGE ID       CREATED         SIZE
yadamu/mssql                      2014      e6e12e199f9a   9 hours ago     18.9GB
mcr.microsoft.com/windows         2004      9e30cb60b773   12 months ago   12.9GB
dbafromthecold/sqlserver2014dev   sp2       d1dfe544c4fc   4 years ago     18.7GB

C:\yadamu>docker-compose --file=docker\dockerfiles\docker-compose-ss2014.yml up -d
Creating SS2014-01 ... error

ERROR: for SS2014-01  Cannot start service SS2014-01: container dd14ba823dff5264cdfbf659313fdfc6dd7a25235d5afa53a9eb8e3d1492e3a1 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

ERROR: for SS2014-01  Cannot start service SS2014-01: container dd14ba823dff5264cdfbf659313fdfc6dd7a25235d5afa53a9eb8e3d1492e3a1 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)
ERROR: Encountered errors while bringing up the project.
```
