### ISSUE TITLE
Mounting NFS volume fails "timed out waiting for the condition"

### ISSUE THREAD

**Issue by DILeak** [docker/for-win#12281]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5221CDB1-EBAD-4999-9CAA-4085EA28B052/20211017191453

### Actual behavior
Pod fails to mount NFS volume, giving this error:
```
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    4m59s  default-scheduler  Successfully assigned test-project/test-digit-5576c79688-zfg8z to docker-desktop
  Warning  FailedMount  2m56s  kubelet            Unable to attach or mount volumes: unmounted volumes=[lagg-connection], unattached volumes=[lagg-connection kube-api-access-h68w7]: timed out waiting for the condition
  Warning  FailedMount  37s    kubelet            Unable to attach or mount volumes: unmounted volumes=[lagg-connection], unattached volumes=[kube-api-access-h68w7 lagg-connection]: timed out waiting for the condition
```
### Expected behavior
Pod mounts the volume.

### Information
  - Is it reproducible?
  Yes, if I reset my kubernetes cluster and re-apply the below yam, it happens again. I have not tried on other computers using Docker for Win.
  - Is the problem new?
  Yes, I'm not entirely sure what changed from when it used to work. I was on 4.0.1, and after upgrading to 4.1.1 it worked 1 time. After deleting the entire namespace or resetting the cluster again, it stopped working.
  - Did the problem appear with an update?
  No

  - Windows Version:
  10 Pro 10.0.19043
  - Docker Desktop Version:
  4.1.1 (69879)
  - WSL2 or Hyper-V backend?  
  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  No

### Steps to reproduce the behavior
1. Reset the cluster to factory
2. Apply the below yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-project
  labels:
    name: test-project
---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: test
  name: test-nfs
  namespace: test-project
spec:
  clusterIP: 10.96.13.37
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
    environment: test
    scope: backend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    environment: test
  name: test-nfs-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /
    server: 10.96.13.37
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    environment: test
  name: test-nfs-claim
  namespace: test-project
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static
    environment: test
    scope: backend
  name: test-worker
  namespace: test-project
spec:
  selector:
    matchLabels:
      app: static
      environment: test
      scope: backend
  template:
    metadata:
      labels:
        app: static
        environment: test
        scope: backend
    spec:
      containers:
      - image: busybox
        name: worker
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        volumeMounts:
        - mountPath: /cache
          name: nfs-connection
      volumes:
      - name: nfs-connection
        persistentVolumeClaim:
          claimName: test-nfs-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: test-nfs
  namespace: test-project
spec:
  selector:
    matchLabels:
      app: nfs-server
      environment: test
      scope: backend
  template:
    metadata:
      labels:
        app: nfs-server
        environment: test
        scope: backend
    spec:
      containers:
      - image: gcr.io/google_containers/volume-nfs:0.8
        name: nfs
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 20048
          name: mountd
        - containerPort: 111
          name: rpcbind
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /exports
          name: nfs-claim
      volumes:
      - emptyDir: {}
        name: nfs-claim
```
