### ISSUE TITLE
Second docker-compose up hangs while starting windows container

### ISSUE THREAD

**Issue by starky27** [docker/for-win#12299]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Second launch of "docker-compose up" hangs while starting a container. It is released after another container which was also launched by "docker-compose up" is stopped. 
While a container hangs, any "docker container" operation on it hang.

### Expected behavior

Expect a container won't be blocked by another container.

### Information

  - Windows Version: 10.0.19043.1288 / 10.0.19042.508
  - Docker Desktop Version: 4.1.1 (69879)
  - WSL2 or Hyper-V backend?  Hyper-V 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: tried both ways

### Steps to reproduce the behavior

To reproduce create two folders: test1 and test2 with docker-compose.yml and Dockerfile on each folder.

Test1 docker-compose.yml:
```

version: '3.8'

services:
  test1:
    image: test1:latest
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "19500:19500"
```

Test2 docker-compose.yml:

```
version: '3.8'

services:
  test2:
    image: test2:latest
    isolation: process
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "18500:18500"

```

Dockerfile for test1 and test2 is the same:

`FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-20H2
`

  1. (to reproduce second and subsequent times) Stop and remove test1, test2 containers. Remove test1, test2 images. Restart PC (docker restart is not enough)
  2. new cmd, cd test1, docker-compose up
  3. new cmd, cd test2, docker-compose up, wait for start
  4. test2> ctr+c, wait for stop
  5. test2> docker-compose up. it hangs
  6. test1> ctrl+c, the test2 is released and starts normally

If **the ports are removed** from yml file, it works fine.
When any container is created the is also an error in EventViewer (not sure if it's related to the bug).
The error looks like:

_exec's CreateProcess() failed [module=libcontainerd namespace=moby container=e26740989c50d11ce9da51426614fc4b47637f29604bf651e48b0a0ddfa9cdca exec=647fb1f34b661565c8481a08d3a14bbad3077a462da15d23a7ea8d1887e2f9e2 error=container e26740989c50d11ce9da51426614fc4b47637f29604bf651e48b0a0ddfa9cdca encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)]_
