### ISSUE TITLE
Bind not working on WSL

### ISSUE THREAD

**Issue by JKocerka** [docker/for-win#12323]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3317B5DC-C030-49AA-8D1C-2FF5A2436794/20211029125901

### Actual behavior

When I try to bind mount a folder from host containing some files, the folder is created in the container, but it's empty. 

Steps to reproduce: 
- Create a folder on host (eg. `input`). 
- Put some files in there. 
- Run docker container (using powershell):
`docker run --rm -d --mount type=bind,source="$(pwd)\input",target=/inputdocs -p 9000:9000/tcp my_container:latest`

Folder `/inputdocs` exists in the container, but it's empty. 

### Expected behavior

Folder `/inputdocs` contain the files from host. 

### Information
  - Windows Version: Windows 10 Pro 21H1
  - Docker Desktop Version: 4.1.1 (69879)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by rcribeiro** [comment]
I have the same environment as @JKocerka and I'm experiencing the same issue

**Comment by Netzvamp** [comment]
Same here, also with docker compose.

```
volumes:
    config:
        driver: local
        driver_opts:
            o: bind
            device: "${STACKDIR}/config"
            type: none
```
This worked but with one of the last updates we've got that bug. That makes docker desktop useless for me 😞

**Comment by Netzvamp** [comment]
```failed to mount local volume: mount /run/desktop/mnt/host/c/Users/Projects/XXX/XXX/_data, flags: 0x1000: no such file or directory```
I don't see any /run/desktop folder in docker-desktop or docker-desktop-data folder. Is that the source of the problem?

**Comment by Netzvamp** [comment]
Ok, to clarify this bugreport.

In earlier versions i've used this powershell snippet as a workaround, to get my windows folder mounted:

```powershell
$env:STACKDIR = $(wsl wslpath -a '$PWD') -replace "/mnt/c/mnt/c/", "/mnt/host/c/"
# Note: wslpath gives double /mnt/c folders, thats a bug, therefore replace is needed anyways :P
"STACKDIR: " + $env:STACKDIR
docker stack deploy -c docker-stack-wsl.yml mariadb
```

That way i've got the WSL path to my working directory in the environment variable STACKDIR.

and in the compose file i mounted it with that environment variable:

```yml
version: "3"
services:
    mariadb:
        image: mariadb:10.6
        environment:
            MYSQL_ROOT_PASSWORD: changeme
        volumes:
            - "mariadb-cfg:/etc/mysql/conf.d"
            - "mariadb-data:/var/lib/mysql"
        deploy:
            replicas: 1

volumes:
    mariadb-data:
        driver: local
        driver_opts:
            o: bind
            device: "${STACKDIR}/mariadb/data"
            type: none
    mariadb-cfg:
        driver: local
        driver_opts:
            o: bind
            device: "${STACKDIR}/mariadb/cfg"
            type: none
```

That way i got my local/windows mariadb folder in my working directory inside the container, it worked like a charm. (I know, wsl mounts are slow, but it's only for development/experimental)

Now i've got: 

failed to mount local volume: mount /mnt/host/c/MyLocalFolderName/mariadb/cfg:/var/lib/docker/volumes/mariadb_mariadb-cfg/_data, flags: 0x1000: no such file or directory

The /mnt/host/c folder exists in the docker-desktop vm, but not in the docker-desktop-data vm. In docker-desktop-data i've discovered there is a /mnt/c folder. But changing my powershell line to ```$env:STACKDIR = $(wsl wslpath -a '$PWD') -replace "/mnt/c/mnt/c/", "/mnt/c/"``` changes nothing, it also says "no such file or directory".

I hope this helps to reproduce this bug. It's painfull to develop without local mounts 😭
