### ISSUE TITLE
Problematic env file parsing with blanks and equals and hyphen

### ISSUE THREAD

**Issue by in-fke** [docker/for-win#12344]
### Actual behavior

Error
`unexpected character "-" in variable name near "-DA=B\n"`

### Expected behavior

Expecting this to work.

### Information
```
docker --version
Docker version 20.10.8, build 3967b7d
```

```
docker-compose --version
Docker Compose version v2.0.0

```
### Steps to reproduce the behavior
docker-compose.yml

```
version: '2'
services:
  hello_world:
    image: ubuntu
    command: [env]
    env_file:
    - my.env
```

my.env

```
#
X=-Xmx2048 -DA=B
```

run:

```
docker-compose up
unexpected character "-" in variable name near "-DA=B\n"
```

somehow the parser for .env file seems broken (used to work).
