### ISSUE TITLE
Mounting linux path as volume work only first run

### ISSUE THREAD

**Issue by NikitaMelikhov** [docker/for-win#12406]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1F928F67-3743-4F44-8AD1-AFB9551B3852/20211129143918

### Information
  - Windows Version: Windows 10 Home 21H1 19043.1348
  - Docker Desktop Version: 4.2.0 (70708)
  - WSL2 backend - Ubuntu 20.04 LTS

### Steps to reproduce the behavior
I have such docker-compose.yml
```
version: '3'

services:

  traefik:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./environment/${ENVIRONMENT_NAME}/Dockerfile
    image: ${SERVICE_NAME}:${ENVIRONMENT_NAME}
    container_name: traefik
    env_file:
      - .env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - private
      - public
    volumes:
      - traefik-certs:/etc/certs:ro

volumes:

  traefik-certs:
    name: traefik-certs
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/environment/${ENVIRONMENT_NAME}/certs
      o: bind
```

And first time it execute fine but if i restart Windows and try run this container again i getting error:
`Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - error while mounting volume '/var/lib/docker/volumes/traefik-certs/_data': failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/1a8c01243b0f51b6ce3beec294968223f7e139c951cc48880b4f36f9a5e28e01:/var/lib/docker/volumes/traefik-certs/_data, flags: 0x1000: no such file or directory`

Why it fails? And why it works the first time?
