### ISSUE TITLE
Unable to mount a local disk when a volume is defined in a compose file

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [docker/for-win#12449]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When defining a volume inside a compose file like
```yaml
version: '3.8'

services:
  example:
    image: caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
    name: caddy_data
    driver_opts:
      o: bind
      device: d/Some/path_in/my/host
      type: none
```
The volume binding fails with the error
`Error response from daemon: readdirent /var/lib/docker/volumes/caddy-data/_data: operation not permitted`

On closer inspection I have found that setting the device to `/run/desktop/mnt/host/d/Some/path_in/my/host` is successful. This is essentially found by looking into the `opts.json` file in `\\wsl.localhost\docker-desktop-data\version-pack-data\community\docker\volumes` of a manually created volume.
### Expected behavior
One should not need to pass path prefixes for local mounting to work in a compose file
### Information

  - Windows Version: 11 
  - Docker Desktop Version: 4.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
https://pastebin.com/Wh711eJF
### Steps to reproduce the behavior

  1. Create a docker-compose.yaml with the following contents
  ```yaml
version: '3.8'

services:
  example:
    image: caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
    name: caddy_data
    driver_opts:
      o: bind
      device: d/Some/path_in/my/host
      type: none  
  ```
  2. Do, `docker compose up -d`
  3. Compose fails but volume is created. Only the mounting fails.
