### ISSUE TITLE
Docker: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Time out exceeded while awaiting headers)

### ISSUE THREAD

**Issue by waqas-ali-pk** [docker/for-win#12522]
Steps to reproduce the behavior (sample yml file)
```
services:
  redis:
    image: redis
    container_name: verbund-api-redis
    ports:
      - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:1.13
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
postgres:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
memgraph:
    image: memgraph:latest
    ports:
      - "7687:7687"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
volumes:
  postgres:
  mg_lib:
  mg_log:
  mg_etc:
  azurite:
```

Run docker-compose up -d

The port unavailable error shown above is random and does not always happen on the same service. 
Restarting docker desktop and the docker windows service does not resolve the issue.

_Originally posted by @sreaswar in https://github.com/docker/for-win/issues/9273#issuecomment-717638633_

#########################
The port unavailable error shown above is random and does not always happen on the same service. 
Restarting docker desktop and the docker windows service does not resolve the issue.

ERROR:
Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Time
out exceeded while awaiting headers)

**Is there any workaround for this, for windows OS?**
