### ISSUE TITLE
Docker Container Files Not Reflecting in the Mounted Volume (WSL Integration Failure)

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [docker/for-win#12537]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behaviour

Docker Container Files to reflect in the Mounted Volume.

### Expected behavior

After Restarting my Windows System My Container is Working fine, but I'm facing the below two issues:
1. Fresh Container is started (Previous files existed in mounted volume not showing in a container).
2. New Files created are not reflected in the mounted volume.

### Information

  - Windows Version: Win 10 Latest Update
  - Docker Desktop Version: 4.4.4
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behaviour

  1. Pull any Docker image.
  2. Docker-Compose File
```yml
version: "3"

services:
  my_container:
    ipc: host
    restart: always
    image: user/image:latest
    container_name: new_container
    ports:
      - "80:80"
      - "8000:8000"
      - "8080:8080"

    volumes:
      - "./.workspace/:/home/workspace/"
```
3. Then `docker-compose up -d`
4. Work with it, create files in Container, (they will be reflected in Mounted Volume as expected).
5. Restart PC.
6. Now Check container files, you will not be able to find previous files, (but they existed in Mounted Volume)
7. Whatever files you create now, will not be reflected in Mounted Volume, and when you Restart the PC now, you will lose these new files.

### Additional Info

After Step-5 When I open Ubuntu (WSL2) and run `docker ps` I got the below error.

```shell
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

But Container is running, and accessible, but now showing in Ubuntu (WSL2).

If you need any further info, pls let me know

**Note:** This issue is faced by 100s of our Clients.
