### ISSUE TITLE
Dockerengine crashes on bindmount on windows host

### ISSUE THREAD

**Issue by Hu1buerger** [docker/for-win#12531]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86E45E88-615A-49C1-AEAF-6F31E52C7E2C/20220205012321

I am using this docker-compose.yml
<details>

```yml
version: "3"

networks:
  web-proxy:
    driver: bridge

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    networks:
      - web-proxy
    links:
      - "nextcloud:cloud"
    ports:
      - "443:443"
    volumes:
      - $PWD/caddy/caddy_data:/data
      - $PWD/caddy/config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - web-proxy
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS="localhost:80"
      - NEXTCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - "d:/Docker/nextcloud/data:/var/www/html:rw"
```
</details>

### Actual behavior
When running `docker-compose up -d; docker-compose down` multiple times, the docker engine on win 11 (versions see diagnostics) crashes.
Unexpectedly the nextcloud container is not starting fully.

When commenting the volumes mount to disk `d` (see last lines of yml) the crash dosnt seem to happen as often.

### Expected behavior

I expect that the docker daemon bindmounts the d:/Docker/nextcloud/data directory (which exists and is accessible perms wise) and nextcloud comes up.

### Information

  - Windows Version: 
 
Edition	Windows 11 Pro
Version	21H2
Installed on	‎11/‎26/‎2021
OS build	22000.469
Experience	Windows Feature Experience Pack 1000.22000.469.0

  - Docker Desktop Version: 4.4.4 (73704)
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, runs on metal

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

<details>

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
``` 

</details>

### Steps to reproduce the behavior

see above
