### ISSUE TITLE
Docker stack port binding with host mode always restart

### ISSUE THREAD

**Issue by batexam759** [docker/for-win#12597]
I want to use Docker stack deployment for my application. When I try to make a binding between my host and the container, it crashes and restarts in a loop.

Everything works when I use docker-compose or docker service

```
version: "3.9"
services:
  site:
    image: iis:latest
    hostname: iis-test
    isolation: 'hyperv'
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
```

Do you have any idea how to solve this problem?

### Information

  - Windows Version: Windows 10 Pro 20H2 19042.1526
  - Docker Desktop Version: 20.10.12, build e91ed57
  - WSL2 or Hyper-V backend?  Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Windows Desktop
