### ISSUE TITLE
Restart policy does not restart container after server reboot when using Docker Compose for Windows

### ISSUE THREAD

**Issue by bvarilone** [docker/for-win#12606]
Creating a new issue because #9340 was abandoned. This is still an issue.

### Test environment

Windows Server 2019
Docker Enterprise Edition v20.10.9 (build 591094d)
Docker Compose v2.2.3
Container Type: Windows
Container Isolation Mode: Process
Test Docker Image: mcr.microsoft.com/dotnet/samples:aspnetapp

### Problem statement

Given a Windows Docker container started using `docker-compose up -d` with a restart policy of _restart: always_ configured in the Docker Compose configuration file, the container does not automatically restart after rebooting the Windows server running it.

The root cause seems to be that the default network created by `docker-compose up -d` gets removed. Even manually attempting to restart the container using `docker-compose restart` fails with a "network not found" error message. The only way to "restart" the container is to run `docker-compose up -d` again (which actually recreates it). This is the same issue documented on Stack Overflow [here](https://stackoverflow.com/questions/51242398/docker-compose-can-not-start-service-network-not-found-after-restart-docker).

This problem occurs both when using the implicit, default Docker network and when using a named, custom Docker network. (A workaround is to use a persistent, already-existing Docker network. See the _workaround_ section below.)

### Steps to reproduce the "network not found" error

1. Create the following _docker-compose.yml_ file:
```
version: '3.3'
services:
    dotnet:
        restart: always
        ports:
            - '8000:80'
        image: 'mcr.microsoft.com/dotnet/samples:aspnetapp'
```
2. Run `docker-compose up -d` then run `docker ps -a` and confirm the container is running
3. Restart the Windows server
4. Run `docker ps -a` after the restart and note the container is in an _Exited_ state
5. Try manually running `docker-compose restart` and note the "network note found" error message

### Workaround: Use a persistent, already-existing Docker network
1. Run `docker-compose down` to remove the container created in the previous section
2. Update the _docker-compose.yml_ file to use an existing network as follows:
```
version: '3.3'
services:
  dotnet:
    restart: always
    ports:
      - '8000:80'
    image: 'mcr.microsoft.com/dotnet/samples:aspnetapp'
    networks:
      - test
networks:
  test:
    name: nat
```
3. Restart the Windows server
4. Run `docker ps -a` after the restart and confirm the container is running
