### ISSUE TITLE
docker-compose up starts all containers there available in the current folder

### ISSUE THREAD

**Issue by sergak01** [docker/for-win#12632]
- [x] I have tried with the latest version of Docker Desktop
 - [x] I have tried disabling enabled experimental features
 - [x] I have uploaded Diagnostics
 - Diagnostics ID: 024619C0-BD3E-41BE-A861-2F7205F9B81D/20220329170800

### Actual behavior

`docker-compose up` command starts all containers there available in the current folder

### Expected behavior

`docker-compose up` command starts only containers that described in the docker-compose.yml file

### Information

This problem can be reproduced in steps:

I have two different configurations for development purposes: first - just for dev, second - for testing that the code can be working in production (build the image from code and test work in the bundle).

The problem is new to me. 

- Windows Version: Windows 10 Pro 21H2 build 19044.1586
- Docker Desktop Version: 4.6.1 (76265)
- WSL2
- Running without virtualization

### Steps to reproduce the behavior

1. Create two different docker-compose config files in the empty folder
```yml
# docker-compose.yml
version: '3.9'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

```
```yml
# docker-compose.test.yml
version: '3.9'

services:
  nginx:
    image: nginx

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

```
2. Start docker by default config with the command `docker-compose up`. After starting - stop all containers
3. Start docker by providing config with the command `docker-compose -f docker-compose.test.yml up`. After starting - stop all containers
4. Start docker by default config with the command `docker-compose up` and see a list of started containers (in my case - started all containers that are available in the current directory). If we remove the config for the image from the docker-compose file but do not remove the container, this container also started after the `docker-compose up` command. `docker-compose -f docker-compose.test.yml up` command also starts containers, not in the config
