### ISSUE TITLE
WSL uses docker gateway ip for all incoming requests

### ISSUE THREAD

**Issue by Indimeco** [docker/for-win#12644]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6EB5D1E5-F693-40FF-A089-CEF96E95FE1A/20220403100357

### Actual behavior
Requests made to a docker container running from wsl2 via docker compose log the ip of the docker gateway (172.X) as the originator.

### Expected behavior
Requests made to a docker container running from wsl2 via docker compose should log the real incoming client ip.

### Information
I'm running [swag with duckdns](https://docs.linuxserver.io/general/swag#create-container-via-duckdns-validation-with-a-wildcard-cert)

This issue seems to span across multiple devices and setups, but I believe my case is specific to WSL/docker.
This is an important problem because it means all security features that rely on ip logging (fail2ban, geoip) do not work.

Common solutions I've tried with no success:
* run the container as `network_mode: host` or other host variants - It [only works on linux](https://docs.docker.com/network/host/)
* [modify docker iptables](https://www.pedrolamas.com/2020/11/04/exposing-the-client-ips-to-docker-containers-on-synology-nas/) - I don't have any DOCKER rules in iptables in my WSL distro, nothing at all
* do nginx configuration to forward client ips from a proxy - I'm not running a reverse proxy in this example so it shouldn't apply, but I've tried using the [realip_module](http://nginx.org/en/docs/http/ngx_http_realip_module.html) and proxy_pass and custom logging looking for headers, all with no result

I honestly don't know how the container is _supposed_ to know the real client ip, or how such information is _supposed_ to be used by services like nginx. 
I would appreciate any light shed here.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Failed with: contacting Windows service: no hypervisorlaunchtype in bootloader

### Steps to reproduce the behavior
1. Given the following `docker-compose.yml` (the vanilla setup for swag duckdns)
```yml
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=xxx.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=xxx
    volumes:
      - /home/aptalca/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
```
2. When any incoming request goes to the server from a public ip
3. Then `/log/nginx/access.log` shows only the docker gateway ip (172.x)

### Related issues
* https://github.com/docker/for-win/issues/9119 - I tried this solution with my own ip ranges and more, but with no success
* https://github.com/linuxserver/docker-swag/issues/55
* https://github.com/moby/moby/issues/15086
