### ISSUE TITLE
docker compose: Use a bind mount with compose error

### ISSUE THREAD

**Issue by vabic** [docker/for-win#12905]
### Actual behavior
1. *For bind mount syntax: Have this error on `docker compose up`: *`Error response from daemon: hcsshim::CreateComputeSystem 963a96fb4a50e9157f801a370d604348aced616cda13a8b8bbe9e974ad2936d1: The request is not supported.`
```
version: '3.4'
services:
  containerbuilder:
    image: mcr.microsoft.com/windows/servercore/iis
    volumes:
      - type: bind
        source: ../../output/App
        target: "c:/Program Files/Org/App/"
```
2. *For volume syntax `docker compose up` works well!*
 ```
version: '3.4'
services:
  containerbuilder:
    image: mcr.microsoft.com/windows/servercore/iis
    volumes:
       - "../../output/App:c:/Program Files/Org/App/"
 ```
3.  *docker run works well also*:
`docker run  --mount type=bind,source="C:\r\Org\output\App",target="c:\Program Files\Org\App" myimage`

### Information

  - Windows Version: 21H2 Build 19044.1586
  - docker version:
    Client:
    Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:03:58 2022
  OS/Arch:          windows/amd64
  Experimental:     false

Docker Compose version v2.7.0
  - WSL2 or Hyper-V backend?   Hyper-V
