### ISSUE TITLE
In Docker Desktop's Kubernetes with WSL2 non-root user does not have access to the pvc directory

### ISSUE THREAD

**Issue by thesalmonidae** [docker/for-win#13026]
A statefulset with pvc and securityContext is set for non-root user, and the non-root user is created in the Dockerfile.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

The pvc directory is not accessible for the non-root user.

### Expected behavior

The pvc directory is accessible for the non-root user.

### Information

If the securityContext is set for 0 (root's UID and GID), then it works. But for 1000 (non-root user) it does not.

  - Windows Version: Windows 11 Pro, 22H2, 22621.675
  - Docker Desktop Version: 4.13.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Nope.

### Steps to reproduce the behavior

Create a Dockerfile with a non-root user and a statefulset with a pvc and add security context as described below.

```
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
```

The non-root user will not have access to the directory specified in the volumeClaimTemplates.

If the security context is replaced as below.

```
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
```

The non-root user is not used, and the directory specified in the volumeClaimTemplates is accessible.
