### ISSUE TITLE
Unable to access secrets within windows container

### ISSUE THREAD

**Issue by WilliamBehrens** [docker/for-win#13048]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

I'm trying to access a docker secret from in a windows container, According to all documentation after passing a secret into the container it should be accessible at C:\ProgramData\Docker\secrets\<secret-name> but it doesn't appear. The directory C:\ProgramData is never available inside the container when I try and list it's contents.
```yml
  windows:
    image: example.com/windows:test
    build: .
    secrets:
      - api_key
  
secrets:
  api_key:
    file: secrets/api_key.txt
```

### Information
  - Windows Version: Windows 10 22H2
  - Docker Desktop Version: 4.12.0 (85629)
  - WSL2 or Hyper-V backend? Hyper-V (Windows containers)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
