### ISSUE TITLE
Error response from daemon: unsupported os linux with Experimental Features with Windows containers

### ISSUE THREAD

**Issue by GeorgeBetts** [docker/for-win#13110]
I would like to run Windows and Linux platform containers side by side using docker-compose.yml by utilising the platform property of dockers experimental mode.

However when I specify the linux platform for a container I am shown the error "Error response from daemon: unsupported os linux".

I used the following docker-compose.yml to replicate this issue:
```
version: "4.12"
services:
  app:
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    container_name: application
    ports:
      - 8000:80
  db:
    image: mysql:5.7
    platform: linux
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: db_user
    ports:
      - "3306:3306"
```

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
If I run `docker compose up` the console outputs the following error:
```
C:\Dev\docker\testing-dual-os-containers>docker compose up
[+] Running 0/0
 - db Error     0.1s
 - app Error   0.1s
Error response from daemon: unsupported os linux
```

### Expected behavior
Running `docker compose up` should start up both containers, one on the windows platform and the other on linux.

### Information

I switched Docker to Windows containers by right clicking the tray icon and selecting 'Switch to Windows containers...'
I have enabled experimental features in docker by setting the Docker Engine to the following:
```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": true,
  "features": {
    "buildkit": true
  }
}
```
I restarted docker desktop after enabling experimental mode.

  - Windows Version: 21H2
  - Docker Desktop Version: v4.12.0
  - WSL2 or Hyper-V backend?  ESL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[2022-12-02T10:22:21.457561400Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0023: is the Containers Windows Feature enabled?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running



Not all of the backend processes are running.
```

### Steps to reproduce the behavior

  1. Create a docker-compose.yml file in a directory and paste in the contents of the docker-compose.yml specified above
  2. In a terminal run `docker compose up` from the directory that contains the docker-compose.yml file, this should produce the console output described in 'Actual behaviour'
