### ISSUE TITLE
service "cvat" has neither an image nor a build context specified: invalid compose project

### ISSUE THREAD

**Issue by cvat-si** [docker/for-win#13121]
My requirement is to access CVAT from another computer through the internet and for that I have created "docker-compose.override.yml" file and saved. But when I execute any command below message is showing in git bash.

"service "cvat" has neither an image nor a build context specified: invalid compose project"

  - Windows Version: Windows 10 (22H2)
  - Docker Desktop Version: 4.15.0
  - WSL2 
  
The created file is attached herewith for more clarification. 
Since I'm new to docker please help on this.

[docker-compose.override.yml.txt](https://github.com/docker/for-win/files/10204782/docker-compose.override.yml.txt)

**Comment by nicks** [comment]
sorry to here you're having trouble!

here's your service yaml:

```
version: '3.3'
services:
 cvat:
   ports:
     - "8080:8080"
   environment:
     ALLOWED_HOSTS: '*'
     UI_SCHEME: http
     UI_HOST: <my external IP>
     UI_PORT: 8080
 ```

here's the compose documentation: https://docs.docker.com/compose/compose-file/#image

It reads:

```
image MAY be omitted from a Compose file as long as a build section is declared. Compose implementations without build support MUST fail when image is missing from the Compose file.
```

Your YAML doesn't have an image field or a build field, so it's invalid.
