### ISSUE TITLE
[BUG] docker-compose up -d on file server causes "Error response from daemon: (EXTRA string=is not a valid Windows path)".

### ISSUE THREAD

**Issue by nakamoto-upost** [docker/for-win#13172]
### Description

I used `docker-compose up -d` in docker-compose.yml on file server(\\xxxxxx\UserData$\zzzzzz\My Documents\docker_test).
```
\\xxxxxx\UserData$\zzzzzz\My Documents\docker_test
└.fs_test
   ├── Dockerfile
   └── docker-compose.yml
```
.fs_test\Dockerfile
```
FROM node:18-bullseye

WORKDIR /var/www/html

RUN apt update && \
    npm install -g npm 

EXPOSE 3000
ENV HOST 0.0.0.0
```
.fs_test\docker-compose.yml
```
version: '3.2'
services:
  fs_test:
    container_name: fs_test
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ../
        target: /var/www/html
    tty: true
```
But, it causes this error.
```
Error response from daemon: \\xxxxxx\UserData$\zzzzzz\My Documents\docker_test%!(EXTRA string=is not a valid Windows path)
```
Why I can't do this?

### Steps To Reproduce

1. make docker-compose.yml on file server and set volume with relative path.
2. docker-compose up -d

### Compose Version

```Text
Docker Compose version v2.13.0
```

### Docker Environment

```Text
Docker version 20.10.21, build baeda1f
```
