### ISSUE TITLE
docker swarm network error.

### ISSUE THREAD

**Issue by yaoqiangpersonal** [docker/for-win#13192]
version: 4.16.2
demo.yml
```yml

version: "3.7"

services:
  nginx:
    image: nginx:1.23.3
    hostname: nginx
    ports:
      - target: 80
        published: 80
```

when I use `docker-compose -f demo.yml up`. it works well. but when I use `docker stack deploy -c demo.yml demo`, `http://localhost` shows the error page.
