### ISSUE TITLE
Docker does not start on the first try

### ISSUE THREAD

**Issue by fabiogusmao** [docker/for-win#1330]
I started experiencing this after #989 was solved. I've been experiencing this every day so I  think I have enough information to report it now. 

*Background:* I use a MYSQL container every day so that I develop in an environment similar to what we have in production. I have to start Docker many times as described below before I can connect to the database. I tried to destroy the container  a few times during my tests but makes no difference. Restarting Docker 2 times after startup is the key.

I am reporting these two issues together because they may be connected but maybe they're two separate things.

### Expected behavior
Docker containers start nicely after computer boots / reboots
### Actual behavior

We get an error message when starting Docker Compose the first time after the computer starts. The message  disappers after we reset docker the first time.

![image](https://user-images.githubusercontent.com/2974851/32894753-e41a7950-cac4-11e7-8cc0-5d3bf85e3d04.png)

After resetting Docker MySQL starts but we still cannot connect:

![image](https://user-images.githubusercontent.com/2974851/32895318-c69d635e-cac6-11e7-9082-59058d8b31ba.png)

![image](https://user-images.githubusercontent.com/2974851/32895370-f636d85c-cac6-11e7-8d5d-d037b1adc978.png)

### Information

Diagnostic ID 1 FD25E850346C/2017-11-16_11-50-42
Diagnostic ID 2 FD25E850346C/2017-11-16_12-09-54

#### System Information
Windows 10 Pro x64 1703 15063.726
Intel Core i5 6500 CPU 16GB RAM

#### Docker Information
Version: 17.11.0-ce-rc3-win38 (14052)
Channel: edge

Docker Compose file:

```
version: '2'
services:
    db:
        image: mysql:5.7.11
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: anythinggoes
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 3308:3306        
```

### Steps to reproduce the behavior

1. Start computer
2. Check in Docker Settings if startup was Ok (green dot on lower left corner)
3. Go to project's folder
4. Run `docker-compose up`
5. View error message as in screenshot 1
6. Uploaded *Diagnostic 1*
7. Reset Docker in Docker Settings
8. Run `docker-compose up` again
9. Get screenshot 2 but cannot connect yet
10. Upload *Diagnostic 2*
11. Reset Docker once more
12. Can connect to MySQL
