### ISSUE TITLE
Cannot bind a windows folder 

### ISSUE THREAD

**Issue by zxln007** [docker/for-win#13394]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D806F768-D4A7-4A3E-8F4F-FB1DD8C571FD/20230413070043

### Actual behavior
i mount 5 folder in a container ,  4 of them  mounted successfully ,

 but only one cannot mount . not always , about 10 percent .

a part of docker-compose.yml

```yaml
    container_name: aaa
    image: aaa
    restart: always
    privileged: true
    ports:
      - "127.0.0.1:2001:2001"
    volumes:
       - /run/desktop/mnt/host/c/aospace/backup:/backup
       - /run/desktop/mnt/host/c/aospace/home/data:/data
       - /run/desktop/mnt/host/c/aospace/opt/image:/headimage
       - /run/desktop/mnt/host/c/aospace/etc/bp/meta/shared:/shared
       - /run/desktop/mnt/host/c/aospace/home/data/dav/cards/collections/collection-root/root:/addressbook
```
### Expected behavior

mount all folder successfully

### Information

  - Windows Version: Windows 10 Pro  internal version： 19045.2846
  - Docker Desktop Version: 4.18.0
  - WSL2 or Hyper-V backend?   WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by milas** [comment]
From the diag, there are some cases where the mount is failing:
```
[2023-04-11T11:51:26.614977600Z][dockerd][I] time="2023-04-11T11:51:26.614278300Z" level=error msg="Handler for POST /v1.41/containers/257ba5c143acc5821718fb23728addf0bc4dc8775fea0bef3e4fc5bf58556575/start returned error: error while creating mount source path '/run/desktop/mnt/host/e/backup': mkdir /run/desktop/mnt/host/e: file exists"
```

That's on `E:\` rather than `C:\` as shown in your example -- is this different? Is `E:\` a removable drive by chance?

One thing to note is that the 2x bind mount syntaxes vary in behavior in Docker:
 * short form (that you're using), e.g. `-v /foo:/bar` will create `/foo` on the host if it does not exist
 * long form will NOT create host path
 ```yaml
 - type: bind
   source: /foo
   target: /bar
 ```

If you convert your volumes into the long syntax in Compose, does the issue go away? That will help us determine if there is an underlying race issue in Compose/Engine.
