### ISSUE TITLE
Networking severely degraded on versions > 4.12

### ISSUE THREAD

**Issue by rg9400** [docker/for-win#13393]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7E746511-651C-4A74-8C84-91189E8962C1/20230406225924

### Actual behavior

I created a very detailed ticket for paid support, but they told me to just come and create it here. 

I am facing numerous degradations in networking performance from any version later than 4.12.0. I will list out the symptoms below, but after updating multiple times to each version after 4.12 as well as trying to update to 4.18 at least 5 times, these issues always get introduced. As soon as I revert to 4.12.0, they instantly go away. Something happened in 4.13 (maybe related to the proxy changes) which has resulted in **significant** network degradation.

1. My download speed on my Windows host is around 1gbps, usually hitting 900mbps. Because of Docker/WSL, I was only ever getting 200mbps in Docker containers on any version up to 4.12.0. On versions greater than 4.12, speedtest drops to an average of 40mbps which is only 20% of the original throughput.

2. I run Uptime-Kuma in my Docker Compose stack. I have it checking multiple container health statuses by pinging the container at a specific port. I use Docker DNS resolution, so I set the container name as the host and the relevant port in the monitors. I have 60 monitors for each container. This works perfectly in 4.12. As soon as I update, instantly there are intermittent Connection Refused hits on the monitors. To be clear, this does not happen for every single ping, but it starts happening enough that the monitors keep flipping between healthy/unhealthy all of a sudden.

3. I have a CIFS volume for a shared Windows folder in my compose which is attached to multiple containers. I notice multiple containers suddenly see the volume disappear. It reappears, but again, like point 2, it starts happening intermittently.

All of these are symptoms of what is probably dropped packets in the networking, and I am sure there are significant other issues occurring. I noticed a lot of other issues that might be related. For example, this reply seems to highlight the change happening on 4.13+ - https://github.com/docker/for-win/issues/13092#issuecomment-1479458621

These are pretty significant downgrades in network performance which is basically making it impossible for me to use anything higher than 4.12 in production. I assumed these would have been fixed now after half a year, but seems they may not even be on the team's radar? 
 
### Expected behavior

Networking should work like in 4.12. Maybe there is demand for the proxy changes, but this level of network degradation is not an acceptable tradeoff for it. 

### Information

  - Windows Version: Windows 11 Pro 22H2 22621.1555
  - Docker Desktop Version: 4.18.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Bare metal Windows 11

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

It seems the diagnostics might be broken in 4.18.0. I noticed someone else having all the nonsense about virtualization and stuff not being enabled here https://github.com/docker/for-win/issues/13388 after running the self-diagnostics, which is the exact same issues my self-diagnostics are giving. These are clearly not correct as they do not occur on 4.12.0, and I wouldn't be able to run a compose stack with 60 containers on production with those basic steps missing. Apparently this is creating too much noise for them to dig into what is happening and makes this command unhelpful

### Steps to reproduce the behavior

**First Issue**

1. Run a Speedtest Container on 4.12 such as below. Ideally overall download speed is high enough to notice reductions
```yaml 
speedtest:
    image: henrywhitaker3/speedtest-tracker:dev
    container_name: speedtest
    environment:
      - OOKLA_EULA_GDPR=true
    ports:
      - 8765:80
    restart: unless-stopped
```
2. Collect and calcualte average speedtest performance
3. Upgrade to 4.18
4. Collect and calculate average speedtest performance

**Second Issue**

1. Run Uptime-Kuma on 4.12 such as below. Ideally, have a handful (I have 60, not sure if you can notice with fewer) containers/monitors to check
```yaml
  uptime-kuma:
    image: louislam/uptime-kuma:beta
    container_name: uptime-kuma
    volumes:
      - ~/docker/configs/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
```
2. Create a handful of monitors to check containers in the compose. Use container name for host and run the port monitoring
3. Verify that none of the monitors are failing randomly in the Docker Logs for the container
4. Upgrade to 4.18
5. Monitor Docker Logs and verify if monitors start failing with Connection Refused errors

**Third Issue**

1. Create a CIFS volume in your compose as below on 4.12
```yaml
  backups:
    driver_opts:
      type: cifs
      o: username=${HOSTUSER},password=${HOSTPASS},iocharset=utf8,serverino,rw,uid=${PUID},gid=${PGID},file_mode=0777,dir_mode=0777
      device: \\${HOSTIP}\backups
```
2. Mount this volume into a container that just checks the existence of the volume every few seconds (I don't have any easy to use examples for this off hand, but should be very easy to create)
3. Verify the existence is persistent
4. Upgrade to 4.18
5. Monitor the logs in the container and notice intermittent disconnections/disappearances of the volume
