### ISSUE TITLE
Invalid bind mount source, must be an absolute path (Docker Swarm)

### ISSUE THREAD

**Issue by kunalbhatia87** [docker/for-win#1341]
When running a Docker Swarm cluster on a docker-machine created Hyper VM, using Windows 10 as the Docker client OS, I have issues when using bind mounts in a docker-compose.yml file that is being consumed by 
`docker stack deploy -c docker-compose.yml <service_name>`

```Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
λ docker-machine ls
NAME      ACTIVE   DRIVER   STATE     URL                      SWARM   DOCKER        ERRORS
manager   *        hyperv   Running   tcp://<ip>:2376           v17.10.0-ce
worker1   -        hyperv   Running   tcp://<ip>:2376           v17.10.0-ce
worker2   -        hyperv   Running   tcp://<ip>:2376           v17.10.0-ce
```
> "invalid bind mount source, must be an absolute path: C:\projects\docker-tests\swarm-logging\logstash\logstash.conf"

```yaml
version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker1

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.4
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - '80:5601'
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1

volumes:
  esdata:
    driver: local
```
