### ISSUE TITLE
Using a proxy while building images

### ISSUE THREAD

**Issue by SebastianPfliegel** [docker/for-win#1380]
### Expected behavior
I need to use a proxy and I'm able to set it in the proxies tab in the Docker Settings. I expect Docker to use the set proxy for all kind of transactions: pulling/pushing images, in the final container and while building the actual image.

### Actual behavior
Unfortunately this only applies to pulling/pushing images and the container. While building no proxy is set and therefore functions like apt-get and curl fail.

### Information

  - Diagnostic ID: 80162FE0-1E80-4CAD-9437-195610F0B460/2017-12-04_15-43-59
  - Windows 10 Enterprise

### Steps to reproduce the behavior

  1. set a proxy in the settings GUI and apply
  2. build a Dockerfile using RUN apt-get update
  3. build fails due to connection refused

### Workaround

As a workaround I'm able to set the build args myself. Here's a sample compose-file:

```yaml
version: '2'
services:
  my_service:
    image: myservice:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://myproxy.com:8080
        - https_proxy=http://myproxy.com:8080
        - HTTP_PROXY=http://myproxy.com:8080
        - HTTPS_PROXY=http://myproxy.com:8080
```
