### ISSUE TITLE
Issue with Docker Build: Vue3 Project Not Building into Volume

### ISSUE THREAD

**Issue by ProDevJune** [docker/for-win#14239]
### Description

I am currently working on a project called test-dev-note and I am experiencing an issue with my Docker setup. The test-dev-vue service is responsible for building the Vue3 project, and the test-dev-nginx service is supposed to serve the built files as a web server. However, the built files are not present in the expected volume.

### Reproduce

1. Clone the repository `test-dev-note` from GitHub: <a href="https://github.com/ProDevJune/test-dev-note.git" target="_blank">ProDevJune/test-dev-note</a>
   - `test-dev-note/`
     - `docker/`
       - `docker-compose.yml`
       - `default.conf.template`
       - `.env.staging`
     - `test-dev-vue/`
       - `Dockerfile`
       - `.env.development`
       - `.env.staging`
       - Other Vue project files
2. Ensure the following files are correctly configured:
   - `docker-compose.yml`
### docker-compose.yml

```yaml
services:
  test-dev-vue:
    build:
      context: ../test-dev-vue
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: test-dev-vue
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - vue_build:/app/dist
    tty: true

  test-dev-nginx:
    image: nginx:alpine
    container_name: test-dev-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - vue_build:/usr/share/nginx/html:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - test-dev-vue

volumes:
  vue_build:

networks:
  default:
    name: test-dev-net
```

   - `test-dev-vue/Dockerfile`
### Dockerfile

```Dockerfile
# 빌드 단계
FROM node:18 AS build-stage
WORKDIR /app
COPY package.json yarn.lock ./
RUN if ! command -v yarn >/dev/null 2>&1; then npm install -g yarn; fi
RUN yarn install
COPY . .

# 환경 변수 설정
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

RUN echo "Building with VITE_API_URL=${VITE_API_URL}"
RUN yarn build-only
RUN ls -la /app/dist

# 결과물만 포함하는 경량 이미지
FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
```

   - `.env.staging` files in both `docker` and `test-dev-vue` directories
3. Run the Docker Compose setup in staging mode:
   ```bash
   docker-compose -f docker/docker-compose.yml --env-file docker/.env.staging up -d --build
4. Check the contents of the /app/dist directory in the test-dev-vue container:
   ```bash
   docker exec -it test-dev-vue /bin/sh
   ls -la /app/dist


### docker exec result

```bash
/ # ls -la /app/dist
total 16
drwxr-xr-x    2 root     root          4096 Aug  5 13:00 .
drwxr-xr-x    3 root     root          4096 Aug  5 13:00 ..
-rw-r--r--    1 root     root           497 May 29 17:56 50x.html
-rw-r--r--    1 root     root           615 May 29 17:56 index.html
/ #
```
The above result shows the current incorrect output where the expected Vue build files are missing.

### Expected behavior

```markdown
The `test-dev-vue` service should build the Vue3 project, and the built files should be available in the `/app/dist` directory, which is mapped to the `vue_build` volume. The `test-dev-nginx` service should then serve these files as a web server.

When the build is successful, the `/app/dist` directory should contain the following files:
The `dist` directory should contain:
- `assets/` folder
- `favicon.ico`
- `index.html`
```

### docker version

```bash
Client:
 Version:           4.33.1
 Vue version:       Vue3
 Git commit:        0045f0d6d33dcd967db1e7246324109b1c5a66c7
 OS/Arch:           Windows11/amd64
 Context:           default
```

### docker info

```bash
Client:
 Context:           default
 Debug Mode:        false
 Plugins:
  buildx: Docker Buildx (Docker Inc., 0.8.2)
  compose: Docker Compose (Docker Inc., 2.6.0)
Server:
 OS/Arch:           linux/amd64
```

### Diagnostics ID

74BBA754-EBA8-4226-9CE5-0445248AA8B5/20240805134745

### Additional Info

I have verified that the environment variables for staging mode are correctly set in the respective `.env.staging` files. The build step includes a command to list the contents of `/app/dist`, which shows the files `50x.html` and `index.html` instead of the Vue build output.

Could you please provide guidance on what might be causing this issue and how I can ensure the Vue3 project is built correctly into the `vue_build` volume and served by the `test-dev-nginx` service?

Thank you for your assistance.

Best regards,  
ProDevJune
