### ISSUE TITLE
Cannot get Xdebug working with LEMP Stack and PHPStorm

### ISSUE THREAD

**Issue by kickthemooon** [docker/for-win#1424]
### Expected behavior
Xdebug connects to PHPStorm which is listening on a port (e.g. 9000)

### Actual behavior
xdebug.log

```
I: Connecting to configured address/port: 10.0.75.1:9001.
E: Time-out connecting to client. :-(
```
or
```
I: Connecting to configured address/port: 10.0.75.1:9023.
W: Creating socket for '10.0.75.1:9023', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(
```
### Information

I hope this is not too off-topic but I am trying to get xdebug working with my docker local environment and I am not having much luck.

This is docker-compose.yml:

```
version: "2.1"

services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - "./public:/var/www/html/public:ro"
            - "./default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php

    php:
        image: kickthemooon/php-laravel
        expose:
            - 9000
        volumes:
            - ".:/var/www/html"
            - "./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

volumes:
    data:
```

This is my dockerfile:

```
FROM php:7.1-fpm

RUN apt-get update && apt-get install -y \
    && docker-php-ext-install pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug-2.5.0 \
    && docker-php-ext-enable xdebug
```

This is my xdebug.ini:

```
zend_extension = "/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so"
xdebug.remote_enable = 1
xdebug.remote_autostart = 0
xdebug.remote_connect_back = 0
xdebug.remote_host = 10.0.75.1
xdebug.remote_port = 9001
xdebug.remote_log=/var/www/html/xdebug.log
```

Xdebug phpinfo();

![xdebug_phpinfo_1](https://i.imgur.com/dd14QNj.jpg)

![xdebug_phpinfo_2](https://i.imgur.com/TjWtgWg.jpg)

My PHPStorm settings:

![phpstorm_debug_configuration](https://i.imgur.com/8AICTCN.jpg)
-
![phpstorm_remote_debug_configuration](https://i.imgur.com/kQMYXDb.jpg)
-
![dbgp_configuration](https://i.imgur.com/2GDA69E.jpg)
-
![phpstorm_php_servers_configuration](https://i.imgur.com/PAPHOy3.jpg)

I would appreciate any hints and tips. Thanks.
