### ISSUE TITLE
Latest update prevents connection over localhost, instead works over my internal IP

### ISSUE THREAD

**Issue by ChaosCA** [docker/for-win#1428]
### Expected behavior
The docker container should be bound to localhost on the IP I choose to expose

### Actual behavior
Docker doesn't bind to localhost(127.0.0.1)

### Information

`netstat -a -b`
```
 [vpnkit.exe]
  TCP    0.0.0.0:3307           PC:0          LISTENING
 [vpnkit.exe]
  TCP    0.0.0.0:3308           PC:0          LISTENING
```

I can see Docker binds to the 0.0.0.0 address here. Prior to the update it bound to 127.0.0.1, now it can't be accessed over localhost for some reason. I can only connect to the container using my local IP, which in this case is `192.168.0.24`

### Steps to reproduce the behavior

Running this docker file with `docker-compose up`
```
version: '3.3'

services:
    core-db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - "3307:3306"
```
