### ISSUE TITLE
docker-compose pull error ERROR: cannot download image with operating system "linux" when requesting "windows"

### ISSUE THREAD

**Issue by awidjaja** [docker/for-win#1464]
### Expected behavior

> All images in the docker-compose.yml file are pulled.

### Actual behavior

> None of the images in the docker-compose.yml file were pulled.
`ERROR: cannot download image with operating system "linux" when requesting "windows"`
Note: individual docker pull works.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

> F2099E05-3DBA-47DC-974B-B993D6042D1E/2017-12-27_01-37-52

  - a reproducible case if this is a bug, Dockerfiles FTW

> refer to the docker-compose.yml content below.

  - page URL if this is a docs issue or the name of a man page

> N/A

  - host distribution and version (Windows version, build number, etc)

> Windows 10 Pro 64-bit on SSD, 4GB RAM. 
Docker for Windows with LCOW.

### Steps to reproduce the behavior

  1. docker-compose -f docker-compose.yml pull

docker-compose.yml
```yml
version: '3'

networks:
  votenet:
    driver: overlay

services:

  assessor:
    image: bootcamps/vote-auditor
    networks:
      votenet:
        aliases:
          - auditor

  database:
    image: mongo:3.4
    networks:
      votenet:
        aliases:
          - database
    ports:
      - "27017:27017"
    volumes:
    - /home/docker/data/db:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
  queue:
    image: redis:3.2
    networks:
      votenet:
        aliases:
          - queue
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: '[ $$(redis-cli ping) = "PONG" ] || exit 1 ]'
      timeout: 2s
      interval: 5s
      retries: 5

  worker:
    image: bootcamps/vote-worker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - votenet
    deploy:
      placement:
        constraints: [node.role == worker]

  vote:
    image: bootcamps/vote
    networks:
      votenet:
        aliases:
          - vote
    ports:
      - "5000:3000"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      votenet:
        aliases:
          - visualizer
```
