### ISSUE TITLE
docker stack deploy created services but no container is created

### ISSUE THREAD

**Issue by awidjaja** [docker/for-win#1465]
### Expected behavior

> docker stack deploy will create containers to be run on swarm node

### Actual behavior

> services were deployed but no container is run/created. 
Message: `No suitable node(...`

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

> F2099E05-3DBA-47DC-974B-B993D6042D1E/2017-12-27_02-13-24

  - a reproducible case if this is a bug, Dockerfiles FTW

> refer to docker-compose.yml file below

  - page URL if this is a docs issue or the name of a man page

> N/A

  - host distribution and version (Windows version, build number, etc)

> Windows 10 Pro 64-bit on SSD, 4GB RAM. 
Docker for Windows with LCOW.

### Steps to reproduce the behavior

  1. docker stack deploy -c docker-compose.yml vote

docker-compose.yml
```yml
version: '3'

networks:
  votenet:
    driver: overlay

services:

  assessor:
    image: bootcamps/vote-auditor
    networks:
      votenet:
        aliases:
          - auditor

  database:
    image: mongo:3.4
    networks:
      votenet:
        aliases:
          - database
    ports:
      - "27017:27017"
    volumes:
    - /home/docker/data/db:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
  queue:
    image: redis:3.2
    networks:
      votenet:
        aliases:
          - queue
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: '[ $$(redis-cli ping) = "PONG" ] || exit 1 ]'
      timeout: 2s
      interval: 5s
      retries: 5

  worker:
    image: bootcamps/vote-worker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - votenet
    deploy:
      placement:
        constraints: [node.role == worker]

  vote:
    image: bootcamps/vote
    networks:
      votenet:
        aliases:
          - vote
    ports:
      - "5000:3000"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      votenet:
        aliases:
          - visualizer
```

docker info

``` yml
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.0-ce-rc4
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: active
 NodeID: ovw7j8ickyruwu8ur9knnijnv
 Is Manager: true
 ClusterID: k0k3ovqankuj9nd73em1n85e7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.88.81
 Manager Addresses:
  192.168.88.81:2377
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.881GiB
Name: myPortege
ID: OLYP:46KC:XVBD:IIL6:NIIQ:M43B:UMNW:OADA:AOZV:BZSI:GYB2:KFXZ
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 140
 System Time: 2017-12-27T01:07:57.2843034+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
