### ISSUE TITLE
(LCOW) Linux-only containers docker-compose getting: 'cannot download image with operating system "linux" when requesting "windows"'

### ISSUE THREAD

**Issue by zeecodes** [docker/for-win#1472]
### Expected behavior
Docker Edge running with 'Linux containers' feature enabled should pull all images from docker-compose yml as all images are Linux based.

### Actual behavior
PS C:\DockerProjects\myproject> docker-compose up -d
Pulling db (tutum/mysql:latest)...
latest: Pulling from tutum/mysql
ERROR: cannot download image with operating system "linux" when requesting "windows"

### Information
Virtualisation: Proxmox 5 VM running qemu/KVM
Operating System: Windows 10 Pro N (Version 1709; OS Build 16299.125)

Docker information:
Version 17.12.0-ce-rc4-win44 (14896)
Channel: edge f23de3e

Machine: 0.13.0
Compose: 1.18.0

Docker's Diagnostic ID: 8B85E64E-6E12-43FB-B240-432FFBB3F7EC/2017-12-31_03-46-42

Issue looks the same as; https://github.com/docker/for-win/issues/1464

### Steps to reproduce the behavior

  1.  docker-compose.yml with contents of:
```
version: '3.0'
services:
 web:
  build: .
  links:
    - db
  volumes:
    - ./public_html:/var/www/project
  ports:
    - "8080:80"
    - "3001:3001"
    - "3000:3000"
 db:
  image: tutum/mysql
  environment:
    MYSQL_USER: root
    MYSQL_PASS: password
  volumes:
    - ./Mysql:/var/lib/mysql
    - ./MysqlHome:/root
  ports:
    - "3306:3306"
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 81:80
  links:
      - db
  environment:
    PMA_HOST: db
```

  2. Run 'docker-compose up -d' in the source directory.
