### ISSUE TITLE
Connection/Network Problems in latest Edge version

### ISSUE THREAD

**Issue by richraid21** [docker/for-win#1571]
### Expected behavior

Create postgres container and connect to it with `psql`. 

### Actual behavior

`psql` is unable to connect. PowerShell confirms that the port is listening though. I really have no idea what the problem actually is. This may be an issue with how `psql` works. 

![image](https://user-images.githubusercontent.com/8130585/35060736-5142248a-fb8d-11e7-9e07-4e607e59b362.png)

### Information

I was unable to connect to the Postgres instance in my container with both `psql` and a variety of other tools. Once I changed the release channel to "stable" and reinstalled, the problem went away. 

### Steps to reproduce the behavior

1. Install the latest edge version on Windows 10 15063.850 

2. 
```
version: '2'

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: rich
    ports:
      - 5432:5432
``` 

3. `docker-compose up -d`

4. `psql -U postgres` errors out

![image](https://user-images.githubusercontent.com/8130585/35060776-6239f7ea-fb8d-11e7-8566-0d3d6d9b660d.png)

5. Downgrade from edge to stable, restart docker and run the same `psql` command and it will work.
