### ISSUE TITLE
docker swarm isn't reusing named volumes, instead creating new ones

### ISSUE THREAD

**Issue by mawl** [docker/for-win#1605]
### Expected behavior
When deploying services with `docker stack deploy` I would assume that named volumes will be reused on the node.

### Actual behavior
Instead docker creates a new volume when Container is updated or restarted.

### Information
* Microsoft Windows Server 2016 [Version 10.0.14393]
* Docker version 17.06.2-ee-5, build 508bb92

prod.yml
```
version: '3.2'
services:
  mongo:
    image: mongo:3.6.0-windowsservercore-ltsc2016
    deploy:
      placement:
        constraints:
          - node.hostname == appsrv02
      endpoint_mode: dnsrr             
    ports:
    - target: 27017
      published: 27017
      protocol: tcp
      mode: host    
    volumes:
    - mongo_data:C:/data/db
    - mongo_config:C:/data/configdb
    
  app:
    image: dockerhub.mycompany.de/buildmanagement/app:latest
    deploy:
      placement:
        constraints:
        - node.hostname == appsrv02
      endpoint_mode: dnsrr
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    environment:
    - DB_HOST=mongodb://mongo:27017
    - CALLBACK_WEBSERVICE_URL=http://app.mycompany.de/api/callbacks
    volumes:
    - git-repositories:C:/git-repositories
    secrets:
    - id_rsa
    - known_hosts   

volumes:
  mongo_data:
  mongo_config:
  git-repositories:

networks:
  default:
    driver: overlay
 
secrets:
   id_rsa:
     external: true
   known_hosts:
     external: true     
```
### Steps to reproduce the behavior

1. Deploy a Service into docker swarm
2. Service gets restarted because of an error / update service
3. a new volume is generated and mounted - in Addition to the old named volume - but the destination does only contain files from the last mountpoint.
```
 "Mounts": [
            {
                "Type": "volume",
                "Name": "mg_git-repositories",
                "Source": "C:\\ProgramData\\docker\\volumes\\mg_git-repositories\\_data",
                "Destination": "C:\\git-repositories",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "99194d59bbec381b9308acd3189f662d4b01ccda097b7702c3ea3175c1e5ce54",
                "Source": "C:\\ProgramData\\docker\\volumes\\99194d59bbec381b9308acd3189f662d4b01ccda097b7702c3ea3175c1e5ce54\\_data",
                "Destination": "c:\\git-repositories",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
```
