### ISSUE TITLE
Trouble installing applications in Kubernetes

### ISSUE THREAD

**Issue by paulkling** [docker/for-win#1651]
### Expected behavior
When installing dashboard:
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml
`
First need to run 
`kubectl proxy` 
But it too throws 
`http: proxy error: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it`

Dashboard eventually available at: http://localhost:8001/ui

When I do a docker ps with Kubernetes (show system containers checked) no containers have exposed ports.

### Actual behavior
`Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.`

### Information
  - Diagnostic ID: 8DA4B2BB-834D-493B-B200-BB5F5004A910/2018-02-02_14-54-13
  - Windows 10 Pro - version 1607 (OS Build 14393.2007)
  - Docker CE 18.02.0-ce-rc2-win51 (15631) edge channel - 4713a50

### Steps to reproduce the behavior
1. I am following Scott Hanselman blog - https://www.hanselman.com/blog/HowToSetUpKubernetesOnWindows10WithDockerForWindowsAndRunASPNETCore.aspx 
- Click Enable Kubernetes
- Wait for green kuberetes is running light
- In powershell run
`C:\> kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml`

**Comment by GuillaumeLebeau** [comment]
I have the same error while running this in PowerShell:
``` bash
> kubectl get nodes
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by pgayvallet** [comment]
The error make me think `kubectl` doesnt even see the `~/.kube/config` file.

Could you copy and paste the result of `kubectl config view`, `echo $HOME`, `ls ~/.kube` in terminal you used to get these errors ?

**Comment by GuillaumeLebeau** [comment]
@pgayvallet, please find the result of all these commands:
```bash
C:\> kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```
```
C:\> echo $HOME
C:\Users\guillaume.lebeau
```
```
C:\> ls ~/.kube
    Directory:  C:\

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a----           2/5/18     11:22     2.67KB config
```

I check the `~/.kube/config` file and it contains those settings:
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6445
  name: docker-for-desktop-cluster
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
current-context: docker-for-desktop
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data: #################
    client-key-data: ##################
```

**Comment by paulkling** [comment]
```
PS C:\> kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```



```
PS C:\> echo $HOME
C:\Users\paul.kling
```


```
PS C:\> ls ~/.kube
    Directory: C:\Users\paul.kling\.kube
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         2/2/2018   2:36 PM           2737 config
```
~/.kube/config
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6445
  name: docker-for-desktop-cluster
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
current-context: docker-for-desktop
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJ
    client-key-data: LS0tLS1CRUdJTiBSU0
```

Our corp policy has my HOMEDRIVE set to H: (network drive)  and HOMEPATH set to \ 
I have noticed this caused trouble for linux type applications in the past.
