### ISSUE TITLE
Docker gets stuck when kafka is used

### ISSUE THREAD

**Issue by CezCz** [docker/for-win#1757]
### Expected behavior
Docker to run seamlessly
### Actual behavior
Docker simply gets stuck (logs stops, cannot do any docker related command), there is no answer coming from docker. Restart is needed, it helps until the next stop.
### Information
We are running not so big kafka, zookeeper, redis, spring boot cloud application.
Problem is only reproducible when kafka zookeeper and redis are running.

What we are trying to do is to validate a csv file in two microservices, they are communicating through kafka. Csv is let's say around 10k records, sent in batches then validation results are cached in redis per each record. This very easily stops any responsivity, however it sometimes breaks without any help.

Interestingly, it works without a problem when only kafka, zookeper and redis are in containers and microservices are run with mvn spring-boot plugin.

Kafka and redis docker-compose part:
```
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
```
Then one of the microservices:
```
    validation:
    image: edison/validation
    ports:
      - "31419:31419"
    environment:
      PROFILE: "default"
      SERVER_PORT: "31419"
      DISCOVERY_URI: "http://discovery:8761/eureka/"
      DISCOVERY_PORT: "8761"
      CONFIGSERVER_URI: "http://config:8888"
      CONFIGSERVER_PORT: "8888"
      REDIS_PORT: "6379"
      REDIS_URL: "redis"
      KAFKASERVER_PORT: "9092"
      KAFKASERVER_URI: "kafka"
      ZKSERVER_URI: "zookeeper"
```

Diagnostic ID: FE45C4F3-3F98-497F-97B2-F818EA68F3C3/2018-02-27_14-53-19

I'd be glad if you'd investigated the cause.
Please let me know if you need anymore data from me.
