### ISSUE TITLE
Kubernetes for win: Cannot dynamically create PersistentVolume

### ISSUE THREAD

**Issue by savpek** [docker/for-win#1758]
### Expected behavior
When kubernetes dynamically allocates hostpaths they should work.

### Actual behavior
They don't work, consumer pods hang on invalid mode error.

Releated issue (however closed) https://github.com/docker/for-win/issues/1669, underlaying issue is same and i tested workarounds. I can manually create PersistentVolumes with hostpath /tmp/foobar and it works. 

I don't have host machine (win10) disks shared to VM, i think atleast in this case volumes should be native unix but it still tries to point path on windows.

Created pv
```
Name:            pvc-cc822733-1c59-11e8-bd24-00155d67c71c
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by=docker.io/hostpath
StorageClass:    hostpath
Status:          Bound
Claim:           satel-monitoring-master/grafana-claim0
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        5Gi
Message:
Source:
    Type:          HostPath (bare host directory volume)
    Path:          C:\Users\psa/.docker/Volumes/grafana-claim0/pvc-cc822733-1c59-11e8-bd24-00155d67c71c
    HostPathType:
Events:            <none>
```

### Information
Somewhere i read that this should be fixed (?) in 18.03 version, however just updated to that version and issue still occurs.

Docker version:
```
Version 18.03.0-ce-rc1-win54 (16164)
Channel: edge
e10c722
```

### Steps to reproduce the behavior
Follow releated issue https://github.com/docker/for-win/issues/1669

As workaround i currently create persistentVolumes from yaml files, however this differs between local and remote environments, which is bad since i'd like to keep configurations as much identical as possible.

**Comment by MitchellNZ** [comment]
+1. I am also experiencing this issue.

However, I am pretty new to docker & Kubernetes..
@savpek Could you please explain your work around in a bit more detail so I can get up and testing in the mean time?

If I understand correctly, you are explicitly creating a PV that is linked to the PVC instead of letting it dynamically create one.
Could you please share an example of how I can link these two?

Would be much appreciated, thanks!

**Comment by savpek** [comment]
This is ugly but i just create bunch of PV:s with enough space before i apply rest 😆 

```
# This is workaround for https://github.com/docker/for-win/issues/1669#event-1492987545
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-volume1
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/monitoring-volume1/"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-volume2
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/monitoring-volume2/"

---

... ... ...

```
