### ISSUE TITLE
Windows container stops being responsive from both networking and the Docker API 

### ISSUE THREAD

**Issue by KevM** [docker/for-win#1774]
### Expected behavior

After a period of time it is no longer possible to communicate with the docker container. This seems odd. I understand that the app in the container may be running into problems but Docker itself seems to fall down with no indication as to why. 

### Actual behavior

Docker container is up yet unresponsive.

### Information

We cannot do the following when this happens:

* docker inspect <containerid>
* ctrl+c on the result of a `docker-compose up` are non-responsive.
* docker-compose down

The only way to get Docker working again is to **Restart Docker...**

#### Requested Details

  - Diagnostic ID from "Diagnose & Feedback" : D328A056-EE5B-4784-AE5E-D0CB52167DE4/2018-03-01_15-51-55

  - Our docker compose:
```yaml
version: "3.1"
services: 
  mssql:
    image: microsoft/mssql-server-windows-developer
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
      attach_dbs: "[{'dbName':'dev','dbFiles':['C:\\\\data\\\\dev.mdf','C:\\\\data\\\\dev.ldf']}]"
    ports: 
      - "1433:1433" 
    # healthcheck:
    #   test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password123!", "-Q", "select 1" ]
    #   interval: 30s
    #   retries: 2
    volumes: 
      - c:\temp:c:\data
```
  - host distribution and version (Windows version, build number, etc)

```bash
> uname -a
windows32 kmiller-lt 2.6.2 9200 i686-pc Intel unknown MinGW
```

Windows Version `1709 (OS Build 16299.248)`

```bash
> docker version
docker version
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

### Steps to reproduce the behavior

  1. `docker-compose up`
  2. Leave the docker container up for awhile. 
  3. Connectivity to the exposed port is lost and docker commands regarding the container no longer work.
