### ISSUE TITLE
Kubernetes External-IP is none

### ISSUE THREAD

**Issue by angegar** [docker/for-win#1893]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: 10
  - Docker for Windows Version: 18.03.0-ce-win58(16761)

### Expected behavior
External IP not null
### Actual behavior
I create a service in using the following code :

```
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
   app: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
```

i am expected to read an external-ip when i execute :
 `kubectl get services` 

I tried to access my pod in using port-forward and it worked pretty well so now i would like to achieve it in using a service.

### Steps to reproduce the behavior

  1. Create a kubertenes service in using kubectl -f with the file content above.
  2. Execute kubectl get services to display the public endpoint but the external id is empty.
