### ISSUE TITLE
awslogs can't see neither AWS creds file, no env vars on windows

### ISSUE THREAD

**Issue by bloodcarter** [docker/for-win#1896]
Docker for windows version: 18.03.0-ce-win59 (16762)

When trying to use awslogs, there is an error: ```Error response from daemon: failed to initialize logging driver: NoCredentialProviders: no valid providers in chain. Deprecated.```

And nothing helps. Even setting global env vars ```AWS_SECRET_ACCESS_KEY``` and ```AWS_ACCESS_KEY_ID```.  On Linux everything works like a charm.

**Comment by rn** [comment]
please provide steps to reproduce

**Comment by bloodcarter** [comment]
A step to reproduce:
1. On windows or linux (doesn't matter). Be sure you not running this on EC2, on EC2 it works OK.
```
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: myGroup
```
P.S. Be sure to create `myGroup` and give your user access to writing CloudWatch log groups.
