### ISSUE TITLE
Add Kubernetes Ingress support

### ISSUE THREAD

**Issue by vincentditlevinz** [docker/for-win#1901]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: Win 10 pro
  - Docker for Windows Version: 18.03.0-ce-win58 (16761)

I have installed the nginx-ingress-controller (0.10.2 from Kubernetes github) on my Kubernetes cluster and it seems to work fine. However, it exposes the node internal IP which is not directly accessible from a browser executing outside the cluster.

### Expected behavior
It would be great to have a forwarding to localhost as it is the case with the LoadBalancer, but I suspect that it means a special ingress controller support inside "kubernetes for windows"

### Actual behavior
The node internal IP is used as the exposed IP, this IP is unfortunately not accessible directly from the browser running on the main host.

### Steps to reproduce the behavior

  1. Install nginx-ingress-controller as specified here: [https://github.com/kubernetes/ingress-nginx/blob/nginx-0.10.2/deploy/README.md] (note: I had some pb with more recent versions)
  2. Create an ingress test case
  3. **kubectl get ing** should show the node internal IP as the ADDRESS field

**Comment by MikePugs** [comment]
I got the ingress to work fine on docker-for-win by following the install instructions for mac located here

https://kubernetes.github.io/ingress-nginx/deploy/

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml

kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml

```

That will create the ingress controllers. Then you just need to create an ingress for one of your services

Example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vote-ingress
spec:
  rules:
  - host: vote.local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: vote
          servicePort: 5000
```
