### ISSUE TITLE
Unable to mount D:/Sources

### ISSUE THREAD

**Issue by dazinator** [docker/for-win#2025]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Expected behavior

1. Can mount a volume to D:/Sources

### Actual behavior

> ERROR: Service 'foo' failed to build: container 5d943ebc5a1aa6c3ea548f5f4d03f19d2d940f75b226ea82b27349a5525e0a0a encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)

### Steps to reproduce the behavior

  1. Extract the C:/Sources folder from the windows server 2016 iso.
  2. Place it somewhere on your docker host like `C:\DockerMount\Sources`
  3. Create this dockerfile:

```
FROM microsoft/windowsservercore
VOLUME D:/sources
RUN powershell -NoProfile -Command Dir
```
2. And this docker-compose.yml file next to it:
```
version: '2.2'
services:  
  foo:  
    build: 
      context: .
      dockerfile: './DOCKERFILE'
    image: my_foo
    restart: always
    # privileged: true # not supported on windows 
    volumes:
     - C:\DockerMount\Sources:D:\sources    
    mem_limit: 2g
```

The run `docker-compose build --no-cache --force-rm`

> Service 'foo' failed to build: container 755e81866d3badec0119536f1490c5065e71936b5382278858ecc760fc78b529 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)

What is the problem?
