### ISSUE TITLE
error: Stack.compose.docker.com "mystack" is invalid: mystack

### ISSUE THREAD

**Issue by awidjaja** [docker/for-win#2055]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 52C48E5F-6523-4AFE-B6F7-3DD304750149/2018-05-22_22-14-07

### Expected behavior
Docker will deploy the stack to kubernetes
### Actual behavior
error: Stack.compose.docker.com "mystack" is invalid: mystack
### Information

  - Windows Version: 1803 Build 17134.48
  - Docker for Windows Version: 
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: kubernetes

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
 Kubernetes:
  Version:     v1.9.6
  StackAPI:                   Unknown

### Steps to reproduce the behavior

  1. docker stack deploy --compose-file .\docker-compose.yml mystack

docker-compose.yml:

``` yml
version: "3.3"

services:

  api:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    #deploy:
    #  replicas: 2

  articles:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: articles
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  comments:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: comments
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  favorites:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: favorites
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  follows:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: follows
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  users:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  nats:
    image: nats
    ports:
      - "4222:4222"

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

volumes:
  mongodb:
```

note: `docker-compose up` command is working using the same file

**Comment by fletch3555** [comment]
Here's a simpler repro case:

`docker-compose.yml` contents
```
version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
```
----
`docker-compose up`/`docker-compose down` output
```
PS > docker-compose up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting test_web_1 ... done
PS > docker-compose down
Stopping test_web_1 ... done
Removing test_web_1 ... done
Removing network test_default
```
----
`docker stack deploy` output
```
PS > docker stack deploy --compose-file .\docker-compose.yml test
Stack.compose.docker.com "test" is invalid: test: Invalid value: "version: \"3.0\"\nservices:\n  web:\n    image: nginx:latest\n    ports:\n    - mode: ingress\n      target: 80\n      published: 80\n      protocol: tcp\nnetworks: {}\nvolumes: {}\nsecrets: {}\nconfigs: {}\n": parse error: services.web.ports.0 must be a string or number
```
