### ISSUE TITLE
Docker compose can not start. Service network not found after restart docker

### ISSUE THREAD

**Issue by JoBaAl** [docker/for-win#2194]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  72ADF485-4186-4DCE-BAE8-80F9955B7B9F/2018-07-11_15-54-47

### Expected behavior
On restart the containers must start automatically without errors.

### Actual behavior
All the containers run ok after running the command `docker-compose -up -d`. The problem is when I restart the docker service. Then, once restarted, all the containers are stoped and when I run the command  `docker-compose start` the following error is shown:

Error response from daemon: network ccccccccccccc not found

### Information

  - Windows Version: Windows 10 pro
  - Docker for Windows Version: Docker version 18.03.0-ce, build 0520e24

### Steps to reproduce the behavior

  1. Docker-compose file:
```
version: '3'

services:
  service_1:
    image: image1
    restart: always
    build:
      context: C:/ProgramData/Docker/volumes/foo2
      dockerfile: Dockerfile
      args:
        ENTRY: "1"
    volumes:
      - C:/ProgramData/Docker/volumes/foo1:C:/foo1
      - C:/ProgramData/Docker/volumes/foo2:C:/foo2
  service_2:
    image: image2
    restart: always
    build:
      context: C:/ProgramData/Docker/volumes/foo2
      dockerfile: Dockerfile
      args:
        ENTRY: "2"
    volumes:
      - C:/ProgramData/Docker/volumes/foo1:C:/foo1
      - C:/ProgramData/Docker/volumes/foo2:C:/foo2
  service_3:
    image: image3
    restart: always
    build:
      context: C:/ProgramData/Docker/volumes/foo2
      dockerfile: Dockerfile
      args:
        ENTRY: "4"
    volumes:
      - C:/ProgramData/Docker/volumes/foo1:C:/foo1
      - C:/ProgramData/Docker/volumes/foo2:C:/foo2
```
  2. Dockerfile:
```
FROM microsoft/dotnet-framework:3.5

ARG ENTRY
ENV my_env=$ENTRY

WORKDIR C:\\foo2

ENTRYPOINT C:/foo2/app.exe %my_env%
```
