### ISSUE TITLE
Cannot connect with npipe:// protocol

### ISSUE THREAD

**Issue by Getitdan** [docker/for-win#2244]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Connect to a container using npipe:// protocol.

### Actual behavior
Error during the connection.

### Information
I'm using [Traefik ](https://docs.traefik.io/)image, and the only way to communicate with it, is using npipe protocol (right?), instead of using a unix socket. But it seems that this path is not presented on the guest container: //./pipe/docker_engine.

Is it a bug, or did I do something wrong?

  - Windows Version: 10 Pro 64 bit, fully updated.
  - Docker for Windows Version: 18.06.0-ce-win70 (19075) and 18.03.1-ce-win65.

### Steps to reproduce the behavior
  1.  Create this docker-compose.yml:

```
version: '3.2'
services:
  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker --docker.endpoint=npipe:////./pipe/docker_engine
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
```
  2. Run:
`docker-compose up -d`

  3. Get the following error log:

> Failed to retrieve information of the docker client and server host: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.21/version: dial tcp: lookup //./pipe/docker_engine: no such host
