### ISSUE TITLE
Stack deploy not working with volumes using kubernetes

### ISSUE THREAD

**Issue by lvoliveira** [docker/for-win#2309]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 30634BE8-24A6-4FBC-8F70-B76775566A07/20180727084919

### Expected behavior
Stack deploy worked
### Actual behavior
Stack.compose.docker.com "test-deploy" is invalid: test-deploy: Invalid value: "null": conversion to kube entities failed: W:\test\folder\web\static: only absolute paths can be specified in mount source
### Information

  - Windows Version: Windows 10 Pro (17134)
  - Docker for Windows Version: 18.06.0-ce-win72 (19098) (channel: stable)

### Steps to reproduce the behavior

  1. docker stack deploy -c test.yaml test-deploy

test.yaml
```
version: '3.3'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    volumes:
     - "./web/static:/static"
    ports:
     - "80:80"

  words:
    build: words
    image: dockerdemos/lab-words
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 16M

  db:
    build: db
    image: dockerdemos/lab-db

```
