### ISSUE TITLE
kube-dns not working

### ISSUE THREAD

**Issue by marchev** [docker/for-win#2409]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
`kube-dns` works correctly and resolves hostnames within the cluster.

### Actual behavior
`kube-dns` does not work, i.e. all name resolutions are unsuccessful.

### Information

  - Windows Version: **Windows 10 Pro, Version 1803, OS Build 17134.165**
  - Docker for Windows Version: **18.06.0-ce-win72 (19098), Channel: stable, 5513f91**

### Steps to reproduce the behavior

  1. Create a `busybox-pod.yaml`, e.g.:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```
  2. Deploy a busybox pod, i.e. `kubectl apply -f busybox-pod.yaml`
  3. Do an `nslookup` via `busybox`, e.g. `kubectl exec busybox nslookup kubernetes.default`. The output indicates unsuccessful name resolution:
```
Server:         10.96.0.10
Address:        10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer
```

Alternatively, `kubectl describe pod kube-dns -n kube-system` displays the following warning:
```
...
 Warning  Unhealthy              7h (x2 over 7h)  kubelet, docker-for-desktop  Readiness probe failed: Get http://10.1.0.16:8081/readiness: dial tcp 10.1.0.16:8081: getsockopt: connection refused
```
