### ISSUE TITLE
Can't access container IP from host docker for windows stack

### ISSUE THREAD

**Issue by JoBaAl** [docker/for-win#2656]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Reach container IP from host

### Actual behavior
I'm using the following docker compose file to build my docker swarm stack that have windows containers deployed in a Windows 10:

```
version: '3.2'

services:
  service1:
    image: myrepository/dotnet-framework:3.5-windowsservercore
    environment:
      - my_path="C:/app/build/app.exe"
      - my_arg= 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.id == asdfasdgasgasg
    volumes:
      - service1:C:/app
  service1:
    image: myrepository/dotnet-framework:3.5-windowsservercore
    ports:
      - target: 7878
        published: 7878
        mode: host
    environment:
      - my_path="C:/app/app.exe"
      - my_arg= 2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.id == asdfasdgasgasg
    volumes:
      - service1:C:/app

volumes:
  service2:
    external:
      name: service1
  service1:
    external:
      name: service1
```
As you can see service2 is listening in port 7878. I know, as is shown in [this ](https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/)post, that I can't reach this port using localhost:7878. Thus I run the command docker inspect containerID to figure out the IP address of the container.

```
"MacAddress": "",
"Networks": {
    "diatec_default": {
        "IPAMConfig": {
            "IPv4Address": "10.0.3.44"
        },
        "Links": null,
        "Aliases": [
            "38c632e1fc8e"
        ],
        "NetworkID": "",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "10.0.3.44",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "00:15:5d:ae:b3:bf",
        "DriverOpts": null
    }
}
```
If I ping the container service2 from service1, it responds. But If I try to access the port 10.0.3.44:7878 from the host, there's no response. How could I reach port 7878from the hots? On the other hand, I have Linux containers that must reach the 'service2' windows container.

### Information

  - Windows Version: Version Windows 10 Pro 1703
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)
