### ISSUE TITLE
Beta 31: Docker Compose client version 1.22 is too old.

### ISSUE THREAD

**Issue by StefanScherer** [docker/for-win#268]
### Expected behavior

Docker Compose should with Windows containers on Windows 10 and Docker 4 Windows Beta 31.

### Actual behavior

```
PS C:\issue28452> docker-compose up
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Install Docker for Windows Beta 31 with Docker 1.13.0-rc2
  2. Switch to Windows containers
  3. Use docker-compose eg with `docker-compose.yml` from  https://github.com/docker/docker/issues/28452

```
PS C:\issue28452> docker-compose --version
docker-compose version 1.9.0, build 2585387
PS C:\issue28452> docker-compose up
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
PS C:\issue28452> docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             windows/amd64
 Experimental:        false
PS C:\issue28452>
```

**Comment by StefanScherer** [comment]
Can I set the client version in docker-compose as well?

**Comment by justincormack** [comment]
I think this issue is discussed somewhere. What compose file version are you using?

**Comment by StefanScherer** [comment]
```yaml
version: '2'
services:
  db:
    image: microsoft/windowsservercore
    command: powershell /c sleep 3600

  web:
    # image: microsoft/windowsservercore
    build: .
    command: ping db
    depends_on:
      - "db"

networks:
  default:
    external:
      name: nat
```

Just to test DNS
