### ISSUE TITLE
`docker-compose up` or even `docker-compose -v` does nothing and exit

### ISSUE THREAD

**Issue by brunolm** [docker/for-win#2699]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BAD61E23-8E5F-4891-AAB0-E23B40CD510B/20181004102209

### Expected behavior
`docker-compose up` on a v3 should start all services

### Actual behavior
`docker-compose up` exits immediatelly

### Information

  - Windows Version: Windows 10 (1803 OS Build 17134.285)
  - Docker for Windows Version: 18.06.1-ce-win73 (19507) (Stable)
    - also tried Edge, same behavior

### Steps to reproduce the behavior

  1. `docker-compose up`

```
version: '3'

services:
  api:
    image: node:8.11.3
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
```

![image](https://user-images.githubusercontent.com/706078/46477952-429d7b80-c7c2-11e8-97a4-94c6eb0fab17.png)

**Notes**

- even if there is no `docker-compose.yml` file it has the same behavior
- I tried to normally reinstall docker and it didn't change anything
