### ISSUE TITLE
How to access LAN IP 172.17.61.14 from docker container?

### ISSUE THREAD

**Issue by ddzobov** [docker/for-win#2718]
I use linux containers on windows machine - latest docker edge
I think it is impossible because default bridge subnet is 172.17.0.0/16.

How can i access LAN IP 172.17.61.14 without changing subnet or how can i change bridge subnet?

**Comment by ddzobov** [comment]
Solved with docker-compose.yml

```
networks:
 default:
   driver: bridge
   ipam:
     driver: default
     config:
       - subnet: 192.168.0.0/24
```
