### ISSUE TITLE
docker-compose not working (no response)

### ISSUE THREAD

**Issue by YuK1Game** [docker/for-win#2923]
executed the `docker-compose` command but I have no response.
There are no clues at all.

Is the log output somewhere?

```
C:\Users\UserName\Documents\Docker\PHPServer>docker-compose up

```

![-1](https://user-images.githubusercontent.com/20548753/48814207-37f07300-ed7d-11e8-84f6-a57f1d1dd484.jpg)

# docker-compose.yml
```
version: '2'

services:
  php56:
    build: ./php56
    ports:
      - "8056:80"
    volumes:
      - ../../Projects/projectname:/var/www/html/projectname
    depends_on:
      - mysql56

  php72:
    build: ./php72
    ports:
      - "8072:80"
    volumes:
      - ../../Projects/projectname:/var/www/html/projectname
    depends_on:
      - mysql57

  mysql56:
    build: ./mysql56
    ports:
      - "3356:3306"
    volumes:
      - ./mysql56/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass

  mysql57:
    build: ./mysql57
    ports:
      - "3357:3306"
    volumes:
      - ./mysql57/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
```

# Docker Versions
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

# Docker Compose Versions
```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

# Windows Versions
```
Windows 10 Professional
```

Help me, thanks.
