### ISSUE TITLE
Kubernetes local cluster should be configured for secure access

### ISSUE THREAD

**Issue by aparamon** [docker/for-win#3253]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 92DF728C-3FAA-47C7-AD28-3064722AA675/20190118104344

### Expected behavior

Kubernetes local cluster should be configured for secure access with TLS cert validation, so clients like [Python library](https://github.com/kubernetes-client/python) do not issue unnecessary warnings. Generated `cluster` in `.kube/config` should look like
````
- cluster:
    certificate-authority: C:\ProgramData\DockerDesktop\pki\apiserver.crt
    server: https://localhost:6445
  name: docker-for-desktop-cluster
````
or
````
- cluster:
    certificate-authority-data: LS0tLS1CRUdJ<skip>tCg==
    server: https://localhost:6445
  name: docker-for-desktop-cluster
````

For comparison, [Minikube](https://kubernetes.io/docs/setup/minikube) creates
````
- cluster:
    certificate-authority: /home/username/.minikube/ca.crt
    server: https://127.0.0.1:8443
  name: minikube
````

### Actual behavior

Docker for Desktop specifies `insecure-skip-tls-verify`:
````
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6445
  name: docker-for-desktop-cluster
````

### Information
  - Windows Version:
Windows 10 Version 1809 Build 17763.107

  - Docker for Windows Version:
Decker Descktop CE Version 2.0.0.2 (30215) Channel "stable" Build 0b030e1
Docker version 18.09.1 build 4c52b90
Kubernetes v1.10.11

### Steps to reproduce the behavior

1. Start Kubernetes local cluster.
2. Run [minimal Kubernetes Python client script](https://github.com/kubernetes-client/python/blob/master/examples/example1.py):
````
>python example1.py
Listing pods with their IPs:
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.r
eadthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
10.1.0.202      docker  compose-74649b4db6-tqwwc
192.168.65.3    docker  compose-api-569784c5b6-8jd87
192.168.65.3    kube-system     etcd-docker-for-desktop
192.168.65.3    kube-system     kube-apiserver-docker-for-desktop
192.168.65.3    kube-system     kube-controller-manager-docker-for-desktop
10.1.0.203      kube-system     kube-dns-86f4d74b45-2c7pk
192.168.65.3    kube-system     kube-proxy-2lq7j
192.168.65.3    kube-system     kube-scheduler-docker-for-desktop
````
