### ISSUE TITLE
Failed starting container: 'failed to create endpoint'

### ISSUE THREAD

**Issue by nerumo** [docker/for-win#335]
### Description
I use windows server containers with a compose file. Since networking with windows containers is a bit shaky, I use the default external network 'nat' which is created by default. From time to time if I go up and down with compose, I get errors when starting a container. Stopping, rebuilding, restarting container does not help. Sometimes it helps to restart com.docker.engine, sometimes it helps to restart docker for windows, sometimes it only helps to restart the computer. But after that, it starts working again. 

### Part of log
[15:38:57.087][WindowsDockerDaemon][Info   ] time="2016-12-18T15:38:57.087759900+01:00" level=error msg="Handler for POST /v1.24/containers/4f12ba314d3c1066e3cd4a8f6e51700ba5d0aa20327afd197aeb5a0c8caece73/start returned error: failed to create endpoint wwagdispoe2e_dispo-sql_1 on network nat: HNS failed with error : Unspecified error" 

### Docker Compose
```
version:

 '2.1'
volumes:
  dispo-db: 
    driver: local
services:
  dispo-web:
    ports:
      - "80:80"
    build: 
      context: ./Dispo-Dev
    hostname: wwag-dispo-web-e2e
    volumes:
      - '../Wettstein.Web/Wettstein.Web:C:/inetpub/wwwroot/Web'
      - '../Wettstein.Web/Wettstein.Client:C:/inetpub/wwwroot/Client'
    links:
      - dispo-sql
      - dispo-es
  dispo-es:
    build: ./Dispo-Es
    hostname: wwag-dispo-es-e2e
    ports:
      - "9200:9200"
    volumes:
      - ./DB-e2e/Wettstein-Db:C:/Db
  dispo-sql:
    build: ./Dispo-Db-e2e
    ports:
      - "1433:1433"
    hostname: wwag-dispo-sql-e2e
    volumes:
      - ./DB-e2e/Intermediate-Db:C:/Db
      - dispo-db:C:/Databases

networks:
  default:
    external:
      name: nat
```

### Diangostics 
F225804C-950F-4743-ABE0-5037CB3272EC/2016-12-18_15-41-54
