### ISSUE TITLE
Detected problem of Docker for Windows + BitLocker protected drive

### ISSUE THREAD

**Issue by Eugentis** [docker/for-win#3369]
Hi!
I have Docker for Windows (last stable for today) and Windows 10 + additional HDD protected with Bitlocker. My docker images are stored on this locked drive (with sharing drive for Docker). Docker doesn't start on login in system, I starts it only after unlocking this drive.
I used a docker-compose for my images and I've notified some problems with shared drives - when I am trying to start my image it doesn't syncronize all files to this image - only docker and env directories.

I tried to disable antivirus system and firewalls but it doesn't help. I've looked at docker logs - there were no problems, no errors were during the build and up the application.
I've tried to restart Docker - it doesn't help.

Some time later I've found that if I will made "reshare" (disable sharing drive D, apply, enable sharing drive D, apply) this drive for Docker - problem dissapears.
I suppose the problem with sharing drive should be catched and user should be notified...

Uploaded Diagnostics ID is E9369C69-EDF1-4EBE-93E0-992401D90367/20190210110557

### Expected behavior
If Docker have some problems with access to shared drive - throw an error and notify user

### Actual behavior
No errors, no log records
App runs without file sync

### Steps to reproduce the behavior
Preconditions:
1. Windows 10 with at least 2 drives and second drive locked with Bitlocker
2. Docker for Windows 10 with disable autostart and enable sharring for second drive
Steps:
1. Start application, check sync - all works
2. Stop application
3. Restart Windows
4. Unlock drive
5. Start Docker
6. Start application - no errors, 
7. check sync - files not synced
8. Check docker-compose logs - no errors

docker-compose.yaml
```
version: '3'

services:
    app:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/webserver-apache/Dockerfile
        image: php:7.3.1-apache-stretch
        volumes:
            - "./docker/webserver-apache/sites-enabled:/etc/apache2/sites-enabled:ro"
            - "./:/var/www/html"
        ports:
            - 8080:80
        networks:
            - dphptrainnet
            
    mariadb:
        restart: unless-stopped
        image: mariadb:10.4.1
        networks:
            - dphptrainnet
        volumes:
            - ./env/mariadb/data:/var/lib/mysql            
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

networks:
    dphptrainnet:
```

DockerFile:
```
FROM php:7.3.1-apache-stretch

# Setting up constants for an environment
ENV PHP_MEMORY_LIMIT    512M

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
	php composer-setup.php && \
	php -r "unlink('composer-setup.php');" && \
	mv composer.phar /usr/local/bin/composer
	
RUN apt-get update && \ 
	apt-get install -y curl vim git zip unzip

# Setting up httpd issues
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN a2enmod rewrite headers && /etc/init.d/apache2 restart
RUN echo "127.0.0.1     dockertrain.local" >> /etc/hosts

WORKDIR "/var/www/html"
	
RUN a2enmod rewrite	
```
