### ISSUE TITLE
Docker Compose service port is exposed while it should be hidden

### ISSUE THREAD

**Issue by MrMedTech** [docker/for-win#3388]
Hi
I want to run multiple services in my docker compose file where only one port should be accessible from the host network.
Therefore I created the following compose file:
```
version: '2.1'
services:

  usermanagement-service:
    image: usermanagementservice
    restart: on-failure
    ports:
      - "7778:7778"
    volumes:
        - logdatavolume:/logdata
    mem_limit: 500m
    memswap_limit: 1000m
    tty: true
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
        - testnet
        - secretnet


  mysqldb:
    image: usermanagementservice/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    mem_limit: 500m
    memswap_limit: 1000m
    volumes:
      - userdata:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
```
This works fine but when I do localhost:3306 ,the default port of mysql is accessible while I was awaiting a timout expection or sth like that.
How do I have to define my network / compose file that only the usermanagementservice is accessible and the mysql is hidden?

Thank you
