### ISSUE TITLE
Windows Firewall to block shares

### ISSUE THREAD

**Issue by ninomllr** [docker/for-win#3522]
- [X] I have tried with the latest version of my channel (Stable and Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Mounting a volume into a container

### Actual behavior
ERROR: Cannot create container for service windows: b'Drive sharing seems blocked by a firewall'

### Information
I set up a Dockerfile and docker-compose.yml for my development environment. Everything works well on my Ubuntu. Today I tried to get it up and running on a Windows Host system as well, without luck. I always get the following "ERROR: Cannot create container for service windows: b'Drive sharing seems blocked by a firewall'".

When I run this: 
`docker run --rm -v c:/Users:/data alpine ls /data`

It works!

Then I run my dumped down docker image:

Dockerfile
```
FROM node:10

WORKDIR /usr/src/frontend-app
ENTRYPOINT [ "/bin/bash" ]

```

docker-compose.yml
```
version: '2'

services:
  windows:
    build:
      context: ./windows/
    volumes:
      - C:/Users/myusername/projects/software_stack/windows:/usr/src/frontend-app
    networks:
      static-network:
        ipv4_address: 10.0.75.5

networks:
  static-network:
    ipam:
      config:
        - subnet: 10.0.75.0/28
     
```

And get the firewall error when I build. 

```
docker-compose build windows
docker-compose run windows

```

Interestingly enough when I have the firewall error once, I have to reset to factory settings to make `docker run --rm -v c:/Users:/data alpine ls /data` run again.

I tried every solution mentioned in here without success. Even completely disabling the firewall leads to the same error: https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/43904051

Do you have any other ideas on what is going on?

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: Docker version 18.09.3, build 774a1f4 (but I also tried with the stable release)

### Steps to reproduce the behavior
see above. Although I fear this is some local setting and not a reproducable error..
