### ISSUE TITLE
Docker network missing after Win 2019 host reboot (using docker-compose)

### ISSUE THREAD

**Issue by cukal** [docker/for-win#3685]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Restart with network present

### Actual behavior
After windows host reboot network is missing

### Information
  - Is it reproducible?
Yes

  - Is the problem new?
Unsure 

  - Windows Version: 
Windows Server 2019 - 10.0.17763.379

  - Docker for Windows Version:
18.09.4

### Steps to reproduce the behavior
Create 3 containers with docker-compose: 

```
version: '3'
services:
    front:
        image: strm/nginx-balancer
        container_name: load-balancer
        ports:
            - "80:8080"
        environment:
            - "NODES=web1:80 web2:80"
        restart: always
    web1:
        image: strm/helloworld-http
        restart: always
    web2:
        image: strm/helloworld-http
        restart: always
```

Execute docker-compose up
Reboot server

Containers do not come online and event viewer throws:
```Failed to start container 3332e53cdcc0ef87d147c60526e7da8126d4dfcd4f3328cc17ddffea32214f31: network c5821f52bbb0378fd9a22db9dd670b3e9c90c34e6e0fb09c0f40479bdae1c283 not found```
