### ISSUE TITLE
Can't publish port in swarm mode

### ISSUE THREAD

**Issue by lsibilla** [docker/for-win#3712]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1C65CE86-4B92-4D27-8DF0-B10C60B1137A/20190408091729

### Expected behavior
Using the following compose file:
```
version: '3.5'

services:
  iis:
    image: microsoft/iis:windowsservercore-1803
    ports:
      - target: 80
        published: 8080
        mode: host
```

I expect to reach the default IIS website at http://localhost:8080

### Actual behavior

I don't receive any answer at http://localhost:8080

### Information

I have tried several alternatives.

The following provided the same behaviour:
- using the container IP address instead of the host address
- the same setup on another Windows 1803 box
- remove the `mode: host` from the compose file

The following provided the expected behaviour:
- `docker container run -d -p 8080:80 --rm --name iis microsoft/iis`
- `docker-compose up` instead of `docker stack deploy`
- `docker service create --name iis -p mode=host,target=80,published=8080 microsoft/iis`

I'm using
  - Windows Version:  Windows 10 Enterprise Version 1803 (OS Build 17134.648)
  - Docker for Windows Version: 2.0.0.3

### Steps to reproduce the behavior
  1. Use the compose file here above with the commande `docker stack deploy -c docker-compose.yml iis`
