### ISSUE TITLE
[WSL2] Can't use named volumes in Docker Compose

### ISSUE THREAD

**Issue by SlvrEagle23** [docker/for-win#4396]
The relevant portion of my Docker Compose file looks like so:

```yaml
version: '2.2'

services:
  mariadb:
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
```

I also have a .env file in the same directory with only these contents:

```
COMPOSE_PROJECT_NAME=azuracast
```

When attempting to spin up a Docker container with WSL2, it appears to be trying to create the named volumes in the Windows system directory, instead of recognizing that they're internal to Docker:

```
ERROR: for mariadb  Cannot start service mariadb: error while creating mount source path '/mnt/c/WINDOWS/system32/azuracast_db_data': mkdir /mnt/c/WINDOWS/system32/azuracast_db_data: permission denied
```

I'm aware of the existing issue #4374 relating to Docker Compose, and have already updated my `DOCKER_HOST` environment variable to point to WSL2.

Is this related to that ongoing issue, or is this something else?
