### ISSUE TITLE
Docker for Windows 2.1.0.0, UDP mapping is not working for intra-container communication

### ISSUE THREAD

**Issue by colcek** [docker/for-win#4424]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
DNS container whose 53/udp port mapped to HOST:53 is started with bridge network. Second container in the same bridged network should be able to send DNS queries to the DNS container through the host without linking and IP of the DNS container. 

### Actual behavior
Even though the second container can ping the host, only TCP enabled DNS queries works from the second container. While TCP mapping is present for intra-container communication, UDP label in port mapping is working and only UDP can be used from host to container direction. It seems that intra-container communication does some trick and by-passes the host.

### Information

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.1.0.0
  - It is reproducible in different computers
  - Downgrading to previous version (2.0.0.3) solves the problem

### Steps to reproduce the behavior

  1. Here is the `docker-compose.yml` to start DNS service with Consul
```yml
version: '3'

services:
  consul:
    image: consul:latest
    restart: unless-stopped
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
      - SERVICE_TAGS=core
      - SERVICE_8500_NAME=consul
      - SERVICE_8300_IGNORE=true
      - SERVICE_8301_IGNORE=true
      - SERVICE_8302_IGNORE=true
      - SERVICE_8600_IGNORE=true
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/consul
      - -bootstrap-expect=1
      - -bind=0.0.0.0
      - -client=0.0.0.0
      - -dns-port=53
      - -recursor=8.8.8.8
      - -ui
    ports:
      - "8500:8500"
      - "53:53/udp"

  registrator:
    image: gliderlabs/registrator:latest
    restart: unless-stopped
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul

networks:
  default:
    driver: bridge
```
  2. Start second container to join network created by previous docker-compose
```powershell
PS > docker run -ti --network=core_default ubuntu
```
  3. Install `dnsutils` and others to ubuntu container
```console
root@4e5551889736:/# apt-get update
root@4e5551889736:/# apt-get install dnsutils iputils-ping nmap
```
  4. Here is the current network inspect results
```js
[
    {
        "Name": "core_default",
        "Id": "15a69cab012bf30f5380ded6dcebd11f1b5290d8d37ea039b1b69da882f7de48",
        "Created": "2019-04-09T08:22:47.2894365Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4e5551889736ecaade8fb923c0cf356578c6b03224e6d05ca6a607b796e3e52d": {
                "Name": "ecstatic_tesla",
                "EndpointID": "9291fce771a559b596883d3dba580f59b9ab9270aa989c3eed312eb909e50432",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "93522d7d97e8515cc7da0f8674786df89f0fac236f4f9ab1abdee3a9d1765c80": {
                "Name": "core_registrator_1",
                "EndpointID": "01bb1b155eb6e3af646ac3732071518a350d2005dd0c532cc9a6fb893bbf7e7c",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "d941ad2aa94bc7a81148d7217ce829d9cd2ee0654baa5991637f3aa2140a6720": {
                "Name": "core_consul_1",
                "EndpointID": "edbd61f402060213e3c0c20263dd60becaff85f23853590ea032a75bdf5b00c4",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "core",
            "com.docker.compose.version": "1.23.2"
        }
    }
]
```
  5. Test if the second container can ping host
```console
root@4e5551889736:/# ping 172.19.0.1
PING 172.19.0.1 (172.19.0.1) 56(84) bytes of data.
64 bytes from 172.19.0.1: icmp_seq=1 ttl=64 time=0.077 ms
64 bytes from 172.19.0.1: icmp_seq=2 ttl=64 time=0.105 ms
```
  6. See the DNS resolution is **NOT** working
```console
root@4e5551889736:/# dig consul.service.consul @172.19.0.1

; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> consul.service.consul @172.19.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached
```
  7. See the DNS resolution is working over **TCP**
```console
root@4e5551889736:/# dig consul.service.consul @172.19.0.1 +tcp

; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> consul.service.consul @172.19.0.1 +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59555
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;consul.service.consul.         IN      A

;; ANSWER SECTION:
consul.service.consul.  0       IN      A       172.19.0.2

;; ADDITIONAL SECTION:
consul.service.consul.  0       IN      TXT     "consul-network-segment="

;; Query time: 4 msec
;; SERVER: 172.19.0.1#53(172.19.0.1)
;; WHEN: Mon Aug 05 08:25:55 UTC 2019
;; MSG SIZE  rcvd: 102
```
  8. Try same DNS query directly from host machine and see **UDP** is working
```powershell
PS > nslookup consul.service.consul 127.0.0.1
Server:  UnKnown
Address:  127.0.0.1

Name:    consul.service.consul
Address:  172.19.0.2
```
  9. As expected, same DNS query is not working from host machine with **TCP**
```powershell
PS > nslookup "-set vc" consul.service.consul 127.0.0.1
Server:  UnKnown
Address:  127.0.0.1

*** UnKnown can't find consul.service.consul: Unspecified error
```
  10. `netstat` from host machine (removed ports other than 53)
```powershell
PS > netstat -an | select-string :53

  UDP    0.0.0.0:53             *:*
  UDP    0.0.0.0:53             *:*
  UDP    [::]:53                *:*
```
  11. Finally, to see if the port is open, tried `nmap`. Interestingly, it shows that **TCP** is open
```console
root@4e5551889736:/# nmap -p 53 172.19.0.1

Starting Nmap 7.60 ( https://nmap.org ) at 2019-08-05 08:37 UTC
Nmap scan report for 172.19.0.1
Host is up (0.000072s latency).

PORT   STATE SERVICE
53/tcp open  domain
MAC Address: 02:42:77:D0:AD:33 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.71 seconds
```
