### ISSUE TITLE
files not visible in kubernetes

### ISSUE THREAD

**Issue by stefanloerwald** [docker/for-win#4512]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 6E6A01EA-C6A9-463D-A152-EA738CB7CBCF/20190813163234

### Expected behavior

A mount of a directory should include all subdirectories and files.

### Actual behavior

Some files are not visible. I can't see any difference in properties, such as permissions. In fact, a file that is visible in one subdirectory cannot be seen in another subdirectory even when it's simply copy pasted there.
Note that the problem does not occur with docker only.

### Information

  - Windows Version: Windows 10 Version 1809 (OS Build 17763.615)
  - Docker Desktop Version: 2.1.0.1 (37199)
      - Engine: 19.03.1
      - Kubernetes: 1.14.3
  
 ### Steps to reproduce the behavior

  1. Create a directory C:/data with a few files in it. (actual files I encountered the problem with are attached in zipped form)
  2. Share C in docker for windows settings
  3. Run docker run -i -v C:/data:/data ubuntu:18.04
  4. Use ls data to look for files
  5. See all files as expected
  6. Close down.
  7. Create file invisible.yml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invisible-files
  labels:
    k8s-deployment: invisible-files
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-deployment: invisible-files
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        k8s-deployment: invisible-files
    spec:
      volumes:
      - name: data
        hostPath:
          path: /C/data/
          type: DirectoryOrCreate
      containers:
        - name: invisible-files
          volumeMounts:
            - name: data
              mountPath: /data
          image: ubuntu:18.04 
          command: ["ls", "-a", "data"]
          imagePullPolicy: Always
```

  8. kubectl apply -f invisible.yml
  9. Open the log for the deployment and notice that the list of files is shorter...

If the problem doesn't show, try adding files and update the deployment and see if they appear or if new files remain hidden. That's at least my strongest hunch at what's going crazy here...

[files.zip](https://github.com/docker/for-win/files/3498033/files.zip)
