### ISSUE TITLE
Corrupted state after Windows shutdown

### ISSUE THREAD

**Issue by Vespira** [docker/for-win#4637]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics (not for now but I will if it appears that the issue is real)
  - Diagnostics ID:

As stated in this issue [](https://github.com/docker/for-win/issues/1038) , I posted that I would create an issue if I still have the problem with the latest Docker version, which is the case.

### Expected behavior

When I do a `docker-compose up -d`, I expect, as it did before, my containers to start normally.
I'm not sure if this is related to docker-compose or not, but I guess it's not, because I can solve the issue without touching docker-compose file, just by resetting Docker to factory settings. 

In my docker-compose I tried with only one service like this for instance : 

```
version: '2'
services:
    durnal-stock-db:
         image: postgres
         ports:
             - 5435:5432
         environment:
             POSTGRES_PASSWORD: secret
             POSTGRES_USER: user
            POSTGRES_DB: my-database
            TZ: "Europe/Paris"
```

### Actual behavior

I'm getting an error for each container the docker-compose try to start. Error is with the following pattern : 

> ERROR: for <service-name> Cannot start service <service-name>: b'driver failed programming external connectivity on endpoint <container-name> (<container-id>): Error starting userland proxy: listen tcp 0.0.0.0:5435: bind: Only one usage of each socket address (protocol / network address / port) is permitted.

When I do a `docker ps`, I see nothing running.  I checked my local port used by processes, and neither the port 5432, nor the 5435 are used. 

I tried to restart Docker, remove networks, volumes, containers, images; the only thing that works is to 'Reset to factory' settings from the Docker desktop app.

### Information

  - Windows Version: 10 v.1803
  - Docker Desktop Version: 2.1.0.1 (build 37199)

### Steps to reproduce the behavior

  1. I just have to reboot computer with Docker running.
  2. Then when I try to restart containers, I have one error per container I try to start.
