### ISSUE TITLE
Docker-compose does not generate an error for invalid repository names

### ISSUE THREAD

**Issue by Untiring** [docker/for-win#4986]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Get an error telling you the repository name given in the docker-compose file in the 'image' section is invalid
### Actual behavior
building {servicename}
flashing cursor, no building steps being executed,
no error, ctrl+c doesn't terminate the build process. the only way to stop it by closing the terminal
### Information
when building a custom image with docker-compose I sheepishly tried to name the image with capital letters. when trying to manually build my image with the same name I noticed that this name is invalid and can only contain lowercase letters. Changed this in the docker-compose file and now it does run. An error pointing you to this mistake would have saved me quite some time.

  - Windows Version: 10 pro build 18362
  - Docker Desktop Version: 19.03.4, build 9013bf5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
Check the information section.
give your Dockerfile the following layout:
```yml
version: '3.7'
services:
  {servicename}:
    image: someName
    build:
      context: {some directory with a dockerfile}
# this will not build because of the capital letter in the image name, however it does not generate an error
```
make sure you have a basic docker file in the target directory used in the context section of the docker-compose file
start the build process by running `docker-compose up --build.`
