### ISSUE TITLE
Docker DNS does not resolve container address by name on user-defined network in Windows

### ISSUE THREAD

**Issue by minherz** [docker/for-win#500]
### Expected behavior
A command like `ping db` where `db` is a name of the container does not succeed returning "Ping request could not find host minio1. Please check the name and try again."

### Actual behavior
A command that use container name should resolve to container IP and succeed.

### Information

  - Diagnostic ID: F9F388E9-7AB0-4CE8-BD59-045CF28124A7/2017-02-15_16-45-57
  - Docker host: Version 1.13.1-beta42 (10069)
  - Windows version: Windows 10 x64 Enterprise Version 1607 (build 14393.693)
  - `docker version` command:
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

### Steps to reproduce the behavior

The following can be reproduced by executing `docker run` commands as well.

  1. Create a user-defined network for nat driver (the default `nat` network mask is 172.25.128.0/20):
```
docker network create -d nat -o com.docker.network.windowsshim.networkname=prototype_net --subnet=172.25.132.0/24 --gateway=172.25.132.1 prototype_net
```
  2. Create a docker-compose.yml file with the following content:
```
version: '2.1'
services:
  db:
    image: microsoft/nanoserver
    command: powershell /c sleep 3600
    networks:
      - isolated

  web:
    image: microsoft/nanoserver
    command: ping db
    depends_on:
      - db
    networks:
      - isolated

networks:
  isolated:
    external:
      name: prototype_net
```
  3. Run following command from the folder where the file is stored:
```
docker up
```

The output will be something like
```
Creating temp_db_1
Creating temp_web_1
Attaching to temp_db_1, temp_web_1
web_1  | Ping request could not find host db. Please check the name and try again.
temp_web_1 exited with code 1
```

Using `docker run` command with `--network-alias` in addition to `--name` has the same effect.
