### ISSUE TITLE
Is there a way to have better performance on Windows ?

### ISSUE THREAD

**Issue by Vatvat99** [docker/for-win#507]
### Expected behavior

Expect a web page to load in a few seconds, like 5.

### Actual behavior

The load time of my pages are between 15sec and 40sec, on Windows. On a linux machine, it goes from 1sec to 5sec. I know there is other issues opened regarding performance, but I hoped there was a way to improve it a little bit, even if it's a hack or something I don't know, because 40sec make it just impossible to work.

### Information

- Windows 10 Pro, Symfony project

**Comment by rneugeba** [comment]
Could you give an example/reproduction of this? Without details it's hard to tell where the bottleneck is (network, VM, disk, ...).

Is you symphony project on a volume mount? If so does it go faster if you copy it into the container?

Which version of docker for windows are you?

**Comment by Vatvat99** [comment]
Here are some infos : 

VM: Hyper-V on Windows Pro
Docker : 1.13.1
HDD : 300Gb free on 500 GB
Network : It's a fiber connection (40Mb up & down)

Here is an extract of my docker-compose.yml, my project is on a mounted volume: 
```yml
app.local:
        build:
            context: ./app
        container_name: app
        restart: always
        hostname: app
        domainname: local
        tty: true
        volumes:
            - "${SOURCES_PATH}/app:/var/www/app"
        ports:
            - "8080:8080"
        expose:
            - 8080
            - 9000 # x-debug
        working_dir: "/var/www/app"

```

**Comment by rneugeba** [comment]
Thanks for the info. The purpose of asking to try to copy the files into the container was more to figure out if slowdown is due to the shared volume access or something else.

From your description it is impossible to figure out where the slowdown comes from. It could be shared volume access, could be network related, could be virtualisation overheads etc.

**Comment by Vatvat99** [comment]
I copied the files into the container but the slowdown remains. So it doesn't seem to come from the shared volume access.

**Comment by friism** [comment]
@Vatvat99 interesting - can you post your docker-compose.yml and setup details when copying the files into the container?

**Comment by Vatvat99** [comment]
Here is my docker-compose file. There is a project "app1" which is a php/mysql website. There is node-container for node JS, an api, and the "app2" project, which is a symfony project.

```yml
version: '2'
services:
    app1.local:
        build:
            context: ./app1
        container_name: app1
        restart: always
        hostname: app1
        domainname: local
        tty: true
        volumes:
            - "${SSH_KEY_PATH}:/home/apacheuser/.ssh"
        ports:
            - "80:80"
        expose:
            - 80
            - 9000 # x-debug
        working_dir: "/var/www/app1"

    node-container:
        build:
            context: ./node
        container_name: node
        hostname: node
        domainname: local
        restart: always
        tty: true
        command: bash -c "npm i; npm run start;"
        ports:
            - 8070:8070

    api.local:
        build:
            context: ./api
        container_name: api
        restart: always
        hostname: api
        domainname: local
        tty: true
        volumes:
            - "${SOURCES_PATH}/shared-logs:/data/shared-logs"
            - "${SSH_KEY_PATH}:/home/apacheuser/.ssh"
        ports:
            - "8081:8081"
        expose:
            - 8081
            - 9000 # x-debug
        working_dir: "/var/www/api"

    app2.local:
        build:
            context: ./api
        container_name: app2
        restart: always
        hostname: app2
        domainname: local
        tty: true
        volumes:
            - "${SOURCES_PATH}/shared-logs:/data/shared-logs"
            - "${SSH_KEY_PATH}:/home/apacheuser/.ssh"
        ports:
            - "8080:8080"
        expose:
            - 8080
            - 9000 # x-debug
        working_dir: "/var/www/app2"
```

Regarding the setup, in my docker files I copy the files of my projects with this : 

`COPY app1 /var/www/app1`
