### ISSUE TITLE
Kubernetes Volumes not correctly mounted with WSL2

### ISSUE THREAD

**Issue by Gsyltc** [docker/for-win#5325]
I have migrated to WSL2 - Windows 10.
Since I have the following issue :

Hostpath volume are not mounted into containers. (directory are empty)

The volumes are well created, the desired path is correct. Like 

> /volumes/my-cluster/services1/www

Directory "/volumes" have 777 permissions

Volumes looks like that :

    vol-www 30Mi RWO Retain Bound jeedom/pvc-www hostpath 19m

PersistenVolumeClaim are bounds to the volumes

    pvc-www Bound vol-www 30Mi RWO hostpath 19m

In WSL1, at the start of the deployment (or helm charts installation). If Directories does not exists, they are created. Volume are mounted to the containers and work well
Conditions : volumes must be mounted in /c/.... (not in /mnt/c/...)

With WSL2, there is no need to mount volume in /c/...
`docker run -v /volumes/my-cluster/services1/www:/var/html/www my-image` work well.

With kubernetes, local directories are not created. directory in container are empty. When creating a files on wsl path, it's not appears in the container, and the other way around doesn't work either.

More, the method who works with WSL1 don't work with WSL2 (mount volume in /c/...)

Thanks

### Information

  - Windows Version: 10 build 19037
  - Docker Desktop Version: 2.1.7.0 (41536) Edge
  - Kubetctl Version Client : 1.17.0
                                Server : 1.15.5

  - helm V3.0.1+g7c22ef9
  - Docker 19.03.5

Deployment File
---
```
# Source: charts/supervision/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervision
  namespace: j*****m
  labels:
    app.kubernetes.io/name: supervision
    helm.sh/chart: supervision-2.0.1-beta
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec: 
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: supervision
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable : 1 
    type: RollingUpdate 
    
  # Template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supervision
    spec:
      
      hostname: supervision
      containers:
         # Image
       ....
       - image: "*****1.3"
          imagePullPolicy: IfNotPresent
          # Volumes
          volumeMounts:
            - name: logs
              mountPath: /var/log/mosquitto
       ....
      # Volumes
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: "pvc-supervision-logs"
      - name: persistence
        persistentVolumeClaim:
          claimName: "pvc-supervision-persistence"

```
---
# Source: charts/supervision/templates/persistent-volumes.yaml
```
kind: PersistentVolume
apiVersion: v1
metadata: 
  name: "vol-persistence"
  labels:
    volume: persistence
spec:
  storageClassName: hostpath
  capacity:
    storage: 30Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /c/Workspace/volumes/mqtt/persistence
---
# Source: charts/supervision/templates/persistent-volumes.yaml
kind: PersistentVolume
apiVersion: v1
metadata: 
  name: "vol-logs"
  labels:
    volume: logs
spec:
  storageClassName: hostpath
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /c/Workspace/volumes/mqtt/logs
```
---
# Source: charts/supervision/templates/persistent-volume-claims.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pvc-supervision-persistence"
spec:
  storageClassName: hostpath
  volumeName: "vol-persistence"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
---
# Source: charts/supervision/templates/persistent-volume-claims.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pvc-supervision-logs"
spec:
  storageClassName: hostpath
  volumeName: "vol-logs"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

```

**Comment by templafymek** [comment]
Any update on this?

**Comment by wiruzman** [comment]
Any update on this?

**Comment by simonferquel** [comment]
Unfortunately, we don't support hostpath volumes in wsl2. (we don't support them officially with hyper-v either, but there are some potential tricks to make them work).

I'll try to find a workaround for you, but it is a tricky subject.

**Comment by wiruzman** [comment]
> Unfortunately, we don't support hostpath volumes in wsl2. (we don't support them officially with hyper-v either, but there are some potential tricks to make them work).
> 
> I'll try to find a workaround for you, but it is a tricky subject.

@simonferquel I'll appreciate if you can provide the workaround for this.

**Comment by simonferquel** [comment]
So the idea here would be to leverage cross distro mounts.
Cross distro mounts is actually a tmpfs volume that is mounted in "shared" propagation mode in every distro.

You can put things there to share with other distros, and to docker daemon (that is how we handle docker bind mounts under the hood).

So, start by creating a mountpoint in there, and mount the directory you want to share with your pods:
``` 
mkdir /mnt/wsl/sample-hostmount     
mkdir somedir                                                                                                                                                                           echo hello > somedir/hello                                                                                                                                                              sudo mount --bind somedir /mnt/wsl/sample-hostmount 
```

/mnt/wsl is actually the mount point for the cross-distro mounts tmpfs
Docker Daemon mounts it in its /run/desktop/mnt/host/wsl directory

So from windows side (not wsl) you can try running:
`docker.exe run --rm -it -v /run/desktop/mnt/host/wsl/sample-hostmount:/sample-hostmount alpine cat /sample-hostmount/hello` and see the content of the file (you need to run this from windows, as from wsl, it would rewrite your bind source to expose your own distro's /run/desktop/mnt/host/wsl/sample-hostmount)

Then you can use hostmounts with paths rewritten with the /run/desktop/mnt/host/wsl prefix in your pods.

Please note that this will break if you restart without recreating the bind mount before running docker though.

**Comment by GLStephen** [comment]
@simonferquel Can you point me at some docs regarding recommended method to mount volumes in WSL2 and Docker Desktop? I have all the requisite versions, but there doesn't seem to be good docs on the recommended or preferred method to access files in the Windows environment either via mounts in WSL2 or otherwise.

**Comment by GLStephen** [comment]
To clarify it feels like there needs to be some disambiguation between the wider kubernetes docs and what is available in the WSL2/Docker Desktop install.

**Comment by simonferquel** [comment]
There is no official "mount from a wsl distro" volume support yet (if it becomes a popular demand we will change that, likely with some docker desktop specific volume plugin).
However default volume provider works out of the box (not sure if it stores files on the docker-desktop-data distro or on the windows file system though, I need to check)

**Comment by GLStephen** [comment]
@simonferquel thanks for the response, possible I'm misunderstanding some nomenclature. After some teeth nashing I go this working:

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/Users/sjohnston/Documents/Development/helloworld/app
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dir
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
How does that differ from what you said wasn't possible?
