### ISSUE TITLE
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by supermuka** [docker/for-win#5386]
The following error is occuring on Docker for Windows:

`docker-compose build`

> Building auge-server
> Step 1/8 : FROM google/dart:2.7.0
> ERROR: Service 'auge-server' failed to build: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

###
  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 10F504BD-26CB-43DE-993E-A850BFD67A33/20191228143226

### Expected behavior
Works fine when ran `docker-compose pull` or `docker-compose up`

### Actual behavior
The error above is shown.

### Information
  - Is it reproducible? 
Yes, in my case is just install docker for windows.
  - Is the problem new? 
No, many we can find many questions about this on internet. I tried, but didn't find some solution that works.
https://github.com/docker/for-win/issues/611
https://github.com/docker/kitematic/issues/2956
https://stackoverflow.com/questions/48056365/error-get-https-registry-1-docker-io-v2-net-http-request-canceled-while-b

  - Did the problem appear with an update? 
No, I downgrade from 2.1.* to 2.0.* and does not work.
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

### docker-compose.yaml

```
version: '3.4'
services:
    build:
      context: ./
      dockerfile: ./docker/auge_server/Dockerfile
    ports:
      - "9091:9091"
  envoy:
    build:
      context: ./
      dockerfile:  ./docker/envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8440:8440"
      - "8443:8443"
    links:
      - auge-server
```

### Dockerfile (auge_server)

```
FROM google/dart:2.7.0

COPY certificate/cert.pem /etc/auge_server/certificate/cert.pem
COPY certificate/privkey.pem /etc/auge_server/certificate/privkey.pem

COPY config/configuration.yaml /etc/auge_server/config/configuration.yaml
COPY bin/auge_server.dart.snapshot /etc/auge_server/bin/auge_server.dart.snapshot

EXPOSE 9091
WORKDIR "/etc/auge_server/"
CMD /usr/bin/dart bin/auge_server.dart.snapshot
```

### Dockerfile (envoy)

```
FROM envoyproxy/envoy:latest

COPY certificate/cert.pem /etc/auge_server/certificate/cert.pem
COPY certificate/privkey.pem /etc/auge_server/certificate/privkey.pem
COPY envoy/envoy.yaml /etc/envoy/envoy.yaml

CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
```

  - Windows Version: 10.0.19536.1000
  - Docker Desktop Version: 19.03.5, build 633a0ea
  - No proxy behind network. 
  - Are you running inside a virtualized Windows. I tried Hyper-V with Windows Container, but switch to Linux Container too. 

### Steps to reproduce the behavior
  1. Tried set DNS 8.8.8.8 on Docker > Settings > Network > DNS > Fixed: 8.8.8.8
  2. Tried set DNS 8.8.8.8 (preference) 8.8.4.4 (alternative) on Control Painel / Network and Internet / Connections / vEtherner(DockerNAT) / DNS
  3. Tried login to hub.docker

But nothing works.
