### ISSUE TITLE
Kubernetes Pods with HostPort set cannot be reached on HostIP:HostPort

### ISSUE THREAD

**Issue by TBBle** [docker/for-win#5406]
- [x] I have tried with the latest version of my channel ([Stable](https://docs.docker.com/docker-for-windows/release-notes/) ~or Edge~)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

A Kubernetes Pod with a HostPort port should be reachable by HostIP:HostPort.

### Actual behavior

The HostIP for the Pod is the InternalIP of the `docker-desktop` Kubernetes node. The node resource doesn't *have* an ExternalIP listed.

Unlike the Services using LoadBalancer, the port is apparently not opened on localhost either (testing the UDP Port with ncat). So it's not as simple as adding localhost as the ExternalIP of the k8s Node.

### Information

I'm not certain I've ever successfully connected to a game server under Agones on Docker Desktop, so I suspect the problem has always existed. We only *noticed* it in early December 2019 when another user hit the issue, and I only now put the time in to rule out configuration issues or Agones issues.

So I have no reason to believe this problem has not always been present in the k8s setup in Docker Desktop.

  - Windows Version: Windows 10 Enterprise 19.09 Build 18363.418.
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

The use-case I'm hitting it with is [Agones](https://agones.dev/), which manages individual pods using HostPort, and then expects them to be visible to the outside world on [{_ExternalIP of Node falling back to InternalIP of Node_}](https://github.com/googleforgames/agones/blob/release-1.2.0/pkg/gameservers/controller.go#L866):{_HostPort_}.

Agones reports the IP address of the game server as some unroutable internal (192.168) IP address, not in a subnet known to my machine, which only has 10.x routes visible, both for the corporate LAN and the IPs used by Kubernetes internally. I assume this IP is internal to the VM, it's distinct from the ClusterIP addresses of the pods.

Here's a simple reproduction case. It uses TCP rather than UDP, but shows the same issue.

```yaml
# http://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/
# https://github.com/venilnoronha/tcp-echo-server
apiVersion: v1
kind: Pod
metadata:
  name: tcp-echo-server
spec:
  containers:
    - name: tcp-echo-server
      image: venilnoronha/tcp-echo-server:latest
      ports:
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
```

Apply the above with `kubectl apply`, and then run the following to see the incorrect hostIP:
```
kubectl get pods/tcp-echo-server -o jsonpath="{.status.hostIP}{':'}{.spec.containers[0].ports[0].hostPort}/{.spec.containers[0].ports[0].protocol}"
```
