### ISSUE TITLE
Volumes inside my application are not mounted

### ISSUE THREAD

**Issue by galdp** [docker/for-win#5539]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1427FDD5-2A1A-4624-826C-A1C699EE60F8/20200122133101

### Expected behavior

That volumes are mounted as configured in docker-compose.yml

### Actual behavior

Volumes are not mounted.

### Information
  - Windows Version: Version	10.0.18363 Build 18363
  - Docker Desktop Version: 2.2.0.0 (42247)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

We use in out local dev environment volumes  to optimise performace and manly to avoid conflicts of symlinks (between volumes) and other linux specific behaviours to interact with the windows filesystem.

Apps are based on Symfony or an Typo3.

After upgrade to new 2.2.0.0 Version our system not working anymore. Volumes are not mounted.

### Steps to reproduce the behavior

```
version: "3"
services:
  containerXY:
    image: XY
    volumes:
      - ../app:/var/app
      - storage:/var/app/storage
      - vendor:/var/app/vendor

volumes:
  storage:
  vendor:
```
