### ISSUE TITLE
Docker Desktop Windows 2.2.0.0 breaks "nested" volume mounting

### ISSUE THREAD

**Issue by jk12559** [docker/for-win#5540]
Volumes mounted in a container which are inside a folder which is also a volume mount no longer have their content in the container.  See the reproduction steps below for an example.

###### Test Project Structure

* inner/
    * inner-file.txt (empty dummy file)
* outer/
    * outer-file.txt (empty dummy file)
* docker-compose.yml (see content)

###### docker-compose.yml
``` yml
version: "3.7"
services:
  centos:
    container_name: nested_mount_test
    image: centos
    command: sleep 10m
    volumes:
      - ./outer:/test
      - ./inner:/test/inner
```

1.	In the folder with docker-compose.yml file, run docker-compose up –d
2.	Run docker exec -it nested_mount_test /bin/bash
3.	Run cd /test and verify that there is a file called outer-file.txt and a folder called inner inside /test
4.	Observe the content of /test/inner

### Expected behavior
When observing the content of /test/inner, it should container inner-file.txt

### Actual behavior
When observing the content of /test/inner, it is empty

### Information
In Docker Desktop 2.1.0.4, this works as expected, but after upgrading to Docker Desktop 2.2.0.0, the volume mounted inside another volume has no content.

  - Windows Version: Windows 10 Version 1809
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by stephen-turner** [comment]
Thanks for the report. We have code that is supposed to handle this in 2.2.0.0, but maybe it's not fully working. Could you please supply a diagnostics file so that we can look into your logfiles?

**Comment by issacg** [comment]
#metoo

**Comment by issacg** [comment]
Unsure if this is related, but I'm getting a similar problem when trying to share a mount in a nested docker (using the host daemon)

Example:
1. On a directory in the host, create a file HOST.txt
2. `docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock:ro -v %CD%:/data1 alpine sh`
3. 
```
/ # ls -al /data1
total 4
drwxrwxrwx    1 root     root             0 Jan 22 16:22 .
drwxr-xr-x    1 root     root          4096 Jan 22 16:24 ..
-rwxr-xr-x    1 root     root             0 Jan 22 16:22 HOST.txt
/ #
```
4. `# apk add docker-cli`
5.
```
/ # docker run --rm -ti -v /data1:/data2 alpine ls -al /data2
total 4
drwxr-xr-x    2 root     root            40 Jan 22 16:26 .
drwxr-xr-x    1 root     root          4096 Jan 22 16:26 ..
/ #
```

**Comment by houldsg** [comment]
We use this in all our node apps along with multi-stage builds for development, to keep the "node_modules" folder in the container and the source code on the host.

Dockerfile
```Dockerfile
FROM node:10-alpine AS dev-stage
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -g npm@latest && npm install --no-audit

FROM dev-stage as testing-stage
COPY . /usr/src/app
```

docker-compose.yml
```yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-stage
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
```

**Comment by cjancsar** [comment]
@houldsg Is the workflow you shared no longer working in 2.2? Or why did you share?

**Comment by houldsg** [comment]
@cjancsar Correct. The workflow is broken with 2.2.
It's the same "nested" volume mounting pattern except it's:
1. container (/)
2. host (/usr/src/app)
3. container again (/usr/src/app/node_modules)

**Comment by liayn** [comment]
From our POV this is a major blocker. Virtually all our projects use this feature.
Our usecase (simplified):

- ./html:/var/www/html
- 'path to some plugin':/var/www/html/plugins/pluginname/

**Comment by cjancsar** [comment]
@houldsg thanks, I think we are also experiencing that.

**Comment by zac-farrugia** [comment]
Also experiencing the same issue.

**Comment by dealer-solutions-gene** [comment]
What I found is the "child" volume would be created as an empty folder in the "parent" folder.

**Comment by dlford** [comment]
I'm seeing the same issue, same use case as @houldsg. I've had to downgrade to get some work done, but I did run diagnostics before doing so.

Diag ID: `7DB0481A-38FB-4150-A1C5-F752730ED428/20200123133355`

The volumes are created and populated (`node_modules`), I can mount the volumes in a new container and see the contents, but they don't work nested under the bind mounted project root folder.

Here is one configuration for reference:

`docker-compose.yml`

```yaml
version: '3.7'

  client_dev:
    volumes:
      - type: volume
        source: client-node_modules_dev
        target: /home/nextjs/app/node_modules
      - type: volume
        source: client-cache_dev
        target: /home/nextjs/app/.next
      - type: bind
        source: ./client
        target: /home/nextjs/app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    networks:
      net1:
        aliases:
          - client

networks:
  net1:
    name: project-name
volumes:
  client-node_modules_dev:
  client-cache_dev:
```

`Dockerfile`

```docker
FROM node:10-alpine

RUN mkdir -p /home/nextjs/app
WORKDIR /home/nextjs/app
COPY ./package*.json ./
RUN npm install

ENV NODE_ENV=development

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
HEALTHCHECK --start-period=15s --interval=1m --timeout=5s CMD ["node", "healthcheck"]
```
