### ISSUE TITLE
Volume doesn't sync when you delete a folder in Windows

### ISSUE THREAD

**Issue by coolfarmer** [docker/for-win#5550]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F038DED9-684B-479E-98A8-29477AD4CF30/20200122183814

### Expected behavior
Sync should work, if I delete a folder in Windows, ls -lsa should show me the correct result.

### Actual behavior
Actually I have the problem when phpfpm and nginx exist in my docker-compose. If I only have the service who run my symfony the sync will work.

### Information
  - Is it reproducible? Yes, every time
  - Is the problem new? Yes, only with 2.2.0.0
  - Did the problem appear with an update? Yes, 2.2.0.0
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: Windows 10 Version 1903 Build 18362.592
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Create a simple docker-compose file like this:
```
version: '2'

services:
  bitnami3:
    image: 'bitnami/symfony:1'
    volumes:
      - '.:/app'
    environment:
      - TZ=America/New_York
      - SYMFONY_PROJECT_NAME=bitnami3
    depends_on:
      - nginx
    networks:
      - default
  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '8784:8080'
    networks:
      - default
    depends_on:
      - phpfpm
    volumes:
      - '.:/app'
      - './bitnami3.conf:/opt/bitnami/nginx/conf/server_blocks/bitnami3.conf'
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - default
    volumes:
      - '.:/app'

networks:
  default:
    driver: bridge
```

  2. Create at the same level an Nginx conf file "**bitnami3.conf**"
```
server {
    server_name localhost;
    root /app/bitnami3/public;
    listen 0.0.0.0:8080;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
		fastcgi_pass phpfpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
```

  3. Run docker-compose up -d
  4. Normally you should access the demo page of symfony at localhost:8784
  5. In your project directory, go to /var/cache/ and delete the folder "dev"
  6. Refresh the web browser to recreate the cache folder
  7. Delete again the folder dev in /var/cache
  8. Open the container with docker exec -ti {ID} /bin/bash
  9. Go to /app/bitnami2/var/cache then run ls -lsa
10. The folder "dev" is not there, run now "mkdir dev"
       - _mkdir: cannot create directory 'dev': File exists_

11. This result that symfony can't recreate the cache folder and if your refresh your browser this time you will have: 
`Warning: file_put_contents(/app/bitnami2/var/cache/dev/App_KernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory`

I don't know why that happen only with php-fpm and nginx. If I remove them and ONLY have a service with symfony, I can delete the cache folder as many time I want and every refresh Symfony will success to recreate the cache folder.

My english is not the best i'm sorry for that.
If more information is needed I'll keep an eye on this issue.
