### ISSUE TITLE
volume mount in docker compose. Is this a bug?

### ISSUE THREAD

**Issue by jskorlol** [docker/for-win#5592]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I do a volume mount, but with override, in the case of var/www/storage/app/public/images a new mount must be attached.

       -../../backend:/var/www
       -../../images:/var/www/storage/app/public/images

### Actual behavior

However, the problem I'm experiencing doesn't happen with nginx,
It is happening in php7.4-fpm.
In other words, nginx normally mounts on two paths,
php7.4-fpm does not mount image volume

Is this a bug?
It worked fine before the update.
But I think it happened after the update, but I'm not exactly sure.

### Information

  - Windows Version: Windows 10 1809 (17763.973)
  - Docker Desktop Version: 2.2.0.0 (42247)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, Run Windows

### Steps to reproduce the behavior

```
  ### NGINX Server #########################################
  nginx:
    image: nginx:alpine
    restart: always
    labels:
      traefik.enable: true
      traefik.docker.network: "frontend"
      traefik.http.routers.jimg-nginx.entrypoints: "web"
      traefik.http.routers.jimg-nginx.rule: "Host(`jimg.localhost`)"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../backend:/var/www
      - ../../images:/var/www/storage/app/public/images
    networks:
      frontend:
        aliases:
          - jimg.localhost

  ### Laravel API Server #########################################
  php-fpm:
    # A container that exposes an API to show its IP address
    image: jimg-php7.4-fpm
    build:
      context: php7.4-fpm/
      dockerfile: Dockerfile
    labels:
      traefik.enable: false
    volumes:
      - ../../backend:/var/www
      - ../../images:/var/www/storage/app/public/images
    networks:
      - frontend
      - backend
```
![img](https://i.imgur.com/CTGLLzT.png)
