### ISSUE TITLE
Unable to share data between encrypted volumes

### ISSUE THREAD

**Issue by ReactiioN1337** [docker/for-win#5725]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `CBEA0BA8-9AA9-4C60-947B-02DB33039EDA/20200210104617`

### Expected behavior
Docker engine should be able to share my volumes.

### Actual behavior
Docker is not able to use any of my encrypted volumes as shared volume.

### Information

  - Windows Version: Windows 10 1909 (19H2) Build 18363.592
  - Docker Desktop Version: 2.2.0.0 (42247) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**

### Steps to reproduce the behavior

> I don't have windows defender or any firewall enabled. 

  1. Download [VeraCrypt](https://www.veracrypt.fr/en/Home.html).
  2. Encrypt one volume completely OR create a new encrypted container (2GB should be enough).
  3. Mount the encrypted volume/container as a new volume (I used W:\ as drive letter).
  4. Create a simple `docker-compose.yml` file and try to start the container using `docker-compose up` (you can also try with `-d` => same result).

```yaml
version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: gM3Lc5wpLPenn6ga
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data:/var/lib/rabbitmq
```
   5. Confirm the notification about sharing access to this drive.
![image](https://user-images.githubusercontent.com/2386884/74219297-ba2fc480-4cac-11ea-80a0-136a141f0b24.png)

   6. Docker throwed an unhanled exception "drive sharing failed for an unknown reason"

```bash
$ docker-compose up -d
Creating rabbitmq ... error

ERROR: for rabbitmq  Cannot create container for service rabbitmq: status code not OK but 500: {"Message":"Unhandled exception: Drive sharing failed for an unknown reason"}

ERROR: for rabbitmq  Cannot create container for service rabbitmq: status code not OK but 500: {"Message":"Unhandled exception: Drive sharing failed for an unknown reason"}
ERROR: Encountered errors while bringing up the project.
```
