### ISSUE TITLE
Host name resolution doesn't work with windows containers

### ISSUE THREAD

**Issue by pagdot** [docker/for-win#5758]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4F226D24-1691-4562-BBFF-7063BE736E2F/20200214092839

Hostname resolution between windows containers in the same network (nat driver) aren't able to ping each other using the container name. It seems like the dns service of docker (or windows/hyper-v) doesn't work.

It works when using Linux containers. My host pc is connected to a company network with configured dns suffix.

### Expected behavior

Hostname resolution works

### Actual behavior

```
Ping request could not find host "test1". Please check the name and try again. 
```

### Information
  - Windows Version: 1809
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

docker-compose.yaml
```
version: "3.7"
services:
   test1:
      image: mcr.microsoft.com/windows/nanoserver:1809
      container_name: test1
      entrypoint: cmd /c "echo Ready && ping localhost -t >nul"
      networks:
         - default

   test2:
      image: mcr.microsoft.com/windows/servercore:1809
      container_name: test2
      entrypoint: cmd /c "ping localhost -n 5 >nul && echo === Starting nslookup... === && nslookup test1 && echo. && echo === Starting ping === && ping test1"
      networks:
         - default

networks:
   default:
      driver: nat
```

  1. docker-compose up

My output:

```
test1    | Ready
test2    | === Starting nslookup... ===
test2    | *** Request to UnKnown timed-out
test2    | DNS request timed out.
test2    |     timeout was 2 seconds.
test2    | Server:  UnKnown
test2    | Address:  172.18.48.1
test2    |
test2    | DNS request timed out.
test2    |     timeout was 2 seconds.
test2    | DNS request timed out.
test2    |     timeout was 2 seconds.
test2    |
test2    | === Starting ping ===
test2    | Ping request could not find host test1. Please check the name and try again.
test2 exited with code 1
```

EDIT: Extended description and sample, added diagnostics ID
