### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by STaRDoGG** [docker/for-win#5763]
As requested, I'm creating another issue for this error.

Some relevant links that go even more in depth on it, in previous posts (in mo particular order):

- https://github.com/docker/for-win/issues/5516#issuecomment-585678903
- https://github.com/docker/for-win/issues/5516#issuecomment-583306444
- https://github.com/docker/for-win/issues/5516#issuecomment-583275033
- https://github.com/phpmyadmin/docker/issues/267

An additional aside:
In the above link I mention/show that the `docker run php:apache` container is one of them that also gives this error; it seems after the latest Docker update, it no longer does; however, the `docker run wordpress:apache` _does_ still give the same overlay error.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - **Diagnostics ID:** 2ECBE1F4-ADE2-4D97-8082-505598CFAE53/20200213120818

### Expected behavior

No overlay error while trying to create certain containers. (Apparently not happening to all containers, as I can run many others, though I haven't picked out a pattern yet).

### Actual behavior

Getting an overlay error.

### Information
 See below
  - Windows Version: See below
  - Docker Desktop Version: See below
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: It's running in Docker Desktop (Hyper-V)

Unfortunately for me, I still have the same issue with an overlay error (which I don't really understand).

**I just installed:**

![image](https://user-images.githubusercontent.com/1524526/74428958-a5c00900-4e1f-11ea-9652-f28acf54ee5a.png)

**Using this Compose (I left out the MySQL service, to focus on the problem container):**

```
version: '2'

services:

  phpmyadmin:
    container_name: phpmyadmin
    image: 'phpmyadmin/phpmyadmin:latest'
    restart: unless-stopped
    environment:
      - TZ='America/Chicago'
      - "PMA_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=RlL1#2Z%^W"
      - "PMA_ABSOLUTE_URI=https://my.domain.rocks:3112/phpmyadmin/"
    volumes:
      - "/f/Sites/Web/.config/PHPMyAdmin/Files:/Files:rw,shared"    
      - "/f/Sites/Web/.config/PHPMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
      - "/f/Sites/Web/.config/PHPMyAdmin/apache2.conf:/etc/apache2/apache2.conf"
      - "/f/Sites/Web/.config/PHPMyAdmin/Themes/:/var/www/html/themes/"
    depends_on:
      - mysql
    networks:
      - odb

networks:
  odb:
    external:
      name: my-db
```

Gives me this error (which is the same is the previous Docker Edge version):

> {"message":"Status: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/a54d40ac5df89eb2c2c9737db85772fe5782ea47c693ceba2eb1889ec2d7f25e/merged: too many levels of symbolic links, Code: 1","details":"Status: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/a54d40ac5df89eb2c2c9737db85772fe5782ea47c693ceba2eb1889ec2d7f25e/merged: too many levels of symbolic links, Code: 1"}

For what it might also be worth, since I don't know if the 2 are related in any way, but I'm just throwing it out there, I also get this error when trying to create an Adminer container, and mount a local CSS file to the container:

> {"message":"Error response from daemon: error while creating mount source path '/c/Servers/Docker/Containers/Adminer/pepa-linha-dark/adminer.css': mkdir /c/Servers/Docker/Containers/Adminer/pepa-linha-dark/adminer.css: file exists","details":"Error response from daemon: error while creating mount source path '/c/Servers/Docker/Containers/Adminer/pepa-linha-dark/adminer.css': mkdir /c/Servers/Docker/Containers/Adminer/pepa-linha-dark/adminer.css: file exists"}

I'm running on Win 10 x64 (Version 10.0.18363.657])
