### ISSUE TITLE
Containers doesn't start automatically after docker restart

### ISSUE THREAD

**Issue by Nitro-N** [docker/for-win#610]
### Expected behavior
Containers with restart policy "always" or "unless-stopped" should start with docker daemon automatically.
### Actual behavior
Only some containers do it. 
### Information

  - 020FB3EF-7A80-44E4-859C-F154744311E4/2017-03-29_18-36-06
  - Version 17.03.0-ce-win1 (10381)
    Channel: stable
    1d7d97b
  - Windows 10 Pro x64

### Steps to reproduce the behavior

  1. `docker-compose up -d` with this config v1
``` 
nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
```
  2. Quit Docker 
  3. Start Docker
  4. `docker ps` -> container is exited

**Comment by friism** [comment]
@Nitro-N did you check the logs for the excited container?

**Comment by Nitro-N** [comment]
@friism yes, It's ok then exited: no any errors

**Comment by nphmuller** [comment]
Having the same issue.

1. Use to following yml file:
```
version: '3.3'

services:
  redis:
    container_name: "my_redis"
    image: "redis:3.2.4"
    restart: always
    ports:
      - 6379:6379
```
2. `docker-compose up -d`
3. Restart windows (With quickboot disabled in Power Settings!)
4. After reboot run `docker ps -a`
Output:
```
CONTAINER ID        IMAGE        COMMAND                  CREATED             STATUS                       PORTS                              NAMES
a666ec895987        redis:3.2.4  "docker-entrypoint.s…"   About an hour ago   Exited (255) 6 minutes ago   0.0.0.0:6379->6379/tcp             my_redis
```
The exited (255) x minutes ago time should be the time after Windows restart.

Version info:
```
Client:
 Version:      17.11.0-ce-rc3
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   5b4af4f
 Built:        Wed Nov  8 03:03:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce-rc3
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   5b4af4f
 Built:        Wed Nov  8 03:09:46 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
