### ISSUE TITLE
[Hyper-V/WSL2] Swarm - service limiting RAM way below service limit itself

### ISSUE THREAD

**Issue by GameBurrow** [docker/for-win#6157]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `24FB8068-79F2-4343-80D7-28840F37823A/20200329123951`

### Expected behavior
I have a mariadb container set up in swarm with RAM limit 10GB. In `my.cnf`, I have specified limit:
```
innodb-buffer-pool-size		= 8000M
```
In linux docker swarm, when I start importing big databases (> 8GB), container memory usage does increase to 8GB slowly and import succeeds after some time.

### Actual behavior
With docker for windows. In both swarm and non-swarm mode. The exact same configuration, the exact same dump imports, mariadb container memory usage caps on ~350MB (with Hyper-V backend) and on ~450MB (with WSL2 backend) and import fails at one point with some memory related error.
![image](https://user-images.githubusercontent.com/4341091/77848674-11431780-71cf-11ea-92f6-de83c73965f9.png)

Windows host does have enough memory. Tested on 2 different windows hosts (first one has in total 32GB of RAM, other host has less memory, so limits were brought down but it still caps at same points

### Information
  - **Is it reproducible?** Every single time I try
  - **Is the problem new?** Haven't tried before

  - **Windows Version:** First I reproduced it in latest stable 1904, Win 10 Pro x64
Then I tried to upgrade to Insider Slow ring 2004 Build 19041.172 to try if same happens with WSL2 version of docker.

  - **Docker Desktop Version:**
Stable 2.2.0.4 In HyperV mode
Stable 2.2.0.4 in WSL2 mode
Edge 2.2.2.0 in WSL2 mode
  - **Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:**
No

### Steps to reproduce the behavior
1. Build the following image:
[pw-database.zip](https://github.com/docker/for-win/files/4398836/pw-database.zip)
2. Run it in docker swarm with following limits:
```yaml
  db:
    image: "pw-database:latest"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 10000M
        reservations:
          cpus: "0.5"
          memory: 1000M
    volumes:
      - "../../mariadb:/var/lib/mysql"
      #- "starlight-mariadb:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - internal_network
```
