### ISSUE TITLE
Upgraded to 2.3.2.0, broke file binding. Can't start containers now. arrrgh

### ISSUE THREAD

**Issue by YouveGotMeowxy** [docker/for-win#6285]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2ECBE1F4-ADE2-4D97-8082-505598CFAE53/20200409214858

### Expected behavior

I'm able to mount the files.

I was on the last version before updating to 2230 and it would mount the files (config files). After updating, I get the errors in the screenshots below.

### Actual behavior

I'm not able to mount the files.

![image](https://user-images.githubusercontent.com/39491297/78943589-c7d1b280-7a81-11ea-850e-66c7050dfffe.png)

![image](https://user-images.githubusercontent.com/39491297/78943604-d0c28400-7a81-11ea-8175-e4a192ac83be.png)

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

![image](https://user-images.githubusercontent.com/39491297/78943516-a375d600-7a81-11ea-8ebd-0508ffae6c51.png)

**Comment by YouveGotMeowxy** [comment]
... literally the worst support on the planet. Especially for such a popular product.

**Comment by mat007** [comment]
Thanks for the report, and very sorry we couldn’t reply sooner to provide you support for this free product.

This may be similar to #6209? It’s hard to tell without a bit of information in the «Steps to reproduce the behavior» field of the issue.
Can you tell us the command line you’re using or how you mount your folders?

**Comment by YouveGotMeowxy** [comment]
@mat007 Hi, sorry for sounding so frustrated, I know it's a free products, but I've come to depend on it and have spend countless hours now getting all these little tweaks and containers and settings going it gets frustrating when an update takes it down, and then no matter where I go for some assistance I just get crickets, and then just hope and pray that a new release that is who knows how far away will fix it.

**Here's the compose I use that contains the DNSCrypt Proxy error:**

```
version: "3"

services:

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: "redacted"
      ServerIP: "192.168.1.188"
      VIRTUAL_HOST: "192.168.1.188"
      IPv6: "false"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
    volumes:
       - 'pihole_data:/etc/pihole/'
       - 'pihole_dnsmasq_data:/etc/dnsmasq.d/'
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    cap_add:
      - NET_ADMIN
    networks:
      - pihole
    restart: unless-stopped

  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    hostname: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    environment:
      TZ: 'America/Chicago'
    volumes:
      - '/f/Sites/DNSCrypt/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
    ports:
      - '5252:5053/udp'
    networks:
      - pihole
    restart: unless-stopped

volumes:
  pihole_data:
    external: true
  pihole_dnsmasq_data:
    external: true

networks:
  pihole:
    external:
      name: my-dns
```

**and for the compose that contains the MySQL error:**

```
version: '2'

services:

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      - TZ='America/Chicago'
      - MYSQL_ROOT_PASSWORD="redacted"
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - '/i/MySQL/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '3306:3306'
    command: "--default_authentication_plugin=mysql_native_password"
    networks:
      - odb

volumes:
  mysql_data:
    external: true

networks:
  odb:
    external:
      name: my-db
```
