### ISSUE TITLE
how to access access container without mapping ports on windows  

### ISSUE THREAD

**Issue by mygoodboy** [docker/for-win#6291]
docker : 2.2.0.3(12716)
windows 10: 1909
docker setting :
   docker subnet: 192.168.65.0/28
   hyper-V subnet: 10.0.75.0/28
vEthernet (Default Switch):172.17.135.209
myIP:192.168.10.99

Hyper-V defaul switch:  can't set 
    ps預設網路交換器使用NAT(網路位址轉譯)自動將電腦網路的存取權提供給虛擬機器

docker-compose.yml
```
version: '2.4'
networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
services:
  smb:
    container_name: smb
    image: phpmyadmin/phpmyadmin

    ports:
      - "8080:80/tcp"
    tty: true
    volumes:
      - D:\docker\disk:/mnt:z
    networks:
      vpn:
        ipv4_address: 172.25.0.2
```
docker network inspect smb_vpn
``` 
[
    {
        "Name": "smb_vpn",
        "Id": "9b9edb6e3e6bf5b6bac9960857e76308d3f579dbd76a5c4fe890e035878da3bb",
        "Created": "2020-04-10T17:09:28.814031222Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.25.0.0/16",
                    "Gateway": "172.25.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "c7c96a17f5d5c0c8be83aa2f095ce4b7a95631698b0c519bda3f37128b04a8eb": {
                "Name": "smb1",
                "EndpointID": "9d89cc2427a3c7ce9d198c130f01ab63bc8038ffb0864e5c0edd9ff6bc1309f9",
                "MacAddress": "02:42:ac:19:00:02",
                "IPv4Address": "172.25.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "vpn",
            "com.docker.compose.project": "smb",
            "com.docker.compose.version": "1.25.4"
        }
    }
]
```

I can access to  127.0.0.1:8080 but fail to 172.25.0.2
$route add 172.0.0.0/16 mask 255.0.0.0 172.25.0.1  -p  > still fail to 172.25.0.2
sombody said : not bridge on windows (whether it's able to connect by IP or not ?)

office example still fail to 172.16.238.10
```
version: "3.7"

services:
  app:
    image: phpmyadmin/phpmyadmin
    networks:
      app_net:
        ipv4_address: 172.16.238.10

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
```
update:
mac and windows can't access to container through bridge
if so , why container can use internet with computer but not access to container from computer
