### ISSUE TITLE
Add NFS Utils to the VM image

### ISSUE THREAD

**Issue by trajano** [docker/for-win#6336]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When I built my own Docker VM using VirtualBox I was able to use this volume definition.

```
volumes:
  elasticsearch-data:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.1,rw"
      device: ":/mnt/sda1/xyz
```

### Actual behavior

Service fails.  I have tried to do `docker volume create` and it also fails with permission denied.

### Information

  - Windows Version: Windows 10 v 1909
  - Docker Desktop Version: 2.2.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. What I did was try to access the DockerVM using the [@brettfisher technique](https://www.bretfisher.com/getting-a-shell-in-the-docker-for-windows-vm/)

    docker run -it --rm --privileged --pid=host justincormack/nsenter1

2. Then I confirmed that in /sbin/ there was no `mount.nfs` which does explain why I cannot mount.  As such I was asking if the nfs-utils can be installed in the VM by default so we'd have the same capability in most UNIX machines.
