### ISSUE TITLE
Docker Copy Not working

### ISSUE THREAD

**Issue by Fosol** [docker/for-win#6505]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 059FF108-F0DE-4206-BEB3-8E9E4F971B51/20200430042742

### Expected behavior
docker-compose should copy files to container.  It is working for all my co-workers.  I have the exact same branch as they do.

This was a slow progression to issues.  I was finding more and more often that my frontend container was having issues.  Sometimes I'd just remove the volume and it would work again.  Other times I had to restart Docker Desktop.  Now nothing works.  It refuses to let my frontend work.  Oddly enough all my other containers continue to work fine.  I've double/triple checked that my files are identical to other team members.  

### Actual behavior
Source files are not being copied to the container.

### Information

  - Windows Version: Latest 10.0.18363
  - Docker Desktop Version: Latest 2.2.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
  1. Create React App (using Typescript) here `/frontend`
  2. Source here `/frontend/src`
  3. `docker-compose` here `/docker-compose.yml`
  4. `Dockerfile` here `/frontend/Dockerfile`

docker-compose.yml
```yml
version: "3.5"

services:
  ####################### Frontend #######################
  frontend:
    stdin_open: true
    tty: true
    restart: on-failure
    container_name: frontend-app
    build:
      context: frontend
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
      - frontend-node-cache:/usr/app/node_modules
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    networks:
      - pims

####################### Networks Definition #######################
networks:
  pims:
    name: pims-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  frontend-node-cache:
```

Dockerfile
- Please note that I've commented out the `npm start` so that I can bash into the container to look at the files.
```
FROM node:10-slim as node

# install build toolchain (for node-gyp)
RUN apt-get update \
  && apt-get install --no-install-recommends -y dumb-init python build-essential \
  && rm -rf /var/lib/apt/lists/*

# set entrypoint to `dumb-init` as it handles being pid 1 and forwarding signals
# so that you dont need to bake that logic into your node app
ENTRYPOINT ["dumb-init", "--"]

WORKDIR /usr/app

# install a specific NPM version
RUN npm install -g npm@6.9.0

COPY package*.json ./

RUN npm set progress=false \
  && npm ci

COPY . .

# webpack-dev-server (3000)
EXPOSE 3000

# CMD ["npm", "start"]
CMD tail -f /dev/null
```
