### ISSUE TITLE
[WSL2] Docker swarm having issues with mount points

### ISSUE THREAD

**Issue by GameBurrow** [docker/for-win#6507]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `24FB8068-79F2-4343-80D7-28840F37823A/20200430065255`

### Expected behavior
When using Docker Swarm under WSL 2 on folders that are mounted from windows host, `/mnt/d/` etc, I expect them to work at all times.

### Actual behavior
There is an extremely high chance that from inital startup one of the mounts fails, with following error
![image](https://user-images.githubusercontent.com/4341091/80681210-dfbcb500-8ac8-11ea-86f2-75534f80115d.png)
Sometims this happens with single mount, sometimes with multiple. Sometimes one mount works for one container, but not on other etc. However once I get this error, I haven't found any stable bypassess. Sometimes restarting computer helps, sometimes restaring WSL & Docker helps. Sometimes restarting LxssManager service helps.

However all hell goes loose when I try to do docker swarm deploy & update on running service. Then all mounts fail with same error.
![image](https://user-images.githubusercontent.com/4341091/80682410-1dbad880-8acb-11ea-8a13-49c94de923d7.png)
I'm noticing in this case it uses raw mouts instead of docker-desktop-bind mounts as it does in first launch
This can be bypassed by bringing the entire stack down and then deploying again.

Same configuration can run with docker-compose just fine.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? No, has been there since I started using Docker for WSL
  - Did the problem appear with an update? With WSL2 update
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  - Windows Version: Win 10 Pro Version 2004 (Build 19041.208)
  - Docker Desktop Version: 2.2.1.0 - 2.3.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Set up docker swarm
  2. Use volume mounts from /mnt/c & /mnt/d etc folders

**Comment by GameBurrow** [comment]
After testing a bit, it looks like it's not a windows folder mount issue, when I moved the code to /folder-name (which is not a windows mount folder), issue still exists.

**Comment by simonferquel** [comment]
Hi, thanks for reporting this issue. I think I know where the root cause is, and should be able to work on a fix quickly.

**Comment by GameBurrow** [comment]
@simonferquel Let's hope thats the case. Today morning I lost 2 hours because of the first issue (only few mounts failing) because none of the restarts didn't seem to be working also ;)

**Comment by simonferquel** [comment]
I'll have a private build to share with you later today. We are not sure if we can slip the patch into the next update (which should happen soon) though.

**Comment by GameBurrow** [comment]
@simonferquel Now on first start 3 out of 6 mounts failed (including the mountpoint that is just docker volume, not mounted from host):
![image](https://user-images.githubusercontent.com/4341091/80727808-d81fff00-8b0e-11ea-9ebf-1c92f043d1f0.png)
and it keeps happening every time.

Yes, I restarted computer also to be sure. 

Diagnostic id:
24FB8068-79F2-4343-80D7-28840F37823A/20200430151627

**Comment by simonferquel** [comment]
Hmm from your logs, am I right to understand that /coding-projects is a symlink to /mnt/d/coding-projects ?
I think the bind mount manager is a bit confused because some dirs are mount from /coding-projects and others from /mnt/d/coding-projects.

**Comment by GameBurrow** [comment]
No, they are all mounting from `/mnt/d/coding-projects/arego/starlight`

My compose-file is located in `/mnt/d/coding-projects/arego/starlight/docker/docker-compose`
and here are the mounts I'm loading:

```
services:
  pw-rackgit:
    image: "pw-rackgit:latest"
    hostname: docker-local-rackgit
    volumes:
    - "../images/rackgit/src:/rackgit"
    - "../starlight-src:/starlight"

  pw-apache:
    image: pw-apache
    hostname: docker-local-apache
    volumes:
      - "../starlight-src:/starlight"
      - "../images/pw-apache/letsencrypt:/etc/letsencrypt/"

  pw-php:
    image: pw-php
    hostname: docker-local-php
    volumes:
      - "../starlight-src:/starlight"
      
  db:
    image: "pw-database:latest"
    hostname: docker-local-db
    volumes:
      #- "../../mariadb:/var/lib/mysql"
      - "starlight-mariadb:/var/lib/mysql"    

  redis:
    image: "pw-redis:latest"
    volumes:
      - "../../redis:/data"

volumes:
  starlight-mariadb:
```
