### ISSUE TITLE
Pod can not mount the host path using pv in kubernetes.

### ISSUE THREAD

**Issue by weiZhenkun** [docker/for-win#6671]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 60B82624-51FF-4179-8097-0909C0087D35/20200513035655

### Expected behavior
     There is a file named "test.txt" in my windows path: C:\cannot-found.
     In the version 2.2.0.5, it works fine.
### Actual behavior
     There is not a file named "test.txt" in my windows path: C:\cannot-found.
### Information

  - Windows Version: Win10 Enterprise 1803 (OS 17134.1425)
  - Docker Desktop Version: Docker Desktop Community 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. update the docker desktop to the version :  Community 2.3.0.2.
2. enable the kubernetes in the docker desktop.
3. Execute the "kubectl create -f test.yaml", the content of the file is bellow:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: global-volume
  labels:
    pv_pvc_label: nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi  
  hostPath:
    path: "/c/cannot-found"
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: global-volume
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv_pvc_label: nfs
  volumeName: global-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: default
spec:
  selector:
    matchLabels:
      component: centos
      module: centos      
  replicas: 1
  template:
    metadata:
      labels:
        component: centos
        module: centos
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: global-volume
      containers:
      - image: centos
        command:
          - /bin/sh
          - "-c"
          - "touch /root/test.txt; echo \"test mount\">/root/test.txt; cp /root/test.txt /tmp/test.txt; sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        volumeMounts:
        - name: nfs
          mountPath: /tmp/
          subPath: mountPath
      restartPolicy: Always
```
4. pod event shows:
```
Events:
  Type     Reason     Age                   From                     Message
  ----     ------     ----                  ----                     -------
  Normal   Scheduled  <unknown>             default-scheduler        Successfully assigned default/alpine-7c7668ff4b-9z9zr to docker-desktop
  Warning  Failed     80s (x12 over 3m16s)  kubelet, docker-desktop  Error: stat /c/cannot-found: no such file or directory
  Normal   Pulled     68s (x13 over 3m16s)  kubelet, docker-desktop  Container image "centos" already present on machine
```
