### ISSUE TITLE
Volume mounts not working after upgrade

### ISSUE THREAD

**Issue by JoshKeegan** [docker/for-win#6680]
- [x] I have tried with the latest version of my channel (**Stable** or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E3E44565-D1FE-46AD-BE6F-6A274FE27BF1/20200513104402

### Information

  - Windows Version: Windows 10 v1909 (Build 18363.778)
  - Docker Desktop Version: 2.3.0.2 (45183) - latest stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

I had a container set to always restart before upgrading to the latest docker desktop that had volume mounts to my local windows Z:\ drive. It was docker-compose and here's the compose file:
```yaml
version: '3.5'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=True
      - SA_PASSWORD=redacted
    volumes:
      - mssqlData:/var/opt/mssql
      - mssqlBackups:/backups
    restart: always
    ports:
      - 1433:1433

volumes:
  mssqlData:
  mssqlBackups:
    driver_opts:
        type: none
        device: /z/Backups/SQL Server
        o: bind
```

It no longer starts and fails with the following error when I try and start it manually:
```bash
Starting mssql_mssql_1 ... error

ERROR: for mssql_mssql_1  Cannot start service mssql: error while mounting volume '/var/lib/docker/volumes/mssql_mssqlBackups/_data': failed to mount local volume: mount /z/Backups/SQL Server:/var/lib/docker/volumes/mssql_mssqlBackups/_data, flags: 0x1000: no such file or directory

ERROR: for mssql  Cannot start service mssql: error while mounting volume '/var/lib/docker/volumes/mssql_mssqlBackups/_data': failed to mount local volume: mount /z/Backups/SQL Server:/var/lib/docker/volumes/mssql_mssqlBackups/_data, flags: 0x1000: no such file or directory
Encountered errors while bringing up the project.
```

The Z:\ drive is still shared, and I have tried removing it, restarting docker & readding it to no avail:
![image](https://user-images.githubusercontent.com/1682204/81803708-fe329f80-950f-11ea-8948-dbba2c6cfed0.png)

When I try and mount the Z:\ drive to another container it appears to still work as expected though (e.g. via `docker run --rm -it -v Z:/:/z debian`).

### Steps to reproduce the behavior

I don't know as it was an existing container from before the upgrade.
The only odd behaviour I found when trying to reproduce was that mounting two drives at the same time failed, e.g. 
```ps
docker run --rm -it -v C:/:/c -v Z:/:z debian
```
errors with:
```ps
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: invalid volume specification: '/host_mnt/z:z'.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
```
Mounting either of the drives individually works as expected, and so does multiple mounts on the same drive.
