### ISSUE TITLE
Bind mount docker.sock with Windows container

### ISSUE THREAD

**Issue by masoudr** [docker/for-win#6813]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The service should set up without any problem.
### Actual behavior
I get this error:
```
ERROR: for webservice  Cannot create container for service webservice: invalid volume specification: '//var/run/docker.sock:/var/run/docker.sock:rw'
ERROR: Encountered errors while bringing up the project.
```
### Information

  - Windows Version: Win10 1909 X64
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I'm trying to mix Windows and Linux containers and as you might know, the latest version that it works properly is `2.2.0.3` (based on [this issue](https://github.com/microsoft/hcsshim/issues/813#issuecomment-621582287)). My problem is with the mounting `docker.sock` into Linux container which seems syntactically right. I tested this with Linux containers and I'm not sure about how to set when using Windows containers.

### Steps to reproduce the behavior

I set the `experimental` feature in my docker daemon and Windows container selected.
Here is my daemon config:
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true,
  "graph": "E:\\Docker"
}
```
Here is my sample `docker-compose.yml`:

```
version: '2.4'

services:
  webservice:
    platform: linux
    build:
      context: ./app/webservice
    ports:
      - "443:443"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./app/webservice:/app
```
And the Dockerfile:
```
FROM python:3.8
ENV PYTHONUNBUFFERED 1
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
RUN mkdir /app
RUN mkdir /build
COPY ./app /app
WORKDIR /app
```

**Comment by rirlswift** [comment]
Seeing a similar issue with a different use case.
start vscode remote: running container that has bind mounts to docker socket (run container from container). 
Windows: must use sudo
Linux: container (started by vscode) and my container shared the same docker group gid -- no sudo.

**Comment by rirlswift** [comment]
I think based on [here](https://docs.docker.com/docker-for-windows/faqs/#how-do-i-connect-to-the-remote-docker-engine-api) that these use cases require using a TCP socket (eg., must remote from local)

This might require TLS?

**Comment by masoudr** [comment]
@rirlswift Thanks for the info but how can I bind the TCP socket I mean I tried but I got this error:
```
version: '2.4'

services:
  webservice:
    platform: linux
    build:
      context: ./app/webservice
    ports:
      - "443:443"
    volumes:
      - type: npipe
        source: ////./pipe/docker_engine
        target: /var/run/docker.sock
        consistency: delegated
```
`ERROR: for webservice  Cannot create container for service webservice: invalid mount config for type "npipe": Linux containers on Windows do not support named pipe mounts`

Also the doc said it has a TCP like `tcp://localhost:2375` but how can I access this address in my `webservice` container?
