### ISSUE TITLE
Can't run php-xdebug in docker(WSL2)

### ISSUE THREAD

**Issue by slps970093** [docker/for-win#6993]
I tried to set up a PHP development environment in Docker in WSL 2 mode, and it does not work with Xdebug

**Comment by stephen-turner** [comment]
Could you please supply more details of what you did, what you expected, the symptoms, and include a diagnostics id. Thank you.

**Comment by slps970093** [comment]
I execute docker-compose
The yml format is as follows
```
version: '2.0'

services:
  buylive_redis:
    container_name: buylive_redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - buylive_network
    volumes:
      - D:\dockerToolbox\share\php\buylive\docker_compose\dev\php74\redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  buylive:
    build:
      context: images
      dockerfile: Dockerfile
    container_name: "buylive_dev_web"
    volumes:
      - D:\dockerToolbox\share\php\buylive\:/var/www/html
      - D:\dockerToolbox\share\php\buylive\docker_compose\dev\php74\php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    depends_on:
      - buylive_db
      - buylive_redis
    networks:
      - buylive_network
  buylive_db:
    container_name: "buylive_dev_db"
    image: "mysql:5.7"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "my2276"
    networks:
      - buylive_network
networks:
  buylive_network:
    driver: bridge

```
But he cannot execute XDEBUG normally

  - [V] I have tried with the latest version of my channel (Stable or Edge)
  - [V] I have uploaded Diagnostics
  - Diagnostics ID:B2037AE8-CCDF-4DF2-8421-F48231636A2A/20200602015137
