### ISSUE TITLE
Persistent volumes get lost in Kubernetes on Docker Desktop for Windows/WSL2

### ISSUE THREAD

**Issue by hbel** [docker/for-win#7023]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2FBDD8C2-1DBB-45C8-A4C8-1FC5E25BD030/20200602184256

### Expected behavior

1. When creating a new persistent volume and new persistent volume claim that gets used in a pod, I expect to find the contents created by the pod in the given file path.

2. Data stored in the persistent volume is still available after a reboot, since it should be stored in wsl2's file system.

### Actual behavior

1. I am not able to find the according path at all in my wsl2 file system.
2. All data stored in the persistent volume is lost.

### Information
  - Windows Version: Windows 10 Pro 2004
  - Docker Desktop Version: 2.3.03, running in WSL2
  - I could only test this on one machine because Kubernetes is not working on any other of my Windows machines yet.

1. Which part of the file system gets accessed by Kubernetes when running in WSL2
2. Where can I find my persistent volumes in the file systems (obviously there are not located under /var/k8s. BTW, there is also no /var/lib/docker as far as I can see)
3. Why are these volumes not persistent and get deleted when shutting down WSL2 or Windows?

### Steps to reproduce the behavior

**Create a persistent volume and claim**

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv-volume
  namespace: persistence
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/k8s/data/neo4j"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pv-claim
  namespace: persistence
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

**Ruin a deployment using the persistent volume claim**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: persistence
spec:
  selector:
    matchLabels:
      db: neo4j
  template:
    metadata:
      labels:
        db: neo4j
    spec:
      volumes:
        - name: neo4j-pv-storage
          persistentVolumeClaim:
            claimName: neo4j-pv-claim
      containers:
      - name: neo4j
        image: neo4j:4.0.4
        ports:
          - containerPort: 7474
          - containerPort: 7687
        volumeMounts:
          - mountPath: "/data"
            name: neo4j-pv-storage
        env:
          - name: NEO4J_AUTH
            value: neo4j/neo4j
```

**Comment by woshizhuyumi** [comment]
I had the similar issue with you, but it's a slight bit different, I was trying to mount as lostPath.
After some time on Google, I found this workaround works for me:
https://github.com/docker/for-win/issues/5325#issuecomment-632309842

**Comment by hbel** [comment]
Actually, it does help. Although this makes things unnecessary complicated for the developers (I  intended to provide them with a consistent deployment over all OS choices for their development systems), it helped to get that at least running under WSL2. One thing though, if storing the files in a cross-mounted directory not located on a windows drive, the mount seems to be a tmpfs - so if you really need persistent data, better not store it in a freshly created directory but on ```/run/desktop/mn/host/c``` or something similar.

**Comment by woshizhuyumi** [comment]
I totally agree. 
According to the 'best practice' of using WSL2, we should copy over our codebase to WSL to gain the best performance.
Given this issue and other difficulties I had so far with WSL2, I'm considering if I should go back to HyperV......

**Comment by zssng** [comment]
I have same issue. I mount host folder `/C/Users/xx/k8s/test` .But nothing shows under the folder 
Here is a test config.

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-volume
  labels:
    type: local
  namespace: test-storage
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/C/Users/xx/k8s/test" #host path to mount
    # type: Directory  # if uncomment this, get is not a directory error

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
  namespace: test-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: alpine
  labels:
    app: test-storage
  namespace: test-storage
spec:
  selector:
    matchLabels:
      app: test-storage
  template:
    metadata:
      labels:
        app: test-storage
    spec:
      containers:
      - image: alpine
        name: test-storage
        volumeMounts:
        - name: test-persistent-storage
          mountPath: /testdata
        command: ["/bin/sh"]
        args: ["-c", "echo aa > /testdata/11.txt && ls -s testdata && ls /mnt"]
      volumes:
      - name: test-persistent-storage
        persistentVolumeClaim:
          claimName: test-pv-claim

```

This is the output 


```
total 4
     4 11.txt
```
Host folder file not shown in the container mount path,and container directory file not shown in host path.


version: 2.3.0.3, older version (2.2.x) works fine.
