### ISSUE TITLE
ERROR: for selenium-hub  Cannot start service selenium-hub: error while creating mount source path '/dev/shm': mkdir /dev/shm: file exists ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by Freundschaft** [docker/for-win#7148]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DD0EFB0D-0E65-4472-829C-E8544D8B53AE/20200609212742

### Expected behavior

docker-compose up should start a container with selenium using /dev/shm

### Actual behavior

docker-compose up fails with the following error:

```
ERROR: for 8d7ac179454a_golden-tech-framework_selenium-hub_1  Cannot start service selenium-hub: error while creating mount source path '/dev/shm': mkdir /dev/shm: file exists

ERROR: for selenium-hub  Cannot start service selenium-hub: error while creating mount source path '/dev/shm': mkdir /dev/shm: file exists
ERROR: Encountered errors while bringing up the project.
```

### Information

  - Windows Version: 10 2004
  - Docker Desktop Version: 2.3.0.3 (45519) Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

this is my docker-compose.yml file, I am using Windows 10 2004 with WSL2

```
  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    environment:
      - GRID_TIMEOUT=30000
      - GRID_BROWSER_TIMEOUT=30000
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    env_file:
      - ./docker/db/.env
```
