### ISSUE TITLE
MSSQL 2019 Database Restore Fails

### ISSUE THREAD

**Issue by martyt** [docker/for-win#7259]
Attempting to restore a MSSQL database backup to a Docker MSSQL container fails in Docker Desktop 2.3.0.3 when using volumes mounted from the host filesystem. (I don't know if it fails using Docker volumes or not, as that's not how we use Docker.)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
D91F3F4C-3B2D-441C-8868-874FEDAAD817/20200615193850
### Expected behavior
MSSQL database restore should just work. 

In Docker Desktop 2.2.0.5, the restore script works exactly as expected -the new database and associated files are created, and the backup is restored. 

### Actual behavior
In Docker Desktop 2.3.0.3, I share the entire C: drive as before and run the same docker-compose to create the MSSQL container. 

When I execute the RESTORE script, however, I get multiple error messages that seem related to file access permissions:

```
Msg 3634, Level 16, State 1, Line 1
The operating system returned the error '2(The system cannot find the file specified.)' while attempting 'RestoreContainer::ValidateTargetForCreation' on '/var/opt/mssql/data/Authorization.mdf'.
Msg 3156, Level 16, State 5, Line 1
File 'Authorization' cannot be restored to '/var/opt/mssql/data/Authorization.mdf'. Use WITH MOVE to identify a valid location for the file.
Msg 3634, Level 16, State 1, Line 1
The operating system returned the error '2(The system cannot find the file specified.)' while attempting 'RestoreContainer::ValidateTargetForCreation' on '/var/opt/mssql/log/Authorization.ldf'.
Msg 3156, Level 16, State 5, Line 1
File 'Authorization_log' cannot be restored to '/var/opt/mssql/log/Authorization.ldf'. Use WITH MOVE to identify a valid location for the file.
Msg 3119, Level 16, State 1, Line 1
Problems were identified while planning for the RESTORE statement. Previous messages provide details.
Msg 3013, Level 16, State 1, Line 1
RESTORE DATABASE is terminating abnormally.
```

I found through experimentation that if I `touch /var/opt/mssql/data/Authorization.mdf` and `touch /var/opt/mssql/log/Authorization.ldf` and *then* run the restore script, it runs without errors in 2.3.0.3 

### Information

  - Windows Version: Win 10 Pro v1909
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
We use Docker Desktop in conjunction with volumes mounted from the host to quickly setup MSSQL on developer machines and provide a script to restore databases from a MSSQL backup of a "reference" copy of the database. 

We create several folders on the host machine and then mount them as volumes in the docker container. We share the entire C drive with Docker and use the following docker-compose file to create the database instance:

```
version: '3.4'

networks:
  default:
    external:
      name: dev_default

services:
  devsql:
    container_name: devsqltest
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    expose:
      - "1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Str0ngPassword!
    restart: unless-stopped
    volumes:
      - type: bind
        source: c:\devsqltest\data
        target: /var/opt/mssql/data
      - type: bind
        source: c:\devsqltest\log
        target: /var/opt/mssql/log 
      - type: bind
        source: c:\devsqltest\secrets
        target: /var/opt/mssql/secrets
      - type: bind
        source: c:\devsqltest\backup
        target: /var/opt/mssql/backup
      - type: bind
        source: c:\devsqltest\scripts
        target: /var/opt/mssql/scripts
```

We execute the database restore script from either the `sqlcmd` command line or from Microsoft SQL Server Management Studio, connecting to the database as `sa`. This is the restore script - nothing too wild at all:

```
RESTORE DATABASE [Authorization] 
FROM  
	DISK = N'/var/opt/mssql/backup/Authorization.bak' 
WITH  
	FILE = 1,  
	MOVE N'Authorization' TO N'/var/opt/mssql/data/Authorization.mdf',  
	MOVE N'Authorization_log' TO N'/var/opt/mssql/log/Authorization.ldf',  
	NOUNLOAD,  
	REPLACE,  
	STATS = 5
GO
```

**Comment by martyt** [comment]
Surprised there's no comment or acknowledgement of this bug. It's clearly a problem - I'm amazed nobody else has run into it yet. 

We've had to revert to 2.2.0.5 in order to keep working.

**Comment by Nuschler** [comment]
Me too, sounds like issue #6646 that was supposedly fixed. I still have the issue...
https://github.com/docker/for-win/issues/6646#issuecomment-637839727

**Comment by Nuschler** [comment]
What I have found is you can read from a volume but cannot write to a volume in Docker Desktop 2.3.x.x with MSSQL 2019. 

The user MSSQL runs as can only write to folders with permissions granted to mssql user, volumes are mounted as user root.

You can mount a volume as something like /var/opt/mssql/data_volume and restore database to /var/opt/mssql/data but you cannot backup a database back to /var/opt/mssql/data_volume

**Comment by kengranderson** [comment]
This article presents a workaround that worked for me.

https://www.sqlservercentral.com/blogs/using-volumes-in-sql-server-2019-non-root-containers

Use a Dockerfile and while composing the image, switch to root, change ownership to the mssql user, switch back to mssql.
I used this approach to restore 4 databases to 4 different volumes that I gave the mssql user access to in the Dockerfile and attached via docker run.  

Also changed data, stopped and started the container to confirm persistence.

**Comment by martyt** [comment]
Thanks @kengranderson for the link. Only works when using Docker volumes, not when using bind mounting to folders on the host -- no matter what I do, `chown mssql blah` doesn't do anything when `blah` is a folder that was bind mounted from the host. 

But, in the interest of moving forward at my end, I'm modifying how we use MSSQL in Docker and switching to storing our data in Docker volumes instead.  

I still consider this to be a bug - it works just fine in 2.2.0.5 but fails in any later release. If it's not a bug, I wish someone could explain to me why my working installation suddenly failed when I upgraded Docker.

**Comment by kengranderson** [comment]
@martyt - Since you are binding to Windows folders, have you tried (if just to see if it's a security thing) setting the folder permissions to Everyone Full Control?  Or the Docker desktop service has to be run under an admin user account now?

"I wish someone could explain to me why my working installation suddenly failed when I upgraded Docker."

My default guess is that the previous behavior enabled some-evil-person-who-has-nothing-better-to-do-than-make-life-more-inconvenient-for-the-rest-of-us-by-spending-their-days-trying-to-break-into-stuff, to do something evil to Docker images and / the file system, so now the previous behavior is considered a 'security hole?'

**Comment by Azathoth88** [comment]
@kengranderson i tried the same, but that doesn't work for me for BACKUP DB. But I can CREATE DB in the folder. This is definitely a bug for me.

**Comment by Amberg** [comment]
> @kengranderson i tried the same, but that doesn't work for me for BACKUP DB. But I can CREATE DB in the folder. This is definitely a bug for me.

Exactly. `RESTORE DATABASE FROM DISK` does not work from a mounted host folder

- 2019-latest or 2017-latest same behavior
- start sql container as root does not help
- chown mssql does not help

This is a bug

**Comment by john-league-ninja** [comment]
Anyone had any luck resolving this? I am seeing it after doing fresh installs of docker / sql 2019.

**Comment by laiseng** [comment]
I've found workaround for this issue.

1. Create a new empty database 
2. `docker exec -it container_id` into your container
3. change your files mdf ldf file permission using `chmod -R 777 /var/opt/mssql/data` ( for simplicity sake, i change all files )
4. restore your *.bak file using SSMS to the newly created Database and make sure you check the **overwrite existing database WITH REPLCE**
![image](https://user-images.githubusercontent.com/3101352/94532131-0d707a80-0270-11eb-967e-86c69374e12b.png)

NOTE: for my db somehow it complains my newly created has no DB backup log. I just go to my newly created empty db and trigger a mssql backup. then go back to restore my bak file

you should revert back the file permission in /var/opt/mssql/data if it's you dev machine like mine, then you may leave it as it is

**Comment by Phiph** [comment]
I'm experiencing this problem too!

**Comment by moisoiu** [comment]
> I've found workaround for this issue.
> 
> 1. Create a new empty database
> 2. `docker exec -it container_id` into your container
> 3. change your files mdf ldf file permission using `chmod -R 777 /var/opt/mssql/data` ( for simplicity sake, i change all files )
> 4. restore your *.bak file using SSMS to the newly created Database and make sure you check the **overwrite existing database WITH REPLCE**
>    ![image](https://user-images.githubusercontent.com/3101352/94532131-0d707a80-0270-11eb-967e-86c69374e12b.png)
> 
> NOTE: for my db somehow it complains my newly created has no DB backup log. I just go to my newly created empty db and trigger a mssql backup. then go back to restore my bak file
> 
> you should revert back the file permission in /var/opt/mssql/data if it's you dev machine like mine, then you may leave it as it is

For who tried this option and still didn't work, you can also try to uncheck the **Take tail-log backup before restore**

![TailLong](https://user-images.githubusercontent.com/5052365/98126706-90fc3780-1ebe-11eb-9ed6-dd5842799655.PNG)

But this didn't work always, so I also tried to Attach the .mdf file, but same behavior but as soon as I removed the .ldf file everything worked OK.

Kind of annoying issue, initially I tried to restore following the tutorial from here -> https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-ver15

So good luck !

**Comment by jbwittner** [comment]
Hi !

When I tried to restore a database, I had the same problem :'(

```
TITLE: Microsoft SQL Server Management Studio
------------------------------

Restore of database 'Test' failed. (Microsoft.SqlServer.Management.RelationalEngineTasks)

------------------------------
ADDITIONAL INFORMATION:

System.Data.SqlClient.SqlError: The operating system returned the error '2(The system cannot find the file specified.)' while attempting 'RestoreContainer::ValidateTargetForCreation' on '/var/opt/mssql/data/Test.mdf'. (Microsoft.SqlServer.SmoExtended)

For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft+SQL+Server&ProdVer=16.100.46041.41+(SMO-master-A)&LinkId=20476

------------------------------
BUTTONS:

OK
------------------------------
```

```YAML
version: '3.7'

services:
    SQL_Server:
      image:  mcr.microsoft.com/mssql/server:2019-latest
      restart: always
      volumes:
      - type: bind
        source: c:\devsqltest\data
        target: /var/opt/mssql/data
      environment:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 'Str0ngPassword!'
      ports:
          - 1433:1433
```

And when i tried to change the permissions of `/var/opt/mssql/data` with the command `chmod -R 777 /var/opt/mssql/data` i have an error => `chmod: changing permissions of '/var/opt/mssql/data': Operation not permitted`

Thank you for your help
