### ISSUE TITLE
Unable to mount volume using hostPath

### ISSUE THREAD

**Issue by jongio** [docker/for-win#7488]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
2827122D-AEB2-4F8E-BCB8-8EB7FE343E58/20200629175448

### Expected behavior

I should be able to mount a folder from my local development machine and access it from within a container hosted by k8s.

### Actual behavior

I am unable to mount a local folder.

### Information

  - Windows Version:

`Version 2004: 19041.329`

  - Docker Desktop Version:

`Docker version 19.03.12, build 48a66213fe`

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

`No.  WSL 2
Docker Desktop Edge. I also tried with with Desktop Stable`

### Steps to reproduce the behavior

I have pushed the code that is not working here: 
https://github.com/jongio/azureclicredentialcontainer/tree/k8s

The k8s file is here:
https://github.com/jongio/azureclicredentialcontainer/blob/k8s/src/net/.k8s/k8s.yml

The docker-compose file that is working with docker-compose up is here:
https://github.com/jongio/azureclicredentialcontainer/blob/k8s/src/net/docker-compose.yml

Here's what I have:

```yaml
    containers:
        - image: azureclicredentialcontainer
          imagePullPolicy: "Never"
          name: azureclicredentialcontainer
          resources: {}
          volumeMounts:
            - mountPath: /root/.azure
              name: cli
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - hostPath:
            path: /C/Users/Jon/.azure
          name: cli
```

I have tried many paths, including:
- `/host_mnt`
- `/mnt`
- `//C`
- `/C`
- `/home/jon`
...and nothing works.

I have also tried using `type: DirectoryOrCreate` and that didn't help and didn't see any errors with `kubectl get events --all-namespaces --sort-by='.metadata.creationTimestamp'`

azsdke2e

**Comment by jsturtevant** [comment]
what does `kubectl describe po <podname>` give you? Are you able to see kubelet logs?  Might try this on a Windows Server VM to see if the behavior is related to docker desktop/the container runtime/kubernetes

**Comment by jongio** [comment]
I pushed the container to: 
https://hub.docker.com/repository/docker/jongio/azureclicredentialcontainer

With tag: k8s


```
Name:         azureclicredentialcontainer-b4b885b59-b6prl
Namespace:    default
Priority:     0
Node:         docker-desktop/192.168.65.3
Start Time:   Tue, 30 Jun 2020 10:06:09 -0700
Labels:       io.kompose.service=azureclicredentialcontainer
              pod-template-hash=b4b885b59
Annotations:  <none>
Status:       Running
IP:           10.1.0.120
IPs:
  IP:           10.1.0.120
Controlled By:  ReplicaSet/azureclicredentialcontainer-b4b885b59
Containers:
  azureclicredentialcontainer:
    Container ID:   docker://fa14e3af8ff8d26ecc9a97961640125ea0a5e9ffb42a3b17b216bb58a4a6e9a0
    Image:          jongio/azureclicredentialcontainer:k8s
    Image ID:       docker-pullable://jongio/azureclicredentialcontainer@sha256:94dc3e6e0a8c320d656d3bb38a08f87e3248da69a5a008963690b5a8ec34bb8a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 30 Jun 2020 10:06:12 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /root/.azure from cli (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8bnf5 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  cli:
    Type:          HostPath (bare host directory volume)
    Path:          /C/Users/Jon/.azure
    HostPathType:  DirectoryOrCreate
  default-token-8bnf5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8bnf5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From                     Message
  ----    ------     ----       ----                     -------
  Normal  Scheduled  <unknown>  default-scheduler        Successfully assigned default/azureclicredentialcontainer-b4b885b59-b6prl to docker-desktop
  Normal  Pulling    106s       kubelet, docker-desktop  Pulling image "jongio/azureclicredentialcontainer:k8s"
  Normal  Pulled     105s       kubelet, docker-desktop  Successfully pulled image "jongio/azureclicredentialcontainer:k8s"
  Normal  Created    104s       kubelet, docker-desktop  Created container azureclicredentialcontainer
  Normal  Started    104s       kubelet, docker-desktop  Started container azureclicredentialcontainer
```

**Comment by jongio** [comment]
1 On windows machine

mkdir c:\test
create file "foo.txt"

1. git clone https://github.cm/jongio/azureclicredentialcontainer
2. git checkout k8s

cd to src/net

# Docker Desktop

> THIS WORKS

run `docker-compose up --build`

You will see output:
/root/test/foo.txt

docker-compose file
```
version: '3.4'

services:
  azureclicredentialcontainer:
    image: jongio/azureclicredentialcontainer:k8s
    volumes: 
      - "/C/test:/root/test"
    build:
      context: .
      dockerfile: Dockerfile
```



# Kubernetes

> THIS DOES NOT WORK

In WSL2, run from src/net

`kubectl apply -f .`

You can see that the mount appears to work, but **foo.txt** does not get printed and the directory is empty in the container.

![image](https://user-images.githubusercontent.com/2163001/87473038-ba264e80-c5d5-11ea-9722-ea36044155e1.png)

k8s file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: azureclicredentialcontainer
  name: azureclicredentialcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: azureclicredentialcontainer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: azureclicredentialcontainer
    spec:
      containers:
        - image: jongio/azureclicredentialcontainer:k8s
          imagePullPolicy: "Never"
          name: azureclicredentialcontainer
          resources: {}
          volumeMounts:
            - mountPath: /root/test
              name: cli
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - hostPath:
            path: /C/test
          name: cli
status: {}

```

**Comment by jongio** [comment]
I got this working thanks to @TroyLaurin's post here: https://github.com/docker/for-win/issues/5325#issuecomment-645859528

I updated the steps here: https://github.com/jongio/azureclicredentialcontainer#running-azureclicredential-in-kubernetes



## Running AzureCliCredential in Kubernetes

I'm running Docker Desktop and WSL2. The following is for that configuration. If you are using a different setup and can't get this to work, then let me know and I should be able to help you get it all setup.

Standard Kubernetes hostPath based volume mounts do not currently work with Docker Desktop and WSL2, so you need to do the following:

Create a directory in the /mnt/wsl folder to mount to, then mount from ${HOME}/.azure to that folder.  I don't exactly know why this is required, but it works.  Here's more info if you are interested in researching it: [Kubernetes Volumes not correctly mounted with WSL2](https://github.com/docker/for-win/issues/5325#issuecomment-645859528)

```bash
mkdir /mnt/wsl/.azure
sudo mount --bind ${HOME}/.azure /mnt/wsl/.azure
```

Then in your Kubernetes config file you specify the mount path like this:

```yaml
volumes:
   - hostPath:
      path: /run/desktop/mnt/host/wsl/.azure
      type: Directory
      name: cli
```

You can find the entire file example here: [.k8s/k8s.yml](src/net/.k8s/k8s.yml)

Then run `kubeclt apply -f .k8s` and you will see `key1` outputed to your logs.

You can remove the mount with the following:

```bash
sudo umount /mnt/wsl/.azure
```
