### ISSUE TITLE
Docker 'Filesharing has been cancelled' error when trying to spin up docker container

### ISSUE THREAD

**Issue by ConfidenceYobo** [docker/for-win#7507]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6E5F16A4-33E3-45A2-BFC1-68914C81CAEB/20200630141413

### Expected behavior
 To spin up containers
### Actual behavior
ERROR: for db  Cannot create container for service db: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled" ...}
### Information

  - Windows Version: Windows 10 version 2004
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Here is the content of my docker file:
``` yaml
    # pull official base image
    FROM python:3.8-alpine
    
    # set work directory
    WORKDIR /usr/src/app
    
    # set environment variables
    ENV PYTHONDONTWRITEBYTECODE 1
    ENV PYTHONUNBUFFERED 1
    
    # install dependencies
    RUN apk update \
    && apk add --no-cache --virtual .build-deps gcc linux-headers musl-dev mariadb-dev zlib \
     python3-dev jpeg-dev zlib-dev openssl-dev
    
    # install dependencies
    RUN pip install --upgrade pip
    COPY ./requirements.txt .
    RUN pip install -r requirements.txt
    
    # Clean up disk space
    # RUN apk add --virtual .rundeps $runDeps \
    # 	&& apk del .build-deps 
    
    RUN apk del gcc python3-dev musl-dev jpeg-dev zlib-dev
    RUN rm -Rf ~/.cache
    
    # copy project
    COPY . .
```

docker-comose.yml: 
``` yaml
    version: '3.7'
    
    services:
      db:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - db-data:/var/lib/mysql
          - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        env_file:
          - .db.env
        ports:
          - "3310:33060"
    
      web:
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./:/usr/src/app/
        ports:
          - 8000:8000
        env_file:
          - ./.env
        links:
          - db
        depends_on:
          - db
      
    volumes:
      db-data:
```
  2. ``` docker-compose up -d --build ```
