### ISSUE TITLE
WSL2: Intermittent input/output errors on mounted Windows directories

### ISSUE THREAD

**Issue by phillip-elm** [docker/for-win#7552]
- [X] I have tried with the latest version of my channel (Stable or Edge)
- [X] I have uploaded Diagnostics
- Diagnostics ID: 462F11BC-C680-4010-B3F4-93793E1158B2/20200704221336

### Expected behavior

Mounted volumes on the Windows host stat, open, etc. without issues.

### Actual behavior

Containers which serve dynamic and static file requests intermittently experience "input/output error"s on various filesystem operations.

In a sample WordPress FPM container:
```
NOTICE: PHP message: PHP Warning:  require(/var/www/html/wp-content/themes/twentytwenty/template-parts/footer-menus-widgets.php): failed to open stream: Input/output error in /var/www/html/wp-includes/template.php on line 725
```

In a separate in-house Golang application:
```
[ERR] Failed to stat /redacted/path/to/file: input/output error
```

The files that fail are random - the same file that will work 9/10 times will fail the 10th time and then work again after that.

### Information

- I have tested this on both the latest stable and edge releases (2.3.0.3 and 2.3.2.1, respectively)
- Windows Version: 2004 (OS Build 19041.329)
- Windows is running natively on the host desktop machine
- This is my first time using Docker for Windows, so I don't know if this is new. I have not experienced this on Docker for Linux or Mac.
- Based on my research prior to opening this ticket, I can confirm that restarting WSL with `wsl --shutdown` does not fix the issue.

Sample docker-compose.yaml file:

```yaml
version: "3.7"

services:
  wordpress:
    image: wordpress:php7.4-fpm

    expose:
      - 9000

    volumes:
      # WORDPRESS_ROOT is a path on the local filesystem that points to where wp-config.php lives
      - ${WORDPRESS_ROOT}:/var/www/html
```

### Steps to reproduce the behavior

- Start containers with volumes that mount to a Windows filesystem path
- Do something to start reading files - in my case, send a web request to WordPress or a static site server.
- Intermittently, random files will fail to stat or open with "input/output error"

### Notes

I'm not sure if this is a Docker or WSL2 thing - or both. Worst case I can move the issue to that team, but I'd like to see if anyone here is experiencing this.
