### ISSUE TITLE
error while creating mount source path

### ISSUE THREAD

**Issue by GusGF** [docker/for-win#7734]
No logs were generated
Windows 10 Pro Home PC
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.5, build 8a1c60f6

When I run the docker compose file below I'm getting these errors which look like simple file permission issues but have no idea how to proceed. I've no idea why if I'm correct it's trying to create this path:
/run/desktop/mnt/host/c/Users/gus/DockerStuff/webinspect/mysql
Where is it coming up with this??

```
C:\Users\gus\DockerStuff\webinspect>docker-compose up
Creating mysqlcontainer ... error

ERROR: for mysqlcontainer  Cannot start service mysqldbserv: error while creating mount source path '/run/desktop/mnt/host/c/Users/gus/DockerStuff/webinspect/mysql': mkdir /run/desktop/mnt/host/c: file exists

ERROR: for mysqldbserv  Cannot start service mysqldbserv: error while creating mount source path '/run/desktop/mnt/host/c/Users/gus/DockerStuff/webinspect/mysql': mkdir /run/desktop/mnt/host/c: file exists
ERROR: Encountered errors while bringing up the project.
```

docker-compose.yaml

```
version: '3'

services:
    #######  Database service  #######
    mysqldbserv:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysqlcontainer
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sqldb
            MYSQL_USER: user
            MYSQL_PASSWORD: pwd


    #######  Wordpress service  #######
    wordpress:
        image: wordpress
        container_name: wordpresscontainer
        depends_on:
             - mysqldbserv
        restart: always
        environment: 
            WORDPRESS_DB_HOST: mysqldbserv
            WORDPRESS_DB_NAME: sqldb
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: pwd
        ports:
            - '8001:80'
        volumes: 
            - ./wordpress:/var/www/html


    #######  phpmyadmin service  #######
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmincontainer
        depends_on: 
            - mysqldbserv
        restart: always
        ports:
            - '8002:80'
        environment:
            PMA_HOST: mysqldbserv
            MYSQL_ROOT_PASSWORD: root
```
