### ISSUE TITLE
env_file attribute not reading from nested folder

### ISSUE THREAD

**Issue by narwy** [docker/for-win#7821]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D243E875-8FFC-4B33-8179-077C2E1EE782/20200725170110

### Expected behavior
To read the env file nested in a folder and use variables.

### Actual behavior
.env file will not read on Windows nested in a folder but does work on Mac and Linux OS.

### Information
  - Windows Version: 10 Pro - Build 19041
  - Docker Desktop Version: Latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Create a `.env` inside a folder (example /api/.env)
2. Create a docker-compose.yml with these contents:
```
version: '3.1'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./api/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    restart: always
```
3. Run `docker-compose up`

See errors relating to environment variables not found. This works on Mac / Linux OS just not on Windows.
