### ISSUE TITLE
403 Forbidden on locally running Wordpress site

### ISSUE THREAD

**Issue by GusGF** [docker/for-win#8058]
403 Forbidden
You don't have permission to access this resource.

I'm running docker containers php, Wordpress and mysql and all works fine. The fun starts when I wake the computer from sleep mode I get the above response when I try and access my locally running WP site. I resolve this by restarting Docker Desktop and have to do this every time I wake the computer.

The other thing is trying to individually restart the containers i.e. the WP container does not work. It stops but won't start again just remains at exited!

Any suggestions to move forward on this? I've posted my YAML file below.

```
version: '3'

services:
    #######  Database service  #######
    mysqlDBserv:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysqlCont
        volumes:
            # - db_data:/var/lib/mysql
            # ....or use below
            - ./mysql:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wpDB
            MYSQL_USER: admin   
            MYSQL_PASSWORD: pass


    #######  Wordpress service  #######
    wordpress:
        image: wordpress:latest
        container_name: wpCont
        depends_on:
             - mysqlDBserv
        restart: always
        environment:
            # the host is looking for the IP address & host or you can just use the service name
            WORDPRESS_DB_HOST: mysqlDBserv
            WORDPRESS_DB_NAME: wpDB
            WORDPRESS_DB_USER: admin
            WORDPRESS_DB_PASSWORD: pass
        ports:
            # Apparently this is for http connections
            - '8001:80'
            # Apparently this is for https connections
            # - '443:443'
        # All the relevant data lives at :/var/www/html
        volumes:
            # - wp_data:/var/www/html
            # ....or use below            
            - ./wordpress:/var/www/html


    #######  phpmyadmin service  #######
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpCont
        depends_on: 
            - mysqlDBserv
        restart: always
        ports:
            - '8002:80'
        environment:
            PMA_HOST: mysqlDBserv
            MYSQL_ROOT_PASSWORD: root
```
