### ISSUE TITLE
Windows Server 2004 use docker-compose create multi NAT network HNS process is CPU high

### ISSUE THREAD

**Issue by kkbruce** [docker/for-win#8423]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Create a NAT network and running container service.

### Actual behavior

Use docker-compose.exe create multi NAT network, HNS process is easy to cause CPU to pull high and the container process will hold.

### Information

  - Windows Version:

Windows Server 2004 (Server Core Mode)

```
C:\>ver

Microsoft Windows [Version 10.0.19041.450]
```
  - Docker Desktop Version:

```
C:\>docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker Enterprise clusters (Mirantis Inc., v1.6.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.12
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows Server Standard Version 2004 (OS Build 19041.450)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.999GiB
 Name: cnqasdocker01
 ID: FE2K:OHK7:JVXE:NC3S:3BTR:Y6VZ:RC3L:WUMW:HWKV:KOGN:ZIMZ:TNI2
 Docker Root Dir: D:\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

```
Yes, running inside VMware - Hyper-V VM.
```

### Steps to reproduce the behavior

1. Open two command-line and enter different folders.

2. The first command-line, create `docker-compose.yml`

```
version: '3.8'
services:
  iis8080:
    image: "mcr.microsoft.com/windows/servercore/iis:windowsservercore-2004"
    ports:
      - 8080:80
    restart: on-failure
```

Run `docker-compose.exe up` or `docker-compose.exe up -d`

3. The second command-line, create `docker-compose.yml`
```
version: '3.8'
services:
  iis8081:
    image: "mcr.microsoft.com/windows/servercore/iis:windowsservercore-2004"
    ports:
      - 8081:80
    restart: on-failure
```

Run `docker-compose.exe up` or `docker-compose.exe up -d`

![image](https://user-images.githubusercontent.com/2024682/92703330-af452b80-f384-11ea-88eb-2587f82566ca.png)

This usually occurs when only a few (mostly two) are activated.
