### ISSUE TITLE
Volume host path

### ISSUE THREAD

**Issue by pedro2555** [docker/for-win#8424]
This is a question.

Consider the following `docker-compose.yml` file:

```yml
version: "3"

volumes:
  sql-data:
    driver: local

services:
  sql-server:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: your-pass-here
      ACCEPT_EULA: Y
    volumes:
      - sql-data:/var/opt/mssql
```

Where exactly, the exact path and machine, is the mounting point for the `sql-data` volume on the host?

I'm attempting to restore a database on a local SQL server for development purposes but failing to understand where to copy the existing backup so it is visible in the running container.

`docker volume inspect sql-server_sql-data` would return something like:

```
[
    {
        "CreatedAt": "2020-09-10T09:27:52Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "sql-server",
            "com.docker.compose.version": "1.26.2",
            "com.docker.compose.volume": "sql-data"
        },
        "Mountpoint": "/var/lib/docker/volumes/sql-server_sql-data/_data",
        "Name": "sql-server_sql-data",
        "Options": null,
        "Scope": "local"
    }
]
```

On linux `/var/lib/docker/volumes/sql-server_sql-data/_data` would get you access to the volume's files. However this is not the case on Windows, to start no such path exists on Windows.

One would think it may be in the WSL file system (`\\wsl$`). But this is not the case, I guess because the docker engine, as far as I understand, actually runs on a linux virtual machine running in hyper-v.

But how in the world does get access to the volume's data? I just need to copy a ``bak` backup file, any solution is very welcome.

Also, this is terribly badly documented. The expectation fails to be true and there is no obvious guideline in accessing a local volume data.
