### ISSUE TITLE
When a volume is a file, docker will delete its content when starting.

### ISSUE THREAD

**Issue by lazybean** [docker/for-win#8439]
- [x] I have tried with the latest version of my channel (Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 742EB8D3-9DAD-4542-8687-0F8B2BDEC3D1/20200911082441

### Expected behavior
The mounted file should stay intact
### Actual behavior
File content is erased.
### Information

  - Windows Version: 2004 (build 19041.508)
  - Docker Desktop Version: 2.3.6.2 (47842)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
1. In a folder (dockerBug) create 2 files:

- foo.txt :  "hello docker"
- docker-compose.yml:
```
version: "3"

services:
  web:
    image: node:lts-alpine
    working_dir: /temp
    volumes:
      - ./foo.txt:/temp/foo.txt
```
1.b `git init .; git commit -a'
2. docker-compose up -d
3. restart docker
4. Notice foo.txt is empty
```
diff --git a/foo.txt b/foo.txt
index 8260792..e69de29 100644
--- a/foo.txt
+++ b/foo.txt
@@ -1 +0,0 @@
-hello docker
```

5. 
```
❯ git restore .
error: unable to unlink old 'foo.txt': Device or resource busy
```
