### ISSUE TITLE
Gitlab container freezing on startup: not sure if problem with Docker Desktop or with Gitlab?

### ISSUE THREAD

**Issue by JohnRDOrazio** [docker/for-win#8509]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **9F55A40D-560D-4376-ABCA-4024A96FBB3E/20200916081419**

### Expected behavior
When launching Gitlab container, it should take a few minutes to start up and should then become available through the traefik reverse proxy that I'm running. This in fact was the case until recently (a couple weeks ago?). I successfully launched this container a number of times in the past couple months and I started creating Gitlab repos, which persisted between launches given I have mapped to volumes on the Ubuntu 20.04 instance.

### Actual behavior
When launching Gitlab container, system resource usage starts climbing, Disk I/O goes up to about 450MB/s and Docker for Desktop freezes. I can no longer interact with the WSL2 Ubuntu 20.04 instance, and the Docker log for the container stops printing information. The traefik dashboard no longer responds.  My whole Windows 10 system slows down incredibly, and I cannot stop the Gitlab container. I have to shutdown Docker Desktop itself in order for the container to stop, and this can even take 10-20 minutes to complete.

### Information

  - Windows Version: **Windows 10 Pro build 19041**
  - Docker Desktop Version: **2.3.0.5**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **no, running a physical machine**

### Steps to reproduce the behavior

Here is my gitlab container's docker-compose.yml, which was working nicely until recently:

```
## gitlab docker-compose file
version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: "gitlab.docker.localhost"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.docker.localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        #letsencrypt['enable'] = false
        #nginx['proxy_set_headers'] = {
        #  "X-Forwarded-Proto" => "https",
        #  "X-Forwarded-Ssl" => "on"
        #}
    ports:
      - "8929:80"
      - "2224:22"
      #- "8930:443"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab:Z"
      - "/srv/gitlab/logs:/var/log/gitlab:Z"
      - "/srv/gitlab/data:/var/opt/gitlab:Z"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.docker.localhost`)"
      - "traefik.http.routers.gitlab.entrypoints=http,https"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.routers.gitlab.tls=true"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
```
  1. launch the container either from the Docker Desktop interface or from the Ubuntu 20.04 command line: `docker-compose up`
  2. the startup log will freeze for whatever reason either on **puma** startup, or **promethues**, or **grafana**
  3. it is impossible to launch a CLI inside the container to try to debug anything from inside the container. I haven't changed anything in the YML from when the container was launching successfully until recently when it started to act strangely by freezing on startup. I have tried deleting all data in the mapped volumes and restarting but the problem persists.
