### ISSUE TITLE
`PollingFileWatcher` Issue while running `dotnet watch run` with wsl volume mounts

### ISSUE THREAD

**Issue by pawan-regoti** [docker/for-win#8749]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
`dotnet watch run` executes without any issues and track the file changes done in `MySampleService` folder

### Actual behavior
`PollingFileWatcher` issue is occurring sometimes 

### Information

  - Windows Version: Windows 10 with WSL2 integration
  - Docker Desktop Version: 2.4.0.0 (48506) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

I have a dotnet core project which is stored in c drive of my windows system.
I have wsl2 integration with my docker desktop.

I have following folder structure:
* Some Folder in C drive
  * MySampleService
    * bin
    * obj
    * some-code.cs
  * docker-compose.yml

Following is my docker-compose.yml
```
version: "2.1"
services:
  my-sample-service:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    working_dir: /usr/src/app/MySampleService
    volumes:
      - ./MySampleService:/usr/src/app/MySampleService
    environment:
      "DOTNET_USE_POLLING_FILE_WATCHER": 1
    entrypoint: "dotnet watch run --urls=http://0.0.0.0:5010"
    ports:
      - 5010:5010
    healthcheck:
      test: wget --quiet --spider http://localhost:5010/api/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 20

```

I am trying to run my application in docker using `dotnet watch run` and wanted to reflect the changes I do in `MySampleService` in docker build.

When I do `docker-compose up`
I am getting following error in docker logs:

![FilePollingIssue](https://user-images.githubusercontent.com/39826745/94813526-63702a00-03f8-11eb-9ff8-9c4f07661d4f.png)

Can somebody help me in fixing this issue? 🙂
