### ISSUE TITLE
Docker.sock not accessible to containers after Windows restart

### ISSUE THREAD

**Issue by rg9400** [docker/for-win#8841]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7E746511-651C-4A74-8C84-91189E8962C1/20201005183753

### Expected behavior
I have a couple of containers that are mounted to `/var/run/docker.sock` such as Portainer, Ofelia, Ouroboros, Telegraf, etc. The containers are set with the restart policy `unless-stopped`. The expected behavior is that after the host Windows system restarts, these containers spin back up and work as normal
### Actual behavior
After I restart the Windows host, these containers spin back up fine ; however, they do not seem to be able to access the data from this file. They also do not seem to be able to interact with the Docker daemon. So Portainer shows the entire stack as down, Telegraf does not pull metrics, Ofelia cannot exec into containers, etc. If I restart these containers manually, they start working as intended 
### Information

  - Windows Version: 2004 (OS Build 19041.508)
  - Docker Desktop Version: 2.4.1.0 (48583)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Here is a sample `docker-compose` for portainer. 
1. Spin this up
2. Make sure it is working on port 9000
3. Restart Windows
4. Recheck Portainer, notice how it cannot pull data after the restart. 
5. Restart the container itself. Notice that the issue is resolved as it is now able to read data again

```yaml
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    user: 1000:1001
    environment:
      - UMASK_SET=022
      - TZ="America/Chicago"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000
      - 8000:8000
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
```

**Comment by stephen-turner** [comment]
Interesting, it sounds like there's a race condition. Have you successfully run this with previous versions or not?

**Comment by rg9400** [comment]
I just started using Docker for Windows a few weeks ago, and I always noticed this behavior. I was just recently told that it was not expected. Based on the bug report I submitted for the limited internet bandwidth issue (https://github.com/docker/for-win/issues/8590), I started using Docker around version 2.3.7.0

**Comment by thaJeztah** [comment]
This is a known issue when attempting to bind-mount the engine API socket into a container. The root cause is one that's difficult (or impossible) to fix, and is because the API (which creates the socket) and container lifecycles are separate subsystems, and containers can be started before the API is running (which could also be the case if the "live restore" feature is used, which allows restarting the daemon without stopping containers) . 

There's an older ticket in the docker engine issue tracker that discusses this, and has some more details; https://github.com/moby/moby/issues/30348

There are some workarounds that, depending on your use-case, may help;

One of the problems is that the  `-v <host-path>:<container-path>` shorthand syntax automatically creates `<host-path>` if the path does not exist. However, docker does not know if `<host-path>` was expected to point to a file or a directory, and by default creates a _directory_. This means that if `/var/run/docker.sock` is not (yet) present when the container is started, a directory with that name will be created (potentially preventing the API from starting). We tried depreciating the "auto-create" behaviour, but had to revert, as it was breaking too many users (https://github.com/moby/moby/pull/21666).

However, the `--mount` "long syntax" does not auto-create host-paths, and instead will cause the container to _fail_, which may be more desirable in this situation.

The long syntax for compose-files is described here; https://docs.docker.com/compose/compose-file/#long-syntax-3
And for the command-line can be found in this section; https://docs.docker.com/storage/bind-mounts/

For example, to bind-mount the socket on the command-line:

```console
 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
```

For example, the following starts a container with the docker CLI in it, mounts the docker socket and outputs `docker info`;

```bash
docker run --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock docker docker info
```

The equivalent in a compose file is:

```yaml
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
```

As mentioned, the container will fail to start if the socket is not present, so you likely want to set a restart policy for your container / service so that docker attempts to restart the container until the socket is available; see the [restart policy](https://docs.docker.com/compose/compose-file/#restart) in the compose file reference;

```yaml
      restart_policy:
        condition: on-failure
```

An alternative option is to bind-mount the directory instead of the instead of bind-mounting the socket itself, however, this may not work on Docker Desktop, and may expose other information from the host, so may require some additional changes in the configuration

**Comment by rg9400** [comment]
I tested this with the below compose for Portainer, but it did not connect to the socket after running `wsl --shutdown` on the host, then restarting the Docker daemon. I want to use the `unless-stopped` policy, which I assumed would cover the `on-failure` option as well?

`(err=Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?)`

```yaml
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=${UMASK_SET}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - ${CONFDIR}/portainer:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000
      - 8000:8000
    command: -H unix:///var/run/docker.sock
    depends_on:
      - adguard
    dns: 172.20.0.150
    restart: unless-stopped
```
