### ISSUE TITLE
Mounting volumes causes spurious oddities

### ISSUE THREAD

**Issue by popey456963** [docker/for-win#885]
### Expected behavior

Mounting C:\users should mount all folders within it and all sub-folders

### Actual behavior

It seems to pick a single folder from all the folders in a directory and only lists that one.  It also doesn't even continue that until an empty folder:

![](https://puu.sh/wzDUx/1d728662be.png)

My documents alone contains significantly more files and folders:

![](https://puu.sh/wzE0Q/e23606d01f.png)

### Information

  - Diagnostic ID: `D412822A-4598-4B33-83AE-1C4994465E70/2017-07-02_11-58-01`
  - OS and Build: `Windows 10, Docker version 17.06.0-ce, build 02c1d87`.

### Steps to reproduce the behavior

  1. Assuming you have multiple users on your system, or at least multiple folders somewhere within c:\Users, you can reproduce this with `docker run --rm -ti -v C:\Users:/data alpine /bin/sh`
  2. Then run `ls /data/some_user` and verify that not all folders show up.

### Extra

This is a fairly entertaining issue that I've been working on for a few hours to no avail.  It comes from the following docker-compose script:

```
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/tpm
      - /tpm/node_modules
    environment:
      NODE_ENV: development
    # command: ["npm", "run", "dev"]
    command: ls
```

Which works on Mac/Linux but fails on Windows.
