### ISSUE TITLE
2.4.0.0 can't mount file into container: Error response from daemon: not a directory

### ISSUE THREAD

**Issue by 4n70w4** [docker/for-win#8878]
After update to 2.4.0.0 dont work file mount, only work directory mount.

Error response from daemon: not a directory

don't work:

```yml
            volumes:
              - /srv/consul/agent.json:/etc/consul.d/agent.json
```

also don't work

```yml
            volumes:
              - type: bind
                source: /srv/consul/agent.json
                target: /etc/consul.d/agent.json
```

After downgrade to 2.3.0.5 files mount works!
