### ISSUE TITLE
It seems like docker doesn't update on local file change.

### ISSUE THREAD

**Issue by Lukortech** [docker/for-win#9047]
[Related](https://github.com/docker/for-win/issues/5530)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: _4CD6F022-16AA-4E84-A784-3831B05DC7FC/20201014204751_

### Expected behavior
volumes should allow me to reflect local changes on docker image
### Actual behavior
doesn't update stuff eventhough it has changed on my local machine
### Information
  - Windows Version:  2004 - 19041.508
![image](https://user-images.githubusercontent.com/26508593/96044597-f6857700-0e70-11eb-966e-2687f2f55b64.png)

  - Docker Desktop Version: v19.03.13

**Comment by stephen-turner** [comment]
If you are using WSL 2, but keeping your files in the Windows file system, this is expected, which is why we don't recommend that configuration. See https://docs.docker.com/docker-for-windows/wsl/

**Comment by Lukortech** [comment]
Interesting part is that when trying the same setup on Ubuntu the problem still exists. 
I've tried running it on @yirogu machine that has Ubuntu installed and docker didn't react to local file update.
Maybe that's something with `compose.yml `file...

**Comment by Lukortech** [comment]
Folder structure locally:
![image](https://user-images.githubusercontent.com/26508593/96106914-0be3bb00-0edc-11eb-87b1-a05a3e73ad93.png)
Docker image:
![image](https://user-images.githubusercontent.com/26508593/96107020-2f0e6a80-0edc-11eb-991c-eff277fa6da9.png)

The compose file looks like this:
```
version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "npm run watch --silent --no-progress & php artisan serve --host=0.0.0.0 --port=8181"
    ports:
      - 8181:8181  
    volumes:
      - ./resources:/app/resources
```

I am too new to the whole idea of dockerizing vue-laravel app so I might have mixed things up, but to my knowledge volumes should allow me to update resources in docker image and thus npm watching over those files should rebuild the app.
