### ISSUE TITLE
Unable to pull images: gets stuck downloading

### ISSUE THREAD

**Issue by DaleyKD** [docker/for-win#9488]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: ACEB1576-2BEC-41C9-B81F-38F00642D372/20201112184606

### Expected behavior
I'd like to be able to pull docker images from repos without getting stuck and having to reboot my machine.

### Actual behavior
```
Pulling consul      ... waiting
Pulling nginx-proxy ... waiting
Pulling azurite     ... waiting
Pulling rabbitmq    ... waiting
Pulling sql.data    ... downloading (34.8%)
ERROR: Aborting.
```

### Information

  - Windows Version: Windows 10 Enterprise 20H2
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

``` yaml
version: '3.5'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: 172.22.0.101
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf.d.my.conf:/etc/nginx/conf.d/my.conf:ro
      - ./nginx/vhost.d.my.conf:/etc/nginx/vhost.d/*.my.local:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  sql.data:
    container_name: sql.data
    image: mcr.microsoft.com/mssql/server:latest
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine

  consul:
    container_name: consul
    image: consul:latest
    command: agent -dev

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite

networks:
  default:
    name: mylocal
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
```

After fighting Docker Desktop to "get in sync" with the Hyper-V VM's status (in other words, so that Docker Desktop realizes it's not running when the VM is stopped), Docker Desktop finally told me it's ready to rock n' roll.  At that point, I tried to execute the docker-compose command, and that's where I'm now getting stuck.  In the last year, I've never had this issue with docker.

I also tried to disable IPv6 on my network adapter and vEthernet (Default Switch). That did not help.

### Steps to reproduce the behavior

  1. Install Docker.
  2. Set environment variables:
     1. `$env:COMPOSE_DOCKER_CLI_BUILD=1`
     1. `$env:DOCKER_BUILDKIT=1`
  3. Run `docker-compose -f "docker-compose.yml" -p "deps" pull`
