### ISSUE TITLE
DOCKER VOLUMES NOT LISTENING

### ISSUE THREAD

**Issue by GiridharSundar** [docker/for-win#9666]
- [Yes ] I have tried with the latest version of my channel (Stable or Edge)
  - [Yes ] I have uploaded Diagnostics
  - Diagnostics ID: D1D41FCF-E1EC-4859-91CE-1DE49BE72936/20201201075631

### Expected behavior
I have tried to use docker volumes and it never listens. Changes made to my file only affect after I rebuild. 

### Actual behavior
No changes on my container.

### Information
 My docker-compose.yml file

#DOCKER-COMPOSE FILE

```yaml
version: '3.8'

services:
    smart-brain-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        environment:
            POSTGRES_URI: postgres://giri:secret@postgres:5432/facewebapp
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/smart-brain-api

    #POSTGRESS
    postgres:
        build: ./postgres
        environment:
            POSTGRES_USER: giri
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: facewebapp
            POSTGRES_HOST: postgres
        ports:
            - "5432:5432"
```

  - Windows Version: 20H2 Build 19042.630
  - Docker Desktop Version: 20.10.0-rc1, build 5cc2396
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
