### ISSUE TITLE
Container init caused mounting [path] to roofs [path] caused - permission denied (on Windows)

### ISSUE THREAD

**Issue by Splik** [docker/for-win#982]
### Expected behavior
Something like notification: 'Check your firewall settings. Did you enable `Hyper V` in `Windows Firewall/Allowed apps`?'

### Actual behavior
I have a brand new Windows10. I've created a small project with docker-compose. 
docker-compose.yml like:

```
version: '2'

services:
    go:
        build: go
        ports:
            - ${GO_PORT}:8080
        volumes:
            - ../server:/go/src/my-module
        working_dir: /go/src/my-module
        command: sh -c 'go run my-module.go'
```

Dockerfile like:

```
FROM golang:latest

RUN apt-get update && \

    # install git
    apt-get install -y git

# install godep
RUN go get github.com/tools/godep

EXPOSE 8080
```

All works fine, but when I run the command: `@docker-compose run go /bin/sh -c 'cd /go/src/my-module && godep restore'`, `godep` tries to copy folder `../server/vendor` from host to container and throws an error:

```
...
Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/D/web/my-project/server\\\" to rootfs \\\"/var/lib/docker/overlay2/ed93aaa8c2fd1333471116ae9a27618b5ebd9dbb502881cf300a2fab31393b37/merged\\\" at \\\"/go/src/my-module\\\" caused \\\"stat /D/web/my-project/server: permission denied\\\"\""
```

**Docker didn't ask the permissions from Windows Firewall. I've spent a lot of hours to find that problem was with Windows Firewall. The simple notification or something like will be good solution to solve this problem.**

### How to fix?

- The 1st solution, go to `Control Panel\System and Security\Windows Firewall\Allowed apps` and enable `Hyper V` (need to tick all `private`):
![sreenshot](https://monosnap.com/file/WVovhSwFpGNjJzyFie2WMdfjThxdZ7.png)

- The 2nd solution, disable `Windows Firewall`

Also, this comment can help to understand: https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/92
