### ISSUE TITLE
Volume mounts stopped working

### ISSUE THREAD

**Issue by brentarias** [docker/for-win#9879]
I have a docker-compose file I started using in February of 2018.  About 2 months ago I ran it again and verified it was still working.  Then I ran it again today, and it won't work. I have evidence this is from a Docker Desktop update. This problem is very similar to [this other ticket](https://github.com/docker/for-win/issues/6680).

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 978544F3-E186-4A85-A756-10FD8C20DB44/20201221063937

### Expected behavior

Running docker-compose launches WordPress and MySQL.

### Actual behavior

```
brent.arias@RM1-P-WS040 MINGW64 ~/OneDrive/wap
$ docker-compose up -d
Creating volume "wap_wpdb" with default driver
Creating wap_db_1 ... error

ERROR: for wap_db_1  Cannot create container for service db: failed to mount local volume: mount C:\Users\brent.arias\OneDrive\wap\wp-db:/var/lib/docker/volumes/wap_wpdb/_data, flags: 0x1000: no such file or directory

ERROR: for db  Cannot create container for service db: failed to mount local volume: mount C:\Users\brent.arias\OneDrive\wap\wp-db:/var/lib/docker/volumes/wap_wpdb/_data, flags: 0x1000: no such file or directory
Encountered errors while bringing up the project.
```

The folder "C:\Users\brent.arias\OneDrive\wap\wp-db" does exist, despite what the error message says.  In Docker Desktop settings, I have "file sharing" configured with that exact path.

### Information

This problem is occurring on two different systems.  Both had a Docker Desktop 2.5xxx version when I observed the problem.  I upgraded one of them to 3.0.0 (50684) and it didn't solve the problem.  

  - Windows Version / Docker Desktop Version (two laptops): 
     - 20H2 (OS Build 19042.630)  / Docker Desktop 3.0.0
     - 2004 (OS Build 19041.630)  / Docker Desktop 2.5.0.0 (49427)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

My complete docker-compose is this:

```
version: '3.2'

services:
   db:
     image: mysql:5.7
     volumes:
       - type: volume
         source: wpdb
         target: /var/lib/mysql       
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: fxxxxxxxs
       MYSQL_DATABASE: axiscode_wpwap
       MYSQL_USER: axiscode_wpwap
       MYSQL_PASSWORD: pxxxxxxx9

   wordpress:
     depends_on:
       - db
     image: wordpress:4.9.4
     volumes:
       #- /c/repos/wpsite1/wp-content:/var/www/html/wp-content
       - .:/var/www/html
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: axiscode_wpwap
       WORDPRESS_DB_USER: axiscode_wpwap
       WORDPRESS_DB_PASSWORD: pxxxxxxx9
volumes:
    wpdb:
      driver_opts:
        type: none
        # device: /c/Users/brent.arias/OneDrive/wap/wp-db
        device: /Users/brent.arias/OneDrive/wap/wp-db
        o: bind
```
In the "volumes" section, the docker-compose file `device` option originally specified `/c` as a prefix in order to work correctly.  Apparently there was a docker update that made the `/c` prefix no longer "correct."  When I ran "compose up" I got an error that the path "C:/c/Users/brent.arias/OneDrive/wap/wp-db" could not be found.  Obviously that wasn't going to work, so I removed the prefix (as shown in the docker-compose file above)...but I still got the error message shown earlier in this post...that the folder does not exist.  Regardless, this demonstrates that indeed there had been a Docker Desktop update related to this problem, or else it would not have been necessary for me to modify a two-year old docker-compose file.

Between each test run, I invoke `docker volume rm wap_wpdb` so that I can make a clean retry.  It doesn't help.

**Comment by cbovar** [comment]
I'm having the same problem (it was working with the same docker-compose file a few weeks ago). On top of that, the folder I'm mounting is on my `D:\` drive so I'm wondering how to specify it now that it is assumed to be `C:\`

**Comment by cbovar** [comment]
I ended up creating external volumes in WSL2 targeting the mounted Windows filesystem:

`docker volume create logs --opt type=none --opt o=bind --opt device=/mnt/d/logs`

and using named volumes in docker-compose.yml:

```
version: '3.4'

volumes:
  logs:
    external: true

  backgroundservice:
    image: backgroundservice
    build:
      context: .
      dockerfile: BackgroundService/Dockerfile
    volumes:
      - logs:/logs:rw
```

**Comment by brentarias** [comment]
I received a Docker update.  I am now at 3.0.4 (51218).  Unfortunately, the error I'm seeing is unchanged.

**Comment by Leffe108** [comment]
I have this problem too. Moving my project folder to c:\ root solves the problem. From reading other posts I think the reason is that I have uppercase folders in the path C:\Users\Leif\Programmering where I keep my programming projects. Using `subst z: .` in my she-docker folder does not solve the problem. Docker seem to force me to move my code to c:\ root or other location with only lower case file names.

```cmd
C:\Users\Leif\Programmering\Php\she-docker>docker --version
Docker version 20.10.5, build 55c4c88
```

```yml
version: '3.3'
services:
  she:
    image: php:7.4-apache
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8000:80"
    restart: always
volumes:
  src: {}
```

```cmd
C:\Users\Leif\Programmering\Php\she-docker>docker-compose up
Recreating she-docker_she_1 ... error

ERROR: for she-docker_she_1  Cannot start service she: error while creating mount source path '/run/desktop/mnt/host/c/Users/Leif/Programmering/Php/she-docker/src': mkdir /run/desktop/mnt/host/c/Users/Leif/Programmering: file exists

ERROR: for she  Cannot start service she: error while creating mount source path '/run/desktop/mnt/host/c/Users/Leif/Programmering/Php/she-docker/src': mkdir /run/desktop/mnt/host/c/Users/Leif/Programmering: file exists
ERROR: Encountered errors while bringing up the project.
```

But if I copy my code folder to c:\ root it works fine and my src/index.php file is mounted correctly.

```cmd
C:\she-docker>docker-compose up
Removing she-docker_she_1
Recreating e4978cdff4b6_she-docker_she_1 ... done
Attaching to she-docker_she_1
...
```
