### ISSUE TITLE
Starting quite many services seems to break Docker built-in DNS?

### ISSUE THREAD

**Issue by 1605200517** [docker/for-win#988]
### Expected behavior
I can launch services and even after some time they boot up.

### Actual behavior
One of the services, cassandra-seed, cannot start because it cannot establish its broadcast address.

**Error:**
foo_cassandra-seed.1.4f8l3zacroeb@moby    | ERROR [main] 2017-08-08 15:41:23,174 CassandraDaemon.java:752 - Exception encountered during startup: Unknown broadcast_address 'cassandra-seed'

Other containers cannot ping cassandra-seed. No ping from itself possible neither.
With less services all works fine.

### Information

  - Diagnostic ID : 99071758-71EE-4434-938A-45DEF36AD8C5/2017-08-09_10-24-59
  - a reproducible case: see below
  - Version/Host: Version 17.07.0-ce-rc1-win21 (12927) Channel: edge / 76a8c4b under Windows 10

Fragment from the stack YML definition:

```
cassandra-seed:
    image: ${IMAGE_CASSANDRA}
    depends_on:
      - cassandra-master
    networks:
      mynetwork:
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-seed
      CASSANDRA_SEEDS: cassandra-master
      CASSANDRA_START_RPC: "true"
      _JAVA_OPTIONS: "-Xmx2g -Xms1g"
    labels:
      monitor: "yes"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
```

### Steps to reproduce the behavior
Reference machine: Windows 10, a Dell with 4 cores and 32GB RAM, 75% of these resources dedicated to Docker daemon.
  1. Create a stack with many different services (20+) and a small cassandra cluster (master and seed)
  2. Launch stack
  3. cassandra-seed service keeps status Rejected; "docker service logs" reveals the above error.

Please tell me if you can see anything from the diagnostics.
