### ISSUE TITLE
Named volumes are not accesable after first run of docker-compose on Docker/WSL2

### ISSUE THREAD

**Issue by jgfrm** [docker/for-win#9903]
### Expected behavior

local named volumes can be used in docker-compose, e.g.
```
volumes:
  myvol:
    driver: local
    driver_opts:
      type: none
      device: $PWD/dir
     o: bind
```
### Actual behavior
First run succeeds, but subsequent runs result in:
ERROR: for xxx  Cannot start service xxx  : error while mounting volume '/var/lib/docker/volumes/myvol_xxx/_data': failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/40206a5143c54960ebf25309d904f014cadf9bd69ccb7b9b409209b41a59db89:/var/lib/docker/volumes/myvol_xxx//_data, flags: 0x1000: no such file or directory

### Information
Reproducible, Docker for Win 3.0.0, WSL2 (2004 build)
